### ISSUE TITLE
Refseq mapping - Getting more info out if ipyparallel

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#10]
There's a pretty heavy blackbox around ipyclients, if calls to binaries inside them fail they dont' do a good job of communicating this. I know there's a way to get ipyclients to be more chatty/return useful stuff, i just haven't figured out how to do it yet.

**Comment by dereneaton** [comment]
Agreed, this is really important and would be very helpful to solve.

**Comment by dereneaton** [comment]
So it looks like each engine reports it's own errors into a logfile with its pid in ~/.ipython/profile_default/log/ipengine-[pid].log. 

At least it's somewhere for us to look while coding, but not all that helpful for debugging user errors, I suppose. Maybe there is a way to turn off or redirect the logging...

**Comment by dereneaton** [comment]
The ipcontroller's are now named ipyrad[id=xxx] where xxx is randomly generated during __init__. This ensures that we can close ipcluster for a single IPython/Jupyter session of ipyrad without it messing up other things using ipcluster. This doesn't necessarily help with debugging, but I thought it would be helpful to mention here.

**Comment by dereneaton** [comment]
Logging can now be tracked by creating a logger in the module script (see example in `demultiplex.py`) and checking its output in the global logger. 

While debugging keep an extra shell watching the debugger with: `tail -f /tmp/ipyrad_debug.txt`
