### ISSUE TITLE
ipyrad -r - Don't truncate output

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#101]
Dumping stats with -r, if you have too many individuals the output gets chopped off. It'll print like 25 and then '...' and then 25 more, looks like this:

        cra-ant-72857-Amazonas-Duraznopampa          150802  
        cra-ant-72858-Amazonas-Duraznopampa          187453  
        cra-ant-72859-Amazonas-Duraznopampa          165804  
        ...                                             ...  
        cra-ant-72895-Ancash-Chinchan                177130  
        cra-ant-72896-Ancash-Chinchan                192412  
        cra-ant-72897-Ancash-Chinchan                116297  

Should make it actually write stats and info for all samples.

**Comment by dereneaton** [comment]
I think we just need to change the pandas options when using -r option. 
it's something like:
```
pd.set_options("display.rows", 1000)
```

**Comment by isaacovercast** [comment]
Fixed. inside stats() set pd.set_options("display.rows", len(self.samples))
