### ISSUE TITLE
require name when creating params.txt

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#102]
It seems like it would be consistent to require a name when creating a new params file with -n option, and that the name should always be appended to the paramsfile name. e.g.,:

```
## create a new param file with assembly_name data1
ipyrad -n data1

created new file: data1-params.txt
```

Should be pretty easy with some edits to `__main__`.py

**Comment by isaacovercast** [comment]
Deren fixed this. Also, i tested and it does not overwrite current params without the --force flag. Also changed new params.txt file creation to make the format of `-n watname` == `params-watname.txt`.
