### ISSUE TITLE
Refseq - Rename assembly methods

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#104]
Assembly method names are still confusing. Deren suggested:

1) denovo
2) reference (this is the former reference_only)
3) reference_add (this is the former hybrid, it adds denovo to ref)
4) reference_sub (this is the former denovo_only, it subtracts denovo from ref)

What about:
1) denovo
2) reference (former reference_only)
3) denovo+reference
4) denovo-reference

**Comment by dereneaton** [comment]
OK, I agree those names are more clear than our previous ideas.

**Comment by isaacovercast** [comment]
Done. f4cb48f
