### ISSUE TITLE
stats storage and the -r flag for CLI

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#109]
I want to store stats in two ways: 

```
self.stats = a dictionary storing data frames of stats results
    self.stats.summary = a data.frame with just the most important stats
    self.stats.s1 = step1 results
    self.stats.s2 = ...
    self.stats.s3 = ...
    self.stats.s4 = ...
    self.stats.s5 = ...
    self.stats.s6 = ...
    self.stats.s7_loci = ...
    self.stats.s7_samples = ...
    self.stats.s7_snps = ...

self.statsfiles = paths to the saved stats files (printed data frame)
    self.statsfiles.s1 = "/home/user/rad/fastqs/s1.results.txt
    self.statsfiles.s2 = ...
```

What do you think?

And then for the CLI the -r output would print only self.stats.summary and self.statsfiles.keys()

**Comment by isaacovercast** [comment]
I think that sounds good. As it is now the -r output is kind of unwieldy, pawing through the whole thing can be annoying if all you're really interested in is what state each sample is in (which i have done quite often). What do you imagine will be the most important stats in the summary? The sum of total reads passing each step for all samples? That might be a good approximation of information people might be interested in.

**Comment by isaacovercast** [comment]
fixed.
