### ISSUE TITLE
Refseq mapping - parellelize smalt?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#11]
So smalt handles threading for itself internally. It produces significant performance benefits with additional processors. It's not clear to me how to do this inside ipyparallel, since i believe ipyparallel clients are probably only assigned one process? And probably can't grab more if they want to? It'll take some experimenting.

**Comment by dereneaton** [comment]
Take a look at the code in cluster_within.py, specifically the "threaded_view" object, which assigns multiple threads to a single process.

**Comment by dereneaton** [comment]
I believe this is solved.
