### ISSUE TITLE
assembly._launch2() - "too many open files" exception

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#110]
I have a hunch this is a mac problem. Or maybe even a "my machine" problem, be good to figure out regardless.
```
$> launchctl limit maxfiles
        maxfiles    256            unlimited  
```

Tried `launchctl limit maxfiles 10000` and it didn't help. Wouldn't let me set it to unlimited. I think this is a red herring.

**Comment by dereneaton** [comment]
Fixed, ensures ipyclients are always closed.
