### ISSUE TITLE
mergepairs is not merging all mergeable pairs

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#112]
I raised a ticket with the vsearch crew cuz I'm out of ideas on this one:

https://github.com/torognes/vsearch/issues/162

**Comment by dereneaton** [comment]
When I align my test example with the program PEAR I also get a wonky result:
```
## PEAR_OUTPUT

@d41732_35919_c1
TGCAGGTCACCCCACGGTGGTCGAGACGCTTGCTAGCGCAAGCTCCTCGACCACCGTGGGGTG
+
BBBBBHHGHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIBHIIAHHFF=B


## Original sequences aligned by hand:

TGCAGGTCACCCCACGGTGGTCGAGGAGCTTGCGCTAGCAAGCGTCTC                     R1
       CACCCCACGGTGGTCGAGGAGCTTGCGCTAGCAAGCGTCTCGAGACCA--------      R2
       	       	       	       	 --    	       	       --------      what's going on here?
                               deleted  	          new insert
```

Why would PEAR delete part of that GC repeat, and how does it come up with that extra sequence at the end (`GTGGGGTG`) completely out of nowhere? The R1 and R2s are the same length for both pairs in the input files.

**Comment by dereneaton** [comment]
I see that vsearch does the same thing, actually. It also appends (`GTGGGGTG`) to the end. What could this mean?

**Comment by dereneaton** [comment]
It seems to be doing something funky with a tiny palindrome in the middle of the sequence...

```
TTGCGCTAGCAA  palindrome in original matching seq
AACGCGATCGTT  revcomp of the palindrome

TTGC--TAGCGCAA  reverse of the revcomp with inserts
TTGCGCTAG--CAA  original with inserts
```


I guess this is why it removes the GC repeat. But the whole sequence doesn't continue as a palindrome, so it seems like whatever it's trying to catch is messing it up...

**Comment by dereneaton** [comment]
Welp, the solution was that the R2 should not be revcomped before being entered. The second pair should not have been merging at all. Make sure to set stringent checks for bad mergers.

**Comment by isaacovercast** [comment]
Good sleuthing!
