### ISSUE TITLE
CLI - implement -m flag for merging assemblies

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#120]

**Comment by isaacovercast** [comment]
Make a new assembly for the new merged assembly: `ipyrad -m <new_assembly_name> <assembly_1> <assembly_2>`

**Comment by isaacovercast** [comment]
just deepcopies all of the samples into a new Assembly, and complains if the parent assemblies have a difference in their params besides file paths

**Comment by dereneaton** [comment]
now working.
