### ISSUE TITLE
Step 6 - error in fill_superseqs()

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#129]
Glenn's GBS data failed in step 6. says this:

```
INFO:ipyrad.assemble.cluster_across:chunkseqs is (1000, 94, 640)
Caught unknown exception - index 1000 is out of bounds for axis 0 with size 1000
...
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.1.73-py2.7.egg/ipyrad/assemble/cluster_across.py", line 525, in fill_superseqs
        chunkseqs[iloc] = fill                                                                                                                           
IndexError: index 1000 is out of bounds for axis 0 with size 1000  
```
Will update with more info when i figure out what's up...

**Comment by dereneaton** [comment]
Dang, I gotta figure that one out. I've run into it before too, but not in simulated data. Must have something to do with the chunking...

**Comment by dereneaton** [comment]
I fixed the problem, but found while doing it that the h5 array is not properly using chunking, which means its loading the whole array into memory when it writes to it. For a single lane data set this is up to 40GB, I think. So definitely NOT efficient. Working on that. But at least it doesn't crash anymore.

**Comment by dereneaton** [comment]
Maybe I'm wrong, it does seem to be chunking the data... I'll have to do some checks to make sure we don't have memory load issues, but fwiw I'm closing this issue.
