### ISSUE TITLE
adding mapped and unmapped reads to sample.self.stats?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#13]
Have any thoughts on this one way or the other? My thoughts are "its' a convenient place to store this info, but it's also annoying to have two columns of stats that say NaN for many if not most users who wont' be using ref seq mapping".

**Comment by dereneaton** [comment]
Hmm, agreed. Maybe we could rig up the .stats attribute to not print columns that are all NaN.

**Comment by isaacovercast** [comment]
Changed the return call in assembly.stats to:

                return pd.DataFrame([self.samples[i].stats for i in nameordered],
                      index=nameordered).dropna( axis=1, how='all')

axis = 1 sets column-wise
how='all' says only drop if all values are NaN
