### ISSUE TITLE
ipcluster in __init__ is a bad idea

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#14]
Launching ipcluster in ipyrad/\__init\__.py is troublesome because when it launches each new engine they each run \__init__ and thus start their own new ipcontrollers. This ends up leaving behind lots of zombie controllers. 

Alternative ideas: 
1. Go back to telling users to start ipcluster outside of ipyrad. Downside: this is not very Pythonic.

What I'm thinking:
2. Launch ipcluster during Assembly object __init__. This seems reasonable. All functions that will need to be parallelized will be called off of Assembly objects, and this allows users to change the controller (e.g., Local, MPI, PBS) with the paramsdict. Also Assembly objects can store the controller_id for more secure shutdown. There is not really a problem with separate Assembly objects opening separate ipclusters at the same time. 

I'm working on implementing the latter approach now.

**Comment by isaacovercast** [comment]
Sounds totally reasonable. I agree that having users launch their own clusters should be avoided.

**Comment by dereneaton** [comment]
Merged changes into master.
