### ISSUE TITLE
muscle_align2 isn't working (bad arg structure)

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#15]
Looking in ~/.ipython/profile_default/log/ipengine-*.log i see it reporting this:

        muscle_align2() takes exactly 4 arguments (1 given)

Function def of muscle align is: 

        def muscle_align2(data, sample, chunk, num):

but the call looks like this cluster_within.py:573:

               lbview.map(muscle_align2, submitted_args)

It looks like it just needs to have the function def changed to accept a list of args, and then suck all the args out at the top of the call, just like clustall(). I can make this change  but wasn't sure if you had a something specific in mind.

**Comment by dereneaton** [comment]
That sounds right. Step3 is especially broken right now with the new fastq files format. I'll work on getting the de novo method running again too.

**Comment by isaacovercast** [comment]
This is fixed now.
