### ISSUE TITLE
Step 4 fails silently

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#152]
Not sure yet why it is failing for robin yet, but if you run preview mode with a sufficiently small chunk of data then some samples fail step 3, and most samples have very few or no clusters. not sure if it's the failing samples or the few/no clusters, but when you run step 4 it appears to work, but the logs report all samples failing. It writes out hetero_est and error_est as NaN, so when you run step 5 it fsck (which is what's happening to robin). 

Step 4 should at least not fail silently, better would be for it to actually work in this situation...

**Comment by dereneaton** [comment]
Fixed this quite a while ago with better ipyparallel exception handling.
