### ISSUE TITLE
Fail gracefully when ipcluster can't initialize

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#16]
If you start an instance of a notebook that fires up a cluster, then you close the notebook without shutting it down, the cluster stays running. Then if you try to run an instance of ipyrad from the command line you get this nasty error message:

        IOError: Connection file '~/.ipython/profile_default/security/ipcontroller-ipyrad-54048-client.json' not found.

Maybe we can test for success firing up the cluster and if it fails then fail more explicitly.

**Comment by isaacovercast** [comment]
Having trouble getting pyrad to run from the cl at all, will continue to investigate.... See ipyrad/__main__.py in the refseq branch for the dummy test code i've been using to run `python ipyrad`.

**Comment by dereneaton** [comment]
I ran into some problems as well and had to update jupyter-client and ipykernel to get the console installation to work. I can add these requirements to the setup.py. 

When I run the `ipyrad` CLI on the refseq branch it successfully launches the engines but fails in set_params() when trying to find the Mus data. It seems to shut down the engines correctly, though.

Is the MusChr1.fa test file too large to add to tests/data?

**Comment by isaacovercast** [comment]
That did it. minor version update for jupyter-client. I was having trouble
with ip.load_assembly(), but not the raw Assembly() constructor. It works
now.

The MusChr1.fa is 200 Megs. You think that's too big?

**Comment by isaacovercast** [comment]
Also, question: In the latest version it looks like Assembly.dirs.edits got
removed, which is fine but i see inside Assembly.set_params that
self.dirs["fastqs"] is set by both raw_fastq_path and sorted_fastq_path, i
haven't thought enough about if there's a use case having these be
separate, but wanted to verify with you this is the correct behavior....

**Comment by isaacovercast** [comment]
Disregard -> " Assembly.dirs.edits got removed". I'm at the theater trying
to get some work done between reel changes, so my attention is a little
fragmented. my bad.

**Comment by dereneaton** [comment]
Yeah, 200M is pretty big. We can use it for our own testing, but we should probably provide a smaller reference in the data eventually for user testing. 

Thoughts: 
Maybe a plastome sized reference would be good. I was actually thinking how this might be a good example case since many users might be more likely to have a chloro or mito genome available than a nuclear one. If that's the case, we would want an option for the hybrid approach to output the reference (plastome) and denovo (nucelar) data separately in the end.

**Comment by dereneaton** [comment]
CLI seems to be working now. I pushed changes Master's \__main\__ so the CLI can create and parse params files. The params file formatting will need to be updated still (e.g., no reference options yet).
