### ISSUE TITLE
max_fragment_length unnecessarily doubled for 'pair'

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#162]
`max_fragment_length` is calculated from the data during cleanup of step 3. The length is calculated from the merged reads for PE, so this value really should be the max observed length. cluster_across, consens, write_outfiles and jointestimate all pull in this value from the hackersonly dict and then double it for `pair` and `gbs` datatypes. This shouldn't be necessary, and should result in unnecessary file bloat.

**Comment by dereneaton** [comment]
Yeah, I agree it's bloated for paired data right now, which definitely slows us down and wastes disk space. I think step6 still uses `max_fragment_length*2` somewhere. We'll just need to replace that with some call to get the max len from the samples.

**Comment by dereneaton** [comment]
Fixed. No more bloat.
