### ISSUE TITLE
hard coded filenames make it difficult to exchange files between machines

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#165]
A simple solution would be to always reference files relative to the working directory. That way a user only has to edit their working directory and all subdirectories should match up.

Examples. 
data.dirs.working = "home/deren/test"
data.dirs.consens = "data_consens"

Similarly, we should move towards not referencing the sample.files.{} attributes to find filenames, and using them instead to simply to store metainformation.

**Comment by dereneaton** [comment]
I'm working on this. It requires a lot of changes to the code, so it will certainly be a v.0.4.0 milestone, but I think it's really worth it. 

Since I'm doing this I'm also going to try to overhaul and simplify the JSON structure. This will probably also require another upgrade function to move between older and newer assemblies.

**Comment by isaacovercast** [comment]
Moving assemblies is an unsupported feature.
