### ISSUE TITLE
Allow setting min_samples_locus per population

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#166]
This was a popular option in pyrad that allows filtering your data such that there are at least N samples per population per locus. I figure we should implement this first, then we can add the population-aware output formats like treemix and migrate. 

This should not be difficult to implement, the question is just how best to input the information. We could allow min_samples_locus to be entered as a dict, e.g., {pop1: 4, pop2: 5, pop3: 10}, which would be pretty cool; or we could allow users to enter a filename similar to the pop assign file. But if that's the case, maybe we should just have users enter the information into the pop_assign_file itself somehow. 

@isaacovercast what are your thoughts?

**Comment by isaacovercast** [comment]
The dict seems good for the API users. For the CLI users i think it makes sense to use the pop_assign_file, maybe have an optional first line  like this:
```
minsamples: pop1=5, pop2=6, pop3=10
```
It's not ideal, but i think it would also be clumsy to have two separate population specification files. Or something. I imagine we could parse the pop file, and if there is a line indicating minsamples per pop then we can parse that too, maybe raise an error if one of the populations isn't indicated? I think something like this could work.

**Comment by dereneaton** [comment]
This was just requested again. I like your idea of parsing the pop file IF the first line has minsamples: on the first line.

**Comment by dereneaton** [comment]
I've got it working in the master branch now. Will push it in the next version.

The CLI populations.txt file format is like normal, but with the option of adding minimum sample per pop values on a commented line separated by either spaces or commas. These values will override the minsamples_locus value. The minsamp values can be on a single line, or over multiple lines. 

```
1A_0 a
1B_0 a
1C_0 a
1D_0 a
2E_0 b
2F_0 b
2G_0 b
2H_0 b
3I_0 c
3J_0 c
3K_0 c
3L_0 c

## a:3 b:3 c:3
```

Similarly, in the API you can use the `_link_populations()` function directly with two input dicts:
```
base.popdict = {"prz": ["32082_przewalskii", "33588_przewalskii"],
                "cya": ["29154_superba", "30686_cyathophylla", 
                        "41478_cyathophylloides", "41954_cyathophylloides"],
                "rex": ["30556_thamno", "33413_thamno", "35236_rex",
                        "35855_rex", "38362_rex", "39618_rex", "40578_rex"]}
base.popmins = {'cya':4, 'rex':4, 'prz':0}
base._link_populations(base.popdict, base.popmins)

## print resulting dict
base.populations
```
```
{'cya': (4,
  ['29154_superba',
   '30686_cyathophylla',
   '41478_cyathophylloides',
   '41954_cyathophylloides']),
 'prz': (0, ['32082_przewalskii', '33588_przewalskii']),
 'rex': (4,
  ['30556_thamno',
   '33413_thamno',
   '35236_rex',
   '35855_rex',
   '38362_rex',
   '39618_rex',
   '40578_rex'])}
```
