### ISSUE TITLE
single-writer for demultiplex.py

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#167]
I made a bunch of changes to demultiplex.py and now it's running much more efficiently in parallel, however, there is still a huge holdup when each engine tries to write its output to disk. Essentially all of the data sits in the buffer waiting for the OS to sort out who's turn it is to write next. From what I've been reading, this is a bad idea, and only slows things down. 

Here's another idea: It would be better for each engine to return the results in an array with the following information: 

```
## create an empty array, (uint 16 allows up to 32767 barcodes)
array1 = np.zeros((nreads, trim1, trim2), dtype=np.int16)
```

The engines jobs will fill the array with the 1-indexed sample name that it matched to or zero if no match, and will fill the trim1 and trim2 columns with the number of bases to trim from each side to remove barcodes. 

A single writer engine (e.g., engine 0) will receive these arrays, then read through each raw file again, pulling out and writing to the appropriate sample file the trimmed reads. This not only removes having simultaneous calls that are writing to disk, but also reduces the need to concatenate multiple files at the end into a single sample, which in our current method also takes a bunch of time. 

Anyways, we should try implementing this. Until then, things are fast enough to run in reasonable time now, though.

**Comment by dereneaton** [comment]
I haven't tried this yet, but with this problem in mind I can think of at least two other parts of the code that seem to be suffering a similar problem of being limited by writing to disk, and where we only exacerbate it by running parallel. The first is in running step2, which might run faster if written in a similar way to described above. For example, if the user does not want to implement any filtering on the data then we would not even need to read and write it again, but could instead just call data.files.edits = data.files.fastqs. A second instance is during dereplicating by vsearch. On big data sets this actually takes a while because the parallel jobs are all fighting each other. It would make more sense to allow vsearch to use threads on this for one sample at a time rather than parallelize them.

**Comment by isaacovercast** [comment]
stale.
