### ISSUE TITLE
VCF output 

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#168]
Several problems: 
- It goes very fast and then sits at 100% for quite a while.
- Should be numba compiled to run faster
- Should output reference locations
- First column seems to be empty (bug!)

**Comment by dereneaton** [comment]
The long wait time at the end is from concatenating all the chunked files. This can be done more efficiently.

**Comment by isaacovercast** [comment]
Also might be nice to optionally only write out snps to the vcf, rather than all the sequences. Makes the vcf HUGE, and most people are really only interested in the snps anyway. We could add a flag for the output_format param to specify full vcf or just snp vcf.

**Comment by dereneaton** [comment]
Indeed, hoping to implement this soon.

**Comment by dereneaton** [comment]
We now produce the snps only vcf (v) by default, with the option to produce the full (V).
