### ISSUE TITLE
Refmapping (step3) - test for gzip reference sequence

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#175]
For some reason  samtools only wants bgzip'd reference sequences, not gzip. Should test for gzip format, maybe just unzip or warn and make the user do it.

**Comment by dereneaton** [comment]
Yeah, I think we can just test for gzip, and if so, pipe it into samtools while unzipping it; or alternatively,  unzip it into a temp file, pass the temp file to samtools, and then delete it after.

**Comment by isaacovercast** [comment]
fixed 0894b45
