### ISSUE TITLE
AssertionError(R1 and R2 files are not the same length.)

### ISSUE THREAD

**Issue by jldimond** [dereneaton/ipyrad#182]
This is what I get a few minutes into starting step 1. None of my R1 and R2 files are the same size for a given library, but isn't ipyrad able to deal with this?

**Comment by isaacovercast** [comment]
The R1 and R2 files will almost certainly be different sizes (in bytes), but this error is raised if they are different lengths in terms of number of reads. We are assuming that every read in the R1 file has a matching read in the R2 file, and if the files are different lengths then something is wrong. R1 and R2 files that come off the sequencer __should__ be identical in terms of number of reads. If they aren't then something is goofy. Can you run it again with the `-d` flag and attach the ipyrad_log.txt here?

**Comment by jldimond** [comment]
[ipyrad_log.txt](https://github.com/dereneaton/ipyrad/files/468196/ipyrad_log.txt)

**Comment by jldimond** [comment]
So it sounds like ipyrad is trying to match R1 and R2 line for line. I figured it was using a unique number code for each read to match them.

**Comment by isaacovercast** [comment]
Hm, not much help. Can you try getting a line count for your raw data files. Assuming your R1 file is called input_R1_.fq.gz then you can do this:

gunzip -c input_R1_.fq.gz | wc -l

Do the same thing for the R2 file. The number of lines in each file should be identical. Let me know what the output of these commands is.

**Comment by jldimond** [comment]
!gunzip -c ../Raw_data_JD001/JD001_A_S21_L004_R1_001.fastq.gz | wc -l

 88358900

!gunzip -c ../Raw_data_JD001/JD001_A_S21_L004_R2_001.fastq.gz | wc -l

gunzip: invalid compressed data--crc error
gunzip: ../Raw_data_JD001/JD001_A_S21_L004_R2_001.fastq.gz: uncompress failed
    9182

**Comment by jldimond** [comment]
Not sure why the error message for R2...

**Comment by isaacovercast** [comment]
Looks like we cracked it. The R2 file is corrupt. Can you download a new copy of that file?

**Comment by jldimond** [comment]
Doing it right now

**Comment by jldimond** [comment]
Thanks Isaac - they do in fact have identical numbers of lines!

Sorry you are fielding so many newbie questions for me.

!gunzip -c ../Raw_data_JD001/JD001_A_S21_L004_R1_001.fastq.gz | wc -l

 88358900

!gunzip -c ../Raw_data_JD001/JD001_A_S21_L004_R2_001.fastq.gz | wc -l

 88358900

**Comment by isaacovercast** [comment]
Aww yeah! Glad we figured it out. Happy to help.
