### ISSUE TITLE
Executables not installed?

### ISSUE THREAD

**Issue by StuntsPT** [dereneaton/ipyrad#185]
the documentation states that the following executables are installed:

**Executables**:  

* vsearch_ -- used for de novo clustering
* muscle_ -- used for sequence alignment
* smalt_ -- used for reference mapping
* samtools_ -- used for reference mapping
* bedtools_ -- used for reference mapping
* hdf5_ -- used for large array storage/access
* mpich_ -- used for parallelization (mpirun, mpiexec)

But I can't seem to find any of them installed by conda (I do find my local copies). 
Could be related to #184.

**Comment by isaacovercast** [comment]
The binaries are installed inside the python package. You won't see them in your regular path, but the ipyrad script will know where they are. If you are really curious they are installed here:

`<conda_install_dir>/pkgs/ipyrad-0.3.41-0/lib/python2.7/site-packages/bin/`

**Comment by StuntsPT** [comment]
Found them. Not sure why `mlocate` won't find them, even after updatedb, but now that I'm diving into the packaging I found them.
