### ISSUE TITLE
Handling of clusters that contain linked pairs and merged reads

### ISSUE THREAD

**Issue by edgardomortiz** [dereneaton/ipyrad#194]
When the clusters consist of linked pairs and merged reads, the pairs separators are turned from "nnnn" to "NNNN" and the cluster is not aligned by halves like the ones consisting of only pairs. Maybe in this case the separators can be removed and just aligned directly with the merged reads, or maybe if there is just a couple of merged reads causing the problem they can be removed or viceversa.

![2016-10-18 08 41 03 pm](https://cloud.githubusercontent.com/assets/5767612/19502653/16921a78-9574-11e6-8fe6-740b9fac93ff.png)

**Comment by edgardomortiz** [comment]
I realized this could also add Ns to the consensus sequences and filter out the locus after step 5. I added:
`seqs = [i.replace('nnnn','') for i in seqs]`
after line 203 in `cluster_within.py` and the resulting alignments are cleaner, and their consensus sequences don't have the extra Ns introduced by the separators `NNNN`

**Comment by isaacovercast** [comment]
This works as expected now, not sure when it was fixed.
