### ISSUE TITLE
Step 7 - MemoryError()

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#203]
A couple users are seeing this:  IPyradWarningExit: error in vcf build chunk 0: MemoryError()

```
Step 7: Filter and write output files for 91 Samples
[####################] 100% filtering loci | 0:00:54
[####################] 100% building loci/stats | 0:00:09
[####################] 100% building vcf file | 0:00:40
Encountered an error, see ./ipyrad_log.txt.
error in vcf build chunk 0: MemoryError()
```

**Comment by isaacovercast** [comment]
@amelymartins and @LinaValencia85

**Comment by isaacovercast** [comment]
Each parallel client loads the entire catg and then subsets based on sidx. This is crashing pretty fast (40 seconds), so I think it's a memory bottleneck. If you're running lots of parallel clients it wouldn't take that many threads to chew up 64GB..

**Comment by dereneaton** [comment]
fixed.
