### ISSUE TITLE
Save Assembly objects as JSON

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#21]
Currently we're saving Assembly objects by pickling (using dill, actually), but JSON would be much better since it is more human readable and can be understood by non Python programs. From what I've seen there is some weird behavior in using the JSON module so that it requires finagling dicts into tuples, or something or other. So if we go this route the load_obj function will need a lot more work to parse the data back in properly. Not sure how well it works with Pandas DataFrames either. It's worth looking into, though.

**Comment by isaacovercast** [comment]
fixed
