### ISSUE TITLE
Clean up intermediate files

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#210]
Lots of trash hanging around clogging up disk. These are files I think we can safely clean up at the end of each step:

step2: 
- *trimmed_R*_.fastq.gz
- *_merged_.fastq
- *_concat.fq.gz (these files are created if assemblies with duplicate samples are merged before step2. They do not take that long to make, and so should be deleted right after they're used. In fact, we could probably replace their existence with a piped 'cat' command if we were trying to be uber efficient. But just deleting at the end of step2  is fine for now. 

step3:
- *utemp, 
- *utemp.sort
- *htemp 
- *clust.gz

step3 (refmap):
- *sam
- *unmapped.bam, 

step4/5/6: (From `{name}_consens` dir)
- *.tmp
- *.htemp
- *.utemp
- *.utemp.sort

**Comment by dereneaton** [comment]
A note: we should make sure to include the `assembly_name` in any regular expressions that we use to grab files for deletion to ensure we do not delete files that a different assembly might be using if a user were to be running two instance of ipyrad simultaneously.

**Comment by isaacovercast** [comment]
done. Feels much better.
