### ISSUE TITLE
ipyrad exits with an error when clustered samples are not sufficiently represented.

### ISSUE THREAD

**Issue by StuntsPT** [dereneaton/ipyrad#218]
In my case, as shown in gitter, I have a dataset with one sample that has nearly 100% missing data, called "Sin17".
When analysing this dataset, ipyrad exits with the following error on step 7:

```
Step 6: Clustering at 0.85 similarity across 93 samples 
[####################] 100%  concat/shuffle input  | 0:00:15 
[####################] 100%  clustering across     | 0:05:29 
[####################] 100%  building clusters     | 0:00:21 
[####################] 100%  aligning clusters     | 0:12:07
[####################] 100%  database indels       | 0:00:36
[####################] 100%  indexing clusters     | 0:00:49
[####################] 100%  building database     | 0:07:22 
Step 7: Filter and write output files for 94 Samples The following Samples do not appear to have been clustered in step6 (i.e., they are not in /home/francisco/GBS/ipyrad_0.5.15/qsuber01_outfiles/qsuber01.hdf5). Check for typos in Sample names, or try running step6 including the selected samples. 

Missing: Sin17 

ERROR:ipyrad.core.assembly:'Sin17' is not in list

Encountered an unexpected error (see ./ipyrad_log.txt) Error message is below ------------------------------- 
'Sin17' is not in list
```
The suggested workaround by @dereneaton (branching and removing the problematic sample) did the trick, but since this was suggested as a bug I though of opening the issue here.
I expected ipyrad to either just drop the sample automatically, or keep it in the final VCF (et al.) with 100% missing data.

**Comment by StuntsPT** [comment]
Actually the workaround did not solve the issue and Step7 still exits with the same error, despite the number of samples being consistent on both step6 and step7.

**Comment by isaacovercast** [comment]
This is fixed in v.0.9
