### ISSUE TITLE
option to output unlinked vcf

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#220]
This seems useful. I looked at the vcfchunk code and I didn't see a _super_ straightforward way to do it, but i'm sure it's not too hard.

**Comment by dereneaton** [comment]
I figured that there was probably a way to subsample SNPs from the vcf using something like vcf-tools. Like that you could put in a min distance between them or something. Maybe not? Another option is that we create a copy of the same VCF file but with the filter flag turned on for all SNPs except one per locus. That would be less work than writing a separate file, maybe. But then again we already calculate a subsampled array of SNPs, so maybe we should just use that one... I'm thinking on it.

**Comment by dereneaton** [comment]
Looks like vcftools can do it with the `--thin` argument. Setting it to a value much larger than a RAD locus (e.g., 5000) will allow only one SNP per locus. It looks like it grabs the first SNP, I'm not sure if you can tell it to grab a random one, but it's a start. 

```
vcftools --vcf mydata.vcf --thin 5000 --recode --recode-INFO-all --out mydata
```
