### ISSUE TITLE
Add treemix output format

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#223]
Looks pretty straightforward. From the manual:
```
By default, TreeMix assumes biallelic sites. The input file is a gzipped file that consists of a header
with a space-delimited list of the names of populations, followed by lines containing the allele counts
at each SNP. It is assumed that the order of the SNPs in the file is the order of the SNPs in the
genome. The line is space delimited between populations, and the two allele within the population
are comma-delimited. For example:
pop1 pop2 pop3 pop4
5,1 1,1 4,0 0,4
3,3 0,2 2,2 0,4
1,5 0,2 2,2 1,3
```

**Comment by dereneaton** [comment]
Yeah we should definitely make this. Now that we have popfile parsing it should be simple. There is an example in the old pyrad code to build it from a loci file, so we could make a loci2treemix function. Or, if we want it to be faster, we should build it from the large h5 arrays like everything else.

**Comment by dereneaton** [comment]
Now available. See TREEMIX section here: http://ipyrad.readthedocs.io/analysis.html
