### ISSUE TITLE
Update quickstart_API notebook

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#224]
Still has calls like this:
```
data1.step1()
```

Also would be good to add more explicit language to this quickstart about firing up ipcluster.

**Comment by isaacovercast** [comment]
Sorry, this is specifically: tests/quickguide_API.ipynb, not an emergency, but prob good to do eventually.

**Comment by dereneaton** [comment]
I've been working on better tutorials for API and ipcluster. For now I have many empirical examples I could put up, this one is already listed in the `analysis` section; (http://nbviewer.jupyter.org/github/dereneaton/ficus-rad/blob/master/Ficus_Jander_assembly.ipynb).

But yeah, that API guide is super outdated. I'll work on it.

**Comment by isaacovercast** [comment]
Stale.
