### ISSUE TITLE
ABBA-BABA analysis

### ISSUE THREAD

**Issue by tangerzhang** [dereneaton/ipyrad#228]
Hi,
I am wondering how to use ipyrad to perform introgression analysis?
I did not see any description in the document. But it seams that ipyrad is cable of ABBA-BABA analysis in the related publication.
Thanks!

**Comment by dereneaton** [comment]
Hi @tangerzhang, 
There are methods in active development. We need to do a bit more work before making them public though. I will let you know when it is ready, hopefully very soon.

**Comment by isaacovercast** [comment]
ipyrad/analysis/baba.py
