### ISSUE TITLE
Support for quaddRAD

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#233]
Low priority, but something for a rainy day. Quadruple barcoded. Whee!

quaddRAD: A new high-multiplexing and PCR duplicate removal ddRAD protocol produces novel evolutionary insights in a non-radiating cichlid lineage

http://onlinelibrary.wiley.com.ezproxy.gc.cuny.edu/doi/10.1111/mec.14077/full

**Comment by isaacovercast** [comment]
Here's another esoteric data type: tGBS: https://academic.oup.com/nar/article/4210942

**Comment by o-william-white** [comment]
Hi Isaac, is it possible to assemble tGBS data using ipyrad? I am happy to experiment if this is still in development.

**Comment by isaacovercast** [comment]
Yeah, I've never tried it. It kind of _looks_ like a hybrid ddrad/gbs approach, so you might try running it as `ddrad` datatype? I have no reason to believe it won't work, just never had this kind of data before. Let me know how it goes...

**Comment by o-william-white** [comment]
Thanks Isaac, I will give the ddrad datatype a go and let you know how I get on

**Comment by isaacovercast** [comment]
This rainy day will never come. Nobody uses this protocol anyway.
