### ISSUE TITLE
split vsearch dereplication on huge files; it's a memory hog

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#236]
Seems like a super easy fix for this would be to chunk up a giant file and de-replicate each chunk and then re-join. I'm pretty sure vsearch is written to accommodate this by keeping track of the `nsize` and summing it in subsequent derep steps. I forget how we parallelize during this step, but that's worth looking into as well. I've had this step crash a laptop before but never a real workstation, but it all depends on how many giant samples are being de'repped at once.

**Comment by isaacovercast** [comment]
stale. how we do it now is fine. vsearch is better these days.
