### ISSUE TITLE
Step 4 - Haploid data crashes on first attempt

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#245]
To reproduce:
* Use the default rad example data
* Use the stock params settings
* Set max_alleles_consens = 1
* `ipyrad -p params.txt -s 1234 -f`
```
  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
array([ 0.00159844]) is not JSON serializable
```
* Now here's the fucked up thing, run this again `ipyrad -p params.txt -s 4`
```
  Step 4: Joint estimation of error rate and heterozygosity
  Applying haploid-based test (infer E with H fixed to 0).
  [####################] 100%  inferring [H, E]      | 0:00:09  
```
Finishes fine. Wtf?!?!?!

**Comment by isaacovercast** [comment]
Reported by @LilyRobertLewis_twitter

**Comment by dereneaton** [comment]
wtf indeed. It seems to arise only if you run `-s 1234` from scratch, but not if you run from any intermediate step, meaning it has something to do with loading a json file. Not sure what exactly. It doesn't occur in the API, only in the CLI. Seems like it should be easy to fix, but I haven't figured it out...

**Comment by isaacovercast** [comment]
This works fine now.
