### ISSUE TITLE
Error: "Exception: empty varcounts array"

### ISSUE THREAD

**Issue by nclowell** [dereneaton/ipyrad#246]
I successfully ran an assembly on a small subset of my samples (10 individuals), and then tried running a nearly identical assembly on all of my samples (143 individuals). Everything appeared to be running fine from comparing each assemblies' stats output files, until none of my samples made it through Step 7 and I got this error:

```
ERROR:ipyrad.core.assembly:IPyradWarningExit: 
    Exception: empty varcounts array. This could be because no samples 
    passed filtering, or it could be because you have overzealous filtering.
    Check the values for `trim_loci` and make sure you are not trimming the
    edge too far
```

I don't think it has to do with the ``trim_loci`` parameter because I have it set to ``0,0,0,0`` in both assemblies, which I think means it's not trimming and therefore not adding any additional filtering. I also can't sort out which parameter could be leading to "overzealous filtering." Other than the parameters of assembly and filepath names, the only parameters that I varied between assembles were param13 (max depth), param17 (filter min trim len), and param21 (min samples locus). Because param21 is used in Step 7, I made a branched assembly and changed param21 to the value I used on my first smaller assembly, and I still go the same error message.

I've attached my params files for the first smaller assembly (params-cragig004.txt) and the second larger assembly (params-cragig009.txt), and also my two population maps (popmap_cragig007.txt and popmap_cragigrun1_test.txt) in case they have anything to do with it. Lastly, I also attached the log for the assembly on all of my samples.

[params-cragig009.txt](https://github.com/dereneaton/ipyrad/files/1069790/params-cragig009.txt)
[params-cragig004.txt](https://github.com/dereneaton/ipyrad/files/1069791/params-cragig004.txt)
[popmap_cragigrun1_test.txt](https://github.com/dereneaton/ipyrad/files/1069794/popmap_cragigrun1_test.txt)
[popmap_cragig007.txt](https://github.com/dereneaton/ipyrad/files/1069795/popmap_cragig007.txt)
[ipyrad_log.txt](https://github.com/dereneaton/ipyrad/files/1069803/ipyrad_log.txt)

Any idea what could be going wrong or what I could test to resolve this issue? I intend to be appropriately zealous in my filtering!

Thanks so much,
Natalie

**Comment by isaacovercast** [comment]
Hi Natalie,
Even though you get this varcounts error during step 7 there should still be a cragig009_outfiles directory created with a file called cragig009_stats.txt. If you look in this file you'll see something like the following (this is an artificial example):
```
## The number of loci caught by each filter.
## ipyrad API location: [assembly].stats_dfs.s7_filters

                            total_filters  applied_order  retained_loci
total_prefiltered_loci                246              0            246
filtered_by_rm_duplicates             242            242              4
filtered_by_max_indels                  0              0              4
filtered_by_max_snps                    0              0              4
filtered_by_max_shared_het              0              0              4
filtered_by_min_sample                246              4              0
filtered_by_max_alleles                12              0              0
total_filtered_loci                     0              0              0
```

If you can attach this file for me that'll help troubleshoot the issue.

**Comment by nclowell** [comment]
Sure thing! Here it is:

[cragig009_stats.txt](https://github.com/dereneaton/ipyrad/files/1072233/cragig009_stats.txt)

Thanks!

**Comment by isaacovercast** [comment]
Well, yeah, there it is. It's filtering on minsamples per locus:

filtered_by_min_sample              94483          68697              0

The params file you sent me had minsamples per locus of 70. try lowering
this value and running it again, try 4 at first just to see what the
results look like.

**Comment by nclowell** [comment]
Thanks for pointing me to this stats file - still getting the hang of ipyrad!

I made a branching assembly where I lowered the min samples to 25, and another branch where I lowered it to 4, and all produced the same error.

Here are those param files, and their output stats files:
[params-cragig010.txt](https://github.com/dereneaton/ipyrad/files/1072452/params-cragig010.txt)
[params-cragig011.txt](https://github.com/dereneaton/ipyrad/files/1072453/params-cragig011.txt)
[cragig010_stats.txt](https://github.com/dereneaton/ipyrad/files/1072454/cragig010_stats.txt)
[cragig011_stats.txt](https://github.com/dereneaton/ipyrad/files/1072456/cragig011_stats.txt)

I'd expect at least a few to make it through when min samples was set to 4, as the assembly includes the ten samples that I originally ran as a test. Thoughts?

**Comment by isaacovercast** [comment]
I see the problem. I didn't notice you were using a population assignment file, but I see what's happening now. The only thing we use pop assignments for at this point is specifying minimum number of samples per locus on a per population basis. The last line of the population assignment file specifies how many samples must contain data at a locus in order for it to be retained. You have this:
```
# pop1:26 pop2:52 pop3:41 pop4:9 pop5:13 pop6:2
```
It looks like here you have each population name and the total number of individuals per pop. ipyrad will interpret this as "only retain loci that are present in all samples" which is why everything is getting filtered. 

If you have this setting in your pops file it overrides parameter 21, so that's why the behavior didn't change. You need to lower the values of each of these pops on the last line of the file. I would remove this line and run it again with a very small value of min_samples_locus, then examine the stats output and this will help inform your decision about how many samples per pop to actually use.

Hope this helps.

**Comment by nclowell** [comment]
Awesome - thanks so much! I'll give it a shot and get back in touch if it's still filtering everything out. 

As a side note, the population assignment file I used on my test assembly also had the number of individuals in each population, so I'm surprised that I didn't see the same error in my test run.
