### ISSUE TITLE
In ipyrad/__init__ pull in version from git?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#25]
The conda package build pulls in codebase associated with the current git tag. I think this is probably a good strategy, to rely on tagging to milestone stable versions. There should be a way to pull in the current git tag inside ipyrad/__init__, I'm assuming, so we don't have to set it by hand.

**Comment by dereneaton** [comment]
Is this possible? I stole most of setup.py from looking at other modules, and it seemed most others just write a string for the version. Tagging would be classy, though. I'm not up to speed on tagging yet, need to read more.

**Comment by isaacovercast** [comment]
This is the quick and dirty way.

           mytag = subprocess.check_output(["git", "describe", "--tags"]).split("-")[0]

There's python libraries for git that does it "right" but it seems stupid to include a library just for this one tiny feature. I think the easy way is better here.

**Comment by dereneaton** [comment]
Cool, seems easy. What do you think our procedure should be for tagging versions? major new features, major bug fixes, minor ones, anything?

**Comment by isaacovercast** [comment]
[This is a better workflow](http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/). I haven't set it up yet, seems just as annoying as how we're doing it, kinda...

**Comment by isaacovercast** [comment]
Fixed. New workflow to add tags:
* Do work
* `git tag -a <newversion>`
* `git push origin <newversion>`
* `python setup.py` <- bumps the version in __init__.py
* `git add ipyrad/__init__.py`
* `git push`

**Comment by isaacovercast** [comment]
Disregard. I updated setup.py to do some `git` magic. The new workflow is:
* Do work
* `git tag -a <newversion>
* `git push origin <newversion>
* `python setup.py`

The new version of setup.py autodetects the current ipyrad/__init__.py version, pulls down from git the current version tag, if they differ setup.py updates __init__.py, and does a git add/commit with a default commit message indicating the updated version number.

**Comment by isaacovercast** [comment]
Not ideal, but best i could do.. turns out to be a tricky problem, lots of race conditions.

**Comment by dereneaton** [comment]
```
I got an error when running setup.py. Should there be an argument to it? Also, do we have to worry that running setup.py will interfere with our pip or conda installation?

deren@tinus:~/Documents/ipyrad$ python setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

```

**Comment by dereneaton** [comment]
Or did you mean that I should run `pip install -e .` ?

**Comment by dereneaton** [comment]
I pushed changes to master after tagging 0.1.5 but the tag doesn't seem to have worked. Must have screwed something up...

**Comment by dereneaton** [comment]
nvm

**Comment by dereneaton** [comment]
I'm satisfied with this if you want to close it.

**Comment by isaacovercast** [comment]
ipyrad_update_version.py now holds the code for updating the version, really it's just a wrapper script around a couple commands so it's pretty simple. Pulled all the git code out of setup.py and i feel much better now.
