### ISSUE TITLE
Step 7 - [assembly.py]	ERROR 	'R94-16_R1_clean.fq.gz'

### ISSUE THREAD

**Issue by lili426** [dereneaton/ipyrad#250]
When I finished the first six steps , I can't run step 7. It reported that " [assembly.py]	ERROR 	'R94-13_R1_clean.fq.gz' ”. After I deleted the sample R94-13_R1_clean.fq.gz and R94-13_R2_clean.fq.gz , It reported another one " [assembly.py]	ERROR 	'R94-16_R1_clean.fq.gz' " .

**Comment by dereneaton** [comment]
This looks like it is a problem with the sample names perhaps. Is there an apostrophe in the filename? Usually ipyrad will remove "_R1_" part of the names when they are entered correctly. Did you enter a paired datatype as the argument to the 'datatype' parameter?

**Comment by isaacovercast** [comment]
Closing due to oldness of issue and lack of response. If this is still an issue you can re-open the ticket.
