### ISSUE TITLE
All API analysis tools work but BPP

### ISSUE THREAD

**Issue by bioballs** [dereneaton/ipyrad#251]
I am trying the analysis tools from the ipyrad API analysis tools section and all
work but BPP. I can't get the BPP tool working.

After/during that step nothing is happening:

b.run(
    nreps=2, 
    ipyclient=ipyclient, 
    seed=12345, 
    randomize_order=True,
    )

CPU Usage will rise for 2 seconds but will fall back to 0% immediately.

**Comment by dereneaton** [comment]
Thanks. I think I know the problem. Will push a fix very soon.

**Comment by dereneaton** [comment]
Ok, pretty sure I found the problem. It should now be fixed in v.0.7.2.
