### ISSUE TITLE
conda building old releases

### ISSUE THREAD

**Issue by andypohl** [dereneaton/ipyrad#259]
Miniconda building on old releases is broken due to `conda.recipe/ipyrad/meta.yml` citing the Github repository instead of the local source path.  In general I had problems doing e.g.:

```
$ git clone https://github.com/dereneaton/ipyrad.git
$ cd ipyrad/conda.recipe
$ git checkout 0.6.0
$ conda build .
```

What ends up happening is conda will clone ipyrad and use a recent version, instead of what I just checked out locally.

The git URL is the most glaring problem but other errors I got include:
  * `meta.yml` files having a build section competing with a `build.sh`
  * `cutadapt` was missing a `requirements.txt`.

My goal was to make a version-invariant `Dockerfile` that I'd merge into an old release on a new branch.  I'd tag it something like "with-docker_0.6.0" then merge/tag many times, up to the current version.  E.g.:

```
FROM continuumio/miniconda 
RUN apt-get update && apt-get install build-essential
COPY * /tmp
RUN conda update -y conda \
    && conda install -y conda-build \
    && conda build /tmp/conda.recipe \
    && conda install --use-local ipyrad 
```

Instead I'll probably add the version to the Dockerfile I merge into each release like:

```
FROM continuumio/miniconda 
RUN conda update -y conda && conda install -c ipyrad ipyrad=0.6.0
```

which isn't as nice but I think will work.  I don't think it's good to add much to the past.  Maybe `conda build` is more temperamental than it used to be.  Going forward though, you might want to change some of the recipe.

**Comment by dereneaton** [comment]
Hi @andypohl, 

Thanks for the tips! I'm perpetually trying to gain a better understanding of conda. Our recipe is definitely not perfect, and I don't think we've done much testing for installing older versions, or using docker containers. But we'd love to incorporate your changes, or merge a pull request. @isaacovercast and I will take another look at it as well.

There was a recent upgrade to conda-build that changed a lot of things, which we ran into with a bunch of big problems about a month ago. The use of 'build.sh' was one source of confusion for us, I remember.

**Comment by andypohl** [comment]
I don't know that "conda build" working on old versions matters much.  Maybe the old version that was included in a publication might take priority. I can help with making a Dockerfile, but ideally a Docker image would be built without Miniconda.  You can close this issue if you want, or keep it open if you want a reminder.

**Comment by dereneaton** [comment]
Hi @andypohl, 

I'm not sure why it would be non ideal to build a docker image with conda in it. I thought that was a common usage for docker. 

For example, that is what is done in this docker container https://hub.docker.com/r/lipcomputing/ipyrad/~/dockerfile/ which works just fine. 

The dockerfile would only need to be changed slightly if you wanted to install a different version, or, you can revert from the installed version to an older one super easily once you're in the docker container by using conda. 

I'll go ahead and close this for now, because I think we're happy with how the recipe works. If there was a good reason to avoid using conda, however, then you could use `pip install .` in the git repo as well, and that should work.

Cheers,

**Comment by andypohl** [comment]
Be careful with the community-built Docker images.  I don't want to pick on the person that built that image much, because he went to the effort of making it an automated build where the Dockerfile is provided, and honest efforts to help the community should be thanked.  But it's a pretty amateur attempt.

- It has too many layers.  The `apt-get clean` line does nothing because cleaning up that top layer won't clean up the lower layers.  Which is likely why there are multiple `apt-get update -y` lines, too.  In general layers should be separated out in a way such that they are maximally reused among other images.  That's why buildpack-deps is popular.  It sits at the root of a lot of software stacks.  For your case, you probably want 2-4 installation layers: linux core libraries, dependency applications, Python libraries, and finally ipyrad. 
- The main awesome thing about Miniconda is that as a non-root user, you finally have a package manager that extends beyond the reach of pip.  yum and apt-get, the main linux ones, essentially disallow this.  The Docker image in that case doesn't take the proper steps to make it a systemwide installation of Miniconda.  There are misc conda config files in the /root directory, because that's the home directory for the root user.  The consequence is that containers run through a non-root UID will fail and that's not good.  If Miniconda is really the best way, I think deriving the image from [Continuum's own set of Docker images](https://hub.docker.com/u/continuumio/) is better.  Their Miniconda installation is properly systemwide in the image.  Whenever possible, leverage professionally-built Docker images from a large open source project or a company.

The people I help use ipyrad are using it non-interactively, so I know they don't use jupyter.  Docker images should be as small as possible.  Something like jupyter you might want to be optional to a Docker image.  Additionally, you might want to derive a jupyter image off one of the official jupyter images.  Because jupyter is such a heavyweight install, it could be nice if an ipyrad-jupyter image shared layers with that beast to cut down on download and local disk use.
