### ISSUE TITLE
Logger acting non-deterministically

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#26]
In branch refseq, in the call to mapreads() every so often, maybe once every three times, when you call it python crashes and reports:

            ipyparallel.error.CompositeError: one or more exceptions from call to method: mapreads
            [8:apply]: NameError: global name 'LOGGER' is not defined

I'm staring at the code and can't figure out how what i'm doing in refmap.py is any different from the logger calls in demultiplex. I'll fix it, i'm just making this tic to remind myself to do it.

**Comment by isaacovercast** [comment]
fml. It looks like multiple instances of ipcluster were running? I cycled ipcluster and closed all my open ipyrad notebooks and this "bug" disappeared.

**Comment by dereneaton** [comment]
Dang. Yeah, I've been trying to beef up Error handling more to make sure abandoned ipcluster instances are killed. I've run into similar problems before. Definitely something we want to avoid.
