### ISSUE TITLE
Error in step 7 while building vcf file

### ISSUE THREAD

**Issue by ghost** [dereneaton/ipyrad#261]
-------------------------------------------------------------
  ipyrad [v.0.7.10]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  loading Assembly: LygusMin4
  from saved path: ~/ipyrad/Miles/LygusMin4.json
  establishing parallel connection:
  host compute node: [8 cores] on COSQP04917YDNR.net.ucf.edu

I've ran my dataset before the newest updates and it worked just fine, but now I am having the following error.  

Step 7: Filter and write output files for 23 Samples
  [####################] 100%  filtering loci        | 0:00:56  
  [####################] 100%  building loci/stats   | 0:00:36  
  [####################] 100%  building alleles      | 0:00:38  
  [##################  ]  93%  building vcf file     | 0:00:47  
  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
ValueError(could not broadcast input array from shape (2) into shape (1))
ValueError(could not broadcast input array from shape (2) into shape (1))

**Comment by isaacovercast** [comment]
You'll need to rerun steps 5 and 6 if you updated from 0.6.27 -> 0.7, we changed some things in some of the intermediate files that are generated that slightly broke backwards compatibility. Try that and let me know how it goes.

**Comment by AfterDream** [comment]
I have the same ValueError, and my version is 0.7.27. and I had reruned  the steps 4-5-6-7, but the same error occurred

**Comment by isaacovercast** [comment]
stale. plus i fixed this value error in 0.7.30
