### ISSUE TITLE
VCF output error

### ISSUE THREAD

**Issue by markb729** [dereneaton/ipyrad#262]
In ipyrad version 0.7.8 on GBS data, I found an issue regarding iPyrad's adherence to VCF specifications. Not sure what is causing it, but it is an allele mismatch, specifically the allele ID is [sometimes] larger than the number of alleles.

For example, locus_92 111 . A T,C 13 PASS NS=20;DP=118 GT:DP:CATG ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0./.:0:0,0,0,0 ./.:0:0,0,0,0 1/0:14:1,8,5,0 **3/3:1:0,0,0,1** 1/0:7:0,3,3,1 ./.:0:0,0,0,0 ./.:6:0,2,4,0 0/0:1:0,1,0,0 2/2:1:1,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 1/0:9:0,8,0,1 ./.:0:0,0,0,0 1/1:1:0,0,1,0 ./.:0:0,0,0,0./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:4:0,2,2,0 ./.:0:0,0,0,0 1/0:5:3,0,0,2 ./.:4:1,0,0,3 0/0:1:1,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:1:1,0,0,0 1/0:3:3,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0 ./.:0:0,0,0,0./.:0:0,0,0,0 ./.:0:0,0,0,0 1/0:11:0,11,0,0 1/0:12:0,5,7,0 ./.:6:0,5,1,0 ./.:0:0,0,0,0 1/0:7:0,1,6,0 1/0:22:2,10,10,0 ./.:2:2,0,0,0

Note the presence of **3/3:1:0,0,0,1** in this pasted sample string. This is definitely not possible for this ALT. Could you take a look into this?

**Comment by dereneaton** [comment]
This is now fixed, not sure how we missed it before. There was simply too short of a character string dtype to store all three alternative alleles if present when converting to strings. Easy fix. Thanks.
