### ISSUE TITLE
Unlinked Loci Nexus file for SplitsTree

### ISSUE THREAD

**Issue by bioballs** [dereneaton/ipyrad#266]
Is it possible to produce a nexus file with unlinked loci for SplitsTree?

**Comment by isaacovercast** [comment]
It's pretty normal for RAD-seq datasets to assume all loci are unlinked. SplitsTree will happily import the nexus file ipyrad writes out.

This is more of a question than an issue, so i'm closing this ticket, but if you want to chat more about output formats you can jump on our gitter channel:

https://gitter.im/dereneaton/ipyrad
