### ISSUE TITLE
Implement "really quiet" mode

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#269]
We have a quiet mode, but it's still pretty loud, esp if you're running on a cluster and writing stdout to a file (then it's _really_ loud, the file can get enormous), can be super annoying. It would be simple enough to implement a _really quiet_ flag, or just i mean update the behavior of the current flag to basically route the progressbar to /dev/null.

**Comment by dereneaton** [comment]
+1

**Comment by isaacovercast** [comment]
Fixed 1113775

**Comment by isaacovercast** [comment]
Only took 3.5 yrs ;p
