### ISSUE TITLE
Step 7 error regarding population_file

### ISSUE THREAD

**Issue by sabasu9** [dereneaton/ipyrad#271]
Hello,

I'm having an issue with assigning population values to the dataset. I assembled a population file that followed the tutorial very closely. I have attached the file: 
[pop_file.txt](https://github.com/dereneaton/ipyrad/files/1326713/pop_file.txt)

I received this error during step 7:

ERROR:ipyrad.assemble.write_outfiles:error in filter_stacks on chunk 0: IndexError(index 165 is out of bounds for axis 1 with size 161)
ERROR:ipyrad.core.assembly:IPyradWarningExit: error in filter_stacks on chunk 0: IndexError(index 165 is out of bounds for axis 1 with size 161)

I do have 161 individuals and all are labeled under the pop_file, followed by min_locus_sample values.
I only get this error when including the population file. I've even tried reducing the min_locus_sample values to 1 a population to no avail.

Any assistance would be greatly appreciated.
Thanks for your time.
Saptarsi

**Comment by isaacovercast** [comment]
this has been fixed in the 0.9 branch. If you still have problems with it please reopen the ticket.
