### ISSUE TITLE
tetrad running problem

### ISSUE THREAD

**Issue by tangerzhang** [dereneaton/ipyrad#277]
I am running tetrad, but have an error reported:

 tetrad -s out.php -n noambigs -r 0

tetrad instance: noambigs
loading seq array [66 taxa x 7419 bp]
inferring 720720 quartet tree sets
establishing parallel connection:
host compute node: [24 cores] on admin1

Unknown exception encountered: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

Is there anything I can do to solve this problem?
Thanks!

**Comment by isaacovercast** [comment]
Stale issue. If this is still a problem please try the latest version and update with a comment.
