### ISSUE TITLE
Support for pe multiplex barcode protocol w/ barcode 2 in the identifier line

### ISSUE THREAD

**Issue by cb1579** [dereneaton/ipyrad#285]
Hi, I'm having trouble demultiplexing my reads. I have paired-end ddRADSeq data, and step 1 runs to completion but fails to assign any reads to individuals.
 
Barcodes file: [doris_barcodes.txt](https://github.com/dereneaton/ipyrad/files/1573041/doris_barcodes.txt)
 
params file: [params-Doris.txt](https://github.com/dereneaton/ipyrad/files/1573043/params-Doris.txt)

example of reads: 
@700819F:525:HT235BCXX:2:1101:1139:2144 1:N:0:ATCACGAT
CGAATTGCAGATTTTTTCTGAATAAAGCAGTGCAATAAAATTCCCCGCAAAAACACTTNANNNGNNNNNNNNNNNNNNNNNNNNANNNNNNGNTAATAAA
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#<###.####################.######<#.<<GGGI
@700819F:525:HT235BCXX:2:1101:1212:2172 1:N:0:ATCACGAT
AAGGATGCAGGGCATCTCCCTCAGGCTGCGCTCTATCGAAGTCATCCCAGAATTAGATTCCGACCACAGACCAGTCTTAGTCAAACTAGGACCCGAGTGT
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIIIGIIIIIIGGIIIGIIIIIIIIIIIIIGGIGIGIIIGIGI
@700819F:525:HT235BCXX:2:1101:1110:2173 1:N:0:ATCACGAT
GGTTGTGCAGAAAGAGTTGCTGATAAACTTAGCCATGCAGAACAGAATTATGAGTTAGAAGTATGTATATATATACCAATCACTATATCAACCCATTACC
+
<G.G<GGIIIG.GA.GAGAAGG<AA<A<.<<<GA<.<<.G<.G<<A<GGAA....<G.G..<<.GA..<A.<GG<<<.<..<<.GG.A..G..<<<.<<G
@700819F:525:HT235BCXX:2:1101:1146:2206 1:N:0:ATCACGAT
CATATTGCAGATTTTTTCTGAATAAAGCAGTGCAATAAAATTCCCCGCAAAAACACTTTATTTGGCACAAAAGTACACATTTTCACAAAGGGAAAATAAA
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIGGIIIIIIIIAGIIIIIII
@700819F:525:HT235BCXX:2:1101:1134:2242 1:N:0:ATCACGAT
AGCTATGCAGCAGCACATAAGGCGCGTCCACACGCGCAAGTGTACCGGTCGCCTGCACTCGTGCGGCGCGTGTGGTGACAGTTTCAGTACGCAACGTGCT
+
GGGGGIIIIIIIIAG.<<<G.<<A.<AGA...<AAGA.G.<<<<<GG<<<..<.<....<.<GA.AAA....<<AGIAA<<<<GA<GGA<<A..<...<<
@700819F:525:HT235BCXX:2:1101:1463:2134 1:N:0:ATCACGAN
AACCATGCAGCTCCTGGTCCCTAGTTGCCTAAGCTGGGCCTCCTCTGGGCAAACTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
GGGGGIIIIIGGIGGGGGGGGGGGIIGGGGIGGIIGGIGGAGGAGGGGAGGGGIG#############################################

Thank you for the assistance.

**Comment by isaacovercast** [comment]
First of all, those barcodes look unusually long `BC_5120 ATCACGATGGTTG`. You can see what's happening if you look at an example sequence:

```
GGTTGTGCAGAAAGAGTTGCTGATAAACTTAGCCATGCAGAACAGAATTATGAGTTAGAAGTATGTATATATATACCAATCACTATATCAACCCATTACC
```

According to your params file `TGCAG` is the cutsite, which you can see beginning at the sixth character in the above sequence. This is the normal place for it, and the "normal" length of a barcode is ~5 bases, which you can see above should be GGTTG, but in your barcodes file the barcode sequences are much longer than this. Are they multiplex barcoded perhaps? Is there a barcode sequence on R2? Not sure what's going on here beyond this.

**Comment by cb1579** [comment]
My apologies, I forgot I edited the barcodes file to troubleshoot. Each individual has two barcodes separated by an 'AT', as such:

BC_5862  ATCACG-AACCA where '-' is where the 'AT' is present

R2 reads contain the same barcodes as R1.

thanks again.

**Comment by isaacovercast** [comment]
Can you paste a few example R2 sequences? I don't see the first barcode in the R1 sequence, so that explains why ipyrad is having trouble demux'ing.

**Comment by cb1579** [comment]
@700819F:525:HT235BCXX:2:1101:1139:2144 1:N:0:ATCACGAT
CGAATTGCAGATTTTTTCTGAATAAAGCAGTGCAATAAAATTCCCCGCAAAAACACTTNANNNGNNNNNNNNNNNNNNNNNNNNANNNNNNGNTAATAAA
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII#<###.####################.######<#.<<GGGI
@700819F:525:HT235BCXX:2:1101:1212:2172 1:N:0:ATCACGAT
AAGGATGCAGGGCATCTCCCTCAGGCTGCGCTCTATCGAAGTCATCCCAGAATTAGATTCCGACCACAGACCAGTCTTAGTCAAACTAGGACCCGAGTGT
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIIIGIIIIIIGGIIIGIIIIIIIIIIIIIGGIGIGIIIGIGI
@700819F:525:HT235BCXX:2:1101:1110:2173 1:N:0:ATCACGAT
GGTTGTGCAGAAAGAGTTGCTGATAAACTTAGCCATGCAGAACAGAATTATGAGTTAGAAGTATGTATATATATACCAATCACTATATCAACCCATTACC
+
<G.G<GGIIIG.GA.GAGAAGG<AA<A<.<<<GA<.<<.G<.G<<A<GGAA....<G.G..<<.GA..<A.<GG<<<.<..<<.GG.A..G..<<<.<<G
@700819F:525:HT235BCXX:2:1101:1146:2206 1:N:0:ATCACGAT
CATATTGCAGATTTTTTCTGAATAAAGCAGTGCAATAAAATTCCCCGCAAAAACACTTTATTTGGCACAAAAGTACACATTTTCACAAAGGGAAAATAAA
+

It looks as though the first barcode is present in the header but not the actual read. These aren't specific to individuals, but in combination with the barcode present on the read, they can be assigned to an individual. 

This is the header: @700819F:525:HT235BCXX:2:1101:1146:2206 1:N:0:**ATCACG**AT 
 
and the read begins as such: GGTTG...

Can ipyrad resolve this, or should I resort to another demultiplexing tool and continue the pipeline using ipyrad?

**Comment by isaacovercast** [comment]
Hm, what kind of protocol did you follow for constructing the library? I've never seen anything like this, so ipyrad isn't currently rigged to deal with this kind of data. We do multiplexed barcodes, but only in the 3RAD fashion (1 barcode on R1 and 1 barcode on R2). Seems like it would be pretty straightforward to implement this, but I can't make any promises about when it'd get done (a little busy at the moment). Do you have a reference for the library prep protocol, so i can check it out?

**Comment by cb1579** [comment]
Here is the protocol. Unfortunately, I did not construct the libraries, so this is all the info I have.

[ddRADprotocol-updated_.docx](https://github.com/dereneaton/ipyrad/files/1573264/ddRADprotocol-updated_.docx)

Thank you for the help. After a quick search, it looks like there are scripts available to handle this type of library construction.

**Comment by isaacovercast** [comment]
Cool, thanks. It looks like standard Peterson et al ddRAD, but they include
an index during PCR for multiplexed barcoding. Makes perfect sense. I'll
try to get around to it, but hopefully you have luck with the other scripts.

**Comment by isaacovercast** [comment]
It's not perfect but the demux on i7 in API mode does just this. This is a pretty uncommon datatype, so I think we can call this good enough:

https://ipyrad.readthedocs.io/en/latest/API-assembly/cookbook-demultiplex-i7.html
