### ISSUE TITLE
step6 

### ISSUE THREAD

**Issue by zhengboying** [dereneaton/ipyrad#286]
IndexError(too many indices for array）
I don't know the meaning of the error.  becaues my dataset is a multispecies, and they have large distance with each other. I don't know it wether fits these data

**Comment by isaacovercast** [comment]
Can you post more information about everything? Number of samples, length of reads, params file, also please post the last several lines of the ipyrad_log.txt.

**Comment by isaacovercast** [comment]
I can help but I need more information. I'm closing this ticket, but if you post more information we can re-open it.
