### ISSUE TITLE
Refseq mapping - Handle assembly branching more intelligently

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#29]
or at all... ;p

Currently refseq mapping always writes to the same directory <workdir>/<name>_refmapping. This could be a problem if you want to try different values for sequence similarity. Maybe handle refmapping directories and branching the same way it's handled for clustering.

**Comment by dereneaton** [comment]
I think that if we name it `[assembly.name]_refmapping/ ` and enforce that there can't be duplicate assembly names then we should be fine. If users create a branch they need to name it something new. We just need to make sure we enforce that so they get a warning before any data is overwritten.

**Comment by isaacovercast** [comment]
This is true and fixed.
