### ISSUE TITLE
Refmap - 'reference' assembly is not throwing out denovo loci

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#290]
wtf?!?! reads that don't map to the reference are still getting denovo assembled and included in the output. annoying.

**Comment by saraema-silva** [comment]
I have this problem. I performed the "reference" method for assembling a RAD seq dataset but reads that don't map to the reference are denovo assembled and included in the outfiles. Can I simply delete these lines beginning whith "locus_..." from my vcf file? Is this correct?

**Comment by isaacovercast** [comment]
This is fixed in v.0.9
