### ISSUE TITLE
Step 3 - IndexError during 3Rad declone

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#291]
Reported in #215, but moving to a new issue because this is a different problem.

**Comment by isaacovercast** [comment]
@tuckerwc91

**Comment by isaacovercast** [comment]
Can you give me a sense of how long this is running before it crashes? Can you open one of the files in the _edits directory and copy the first 8 lines here?

**Comment by BurnsMercedes** [comment]
Hi Isaac (copied from #215),

I'm running into this same issue as Tuckerwc91. I'm working with a 3Rad dataset, denovo assembly, on iPyrad v. 0.7.23. Here's what it looks like when I run debug on Step 3:
Step 1: Demultiplexing fastq data to Samples
Skipping: 8 Samples already found in Assembly 2018NextSeqi7DemuxP3_c1.
(can overwrite with force argument)

Step 2: Filtering reads
Skipping: All 8 selected Samples already edited.
(can overwrite with force argument)

Step 3: Clustering/Mapping reads
[ ] 0% dereplicating | 0:00:00 INFO:ipyrad.assemble.cluster_within:inside trackjobs of derep_concat_split
[####################] 100% dereplicating | 0:00:24
ERROR:ipyrad.core.assembly:IPyradError( Caught error while decloning 3rad data - list index out of range)

Encountered an unexpected error (see ./ipyrad_log.txt)
Error message is below -------------------------------
IPyradError( Caught error while decloning 3rad data - list index out of range)
INFO:ipyrad.core.assembly:interrupted engine 1 w/ SIGINT to 43876
INFO:ipyrad.core.assembly:interrupted engine 3 w/ SIGINT to 43878
INFO:ipyrad.core.assembly:interrupted engine 5 w/ SIGINT to 43880
INFO:ipyrad.core.assembly:interrupted engine 7 w/ SIGINT to 43886
INFO:ipyrad.core.assembly: shutting down engines
INFO:ipyrad.core.assembly: finished shutdown
INFO:ipyrad:debugging turned off
Here's my log file: 
[ipyrad_log.txt](https://github.com/dereneaton/ipyrad/files/2287104/ipyrad_log.txt)

And here's the first 8 lines of one of the merged files from the _edits directory:
@NS500599:190:HY7FHBGX5:2:11106:19303:11732 1:N:0:TTGGACGT_m1
ATCGGACTCCGACATTTGTTATCCTGTACAACCCCAACTAAAAACAAAGGTCAAATTTCACTAAGGGGTTCTCTGTGAATT
+
EEEEEAEEEEEEEEJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJA/EEEEEEEEEEE
@NS500599:190:HY7FHBGX5:2:11112:14993:1983 1:N:0:TTGGACGT_m1
ATCGGCAAGACATTTAGCATTTCAGGCAATTAGTCGATTTCGTCCAAACAGATTGAAAATAATAAATAACCCGTCCAGACATTCAACATTTCTGCAAATTAGTCGAATT
+
EEEEEEEEEAEEEEEEEEEEEEEEEEEAAEEAEEEEEEEEA/JJJJJJJJJJJJJJJJJJJJJJJJJJEA/EE/EEEEEEEEEEE/EEEEEEAEEEEEEAAEEAEEEEE

Any thoughts?

**Comment by BurnsMercedes** [comment]
Also, as far as the length of time it runs: the dereplicating part of step 3 runs to 100% regardless of the number of samples I'm working on-- usually takes 30 seconds to a couple of minutes. It happens fast. I should also mention that I didn't have this issue with my (much smaller) test data from a PE MiSeq run of the exact same libraries

**Comment by isaacovercast** [comment]
Hi Mercedes,
Well, I can see the problem here, the 3RAD data that I used as the target for development looks somewhat different from yours. A typical read from the data I used looks like this:

@NS500216:300:HLMYTBGXX:1:11101:11046:1788 1:N:0:ATGGCGAA+CTTGTTAT_m1
CTAGATCGGAGGTGCTTGATGAAATCTGAGGTCCTAGATGAAATCCGAGGATTTGGTGGGGGACCTCTCCAAATCCGAGGTCCTAAATGAAAACCGAGGTCCTAGATGAATT

Here the i5 adapter sequence i'm using for decloning is included in the sequence ID (ATGGCGAA+CTTGTTAT). In this case the sequence after the '+' is the i5. This part of step 3 is purely for decloning 3rad reads. Since your i5 adapters aren't in the sequence ID the easiest thing to do will be to just skip the 3rad decloning all together. You can easily do this by setting your 'datatype' parameter to 'pairddrad' and running step 3. This should be just fine, as there is no 3rad specific code downstream of step 3 besides the decloning.

If you know the i5 adapters are in the sequence somewhere and you _really_ want the decloning to happen we'll have to think about how to do this, but for now i think setting the datatype to pairddrad and moving forward is totally the way to go. Give that a shot and let me know how it goes.
