### ISSUE TITLE
h5py error 

### ISSUE THREAD

**Issue by insectnate** [dereneaton/ipyrad#293]
Trying to run ipyrad for the first time but i get this h5py error at the init step.
Command run
 ipyrad -n ipyrad_params -s 234567 -c 8

error message
/anaconda3/lib/python2.7/site-packages/h5py/__init__.py:36:
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

  New file 'params-ipyrad_params.txt' created in /media/ac48d0c19d800ee2/ddRADseq_test

This new empty param file is exactly the same as my original just with my few params taken out.

Any help greatly appreciated.

**Comment by isaacovercast** [comment]
This is a warning from h5py, not an error. It's unfortunately happening for everyone and it will be fixed in a future version of h5py, hopefully soon. You can disable python warnings, but we prefer not to do this, normally. You can safely ignore this warning, everything should be fine.

**Comment by isaacovercast** [comment]
If everything is not fine let me know and we'll reopen this issue.

**Comment by insectnate** [comment]
I'm confused as nothing else happens other than the new param file being created. Isn't the above command intended to take demultiplexed files and perform steps 2-7?

**Comment by isaacovercast** [comment]
`ipyrad -n ipyrad_params -s 234567 -c 8`

The `-n` specifies to create a new params file. If there's a -n in the command line it supersedes all other flags. This is what you want:

`ipyrad -p <yourparams.txt> -s 1234567 -c 8`

Also, if you demux'd files outside of ipyrad you still need to include step 1 so it can go out and examine the files it's importing.

If you have more questions why don't you pop over to the gitter channel, it's for chatting, and it's a little more straightforward for realtime help than commenting on issues:

https://gitter.im/dereneaton/ipyrad

**Comment by insectnate** [comment]
Ok thanks!
