### ISSUE TITLE
ipyrad issue:  ERROR   ValueError(need more than 0 values to unpack)

### ISSUE THREAD

**Issue by carlyraea** [dereneaton/ipyrad#295]
Hello- I'm getting this error over and over again with different sets of data and different parameters. It seems to fail on step 3. Can anyone help me with this? I assume it's a divide by zero type of error but I have no idea how to find the incorrect piece.

Thanks

**Comment by isaacovercast** [comment]
What version are you running? How far does it get into step 3? Can you run
it with the -d flag and post the last 20 like of the ipyrad_log.txt file?
It's not a math error.
-isaac

**Comment by carlyraea** [comment]
I'll try right now. It usually runs for 6-7 minutes before completing. What modifier should I put after the -d flag? It's version 0.7.19.

**Comment by carlyraea** [comment]
2018-05-23 17:19:39,559 	pid=565 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladia_aggregata_chunk_5.ali
2018-05-23 17:19:39,562 	pid=552 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_coniocraea_chunk_1.ali
2018-05-23 17:19:39,565 	pid=481 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_subtenuis_chunk_3.ali
2018-05-23 17:19:39,567 	pid=531 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladia_aggregata_chunk_7.ali
2018-05-23 17:19:39,567 	pid=536 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_apodocarpa2_chunk_1.ali
2018-05-23 17:19:39,567 	pid=484 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_apodocarpa_chunk_0.ali
2018-05-23 17:19:39,569 	pid=547 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_cervicornis_verticillata_chunk_4.ali
2018-05-23 17:19:39,569 	pid=596 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Stereocaulon_sasakii_chunk_9.ali
2018-05-23 17:19:39,569 	pid=500 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Lepraria_sp_chunk_9.ali
2018-05-23 17:19:39,572 	pid=524 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_piedmontii_chunk_8.ali
2018-05-23 17:19:39,574 	pid=489 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_cenotea3_chunk_4.ali
2018-05-23 17:19:39,577 	pid=653 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_cenotea2_chunk_4.ali
2018-05-23 17:19:39,579 	pid=619 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_appalachensis_chunk_9.ali
2018-05-23 17:19:39,579 	pid=639 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Stereocaulon_pileatum_chunk_5.ali
2018-05-23 17:19:39,580 	pid=584 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Stereocaulon_rivulorum_chunk_0.ali
2018-05-23 17:19:39,581 	pid=609 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_fimbriata_chunk_7.ali
2018-05-23 17:19:39,581 	pid=543 	[cluster_within.py]	DEBUG 	skipping empty chunk - /gpfs/summit/scratch/caan8813/ipyrad_cladonia_2/ipyrad_assembly_cladonia_2-tmpalign/Cladonia_amaurocraea_chunk_0.ali
2018-05-23 17:19:41,630 	pid=455 	[assembly.py]	INFO 	  shutting down engines
2018-05-23 17:19:41,675 	pid=455 	[assembly.py]	INFO 	  finished shutdown
2018-05-23 17:19:41,677 	pid=455 	[__init__.py]	INFO 	debugging turned off

**Comment by isaacovercast** [comment]
Looks like there are no clusters being found. Does step 2 finish ok? Can you paste the output of `ipyrad -p <your params file> -r`? Also, can you attache the s2_rawedit_stats.txt file from the _edits directory in your working directory?

**Comment by carlyraea** [comment]
Hello,

Sorry for the extremely delayed reply, I was in the field.

Step 2 finishes but step 3 fails with :

  Encountered an unexpected error (see ./ipyrad_log.txt)

  Error message is below -------------------------------

ValueError(need more than 0 values to unpack)



Here's the return from the edits file (a piece):


                                   reads_raw  trim_adapter_bp_read1
trim_quality_bp_read1  reads_filtered_by_Ns  reads_filtered_by_minlen
reads_passed_filter

Cladia_aggregata                           1                      0
              0                     0                         0
        1

Cladonia_amaurocraea                       8                      0
              0                     0                         0
        8

Cladonia_apodocarpa                       33                      0
              0                     0                         0
      33

Cladonia_apodocarpa2                      73                      0
              0                     0                         0
      73

Cladonia_appalachensis                   222                      0
              0                     0                         0
      222

Cladonia_cenotea                         568                      0
              0                     0                         5
      563

Cladonia_cenotea2                        391                      0
              0                     0                         0
      391

Cladonia_cenotea3                        490                      0
              0                     0                         3
      487

Cladonia_cervicornis_verticillata        876                      0
              0                     0                         2
      874

Cladonia_chlorophaea                     129                      0
              0                     0                         1
      128

Cladonia_coniocraea                      624                      0
              0                     0                         0
      624

Cladonia_didyma                          374                      0
              0                     0                         0
      374

Cladonia_didyma2                         205                      0
              0                     0                         0
      205

Cladonia_ecmocyna                        820                      0
              0                     0                         3
      817

Cladonia_ecmocyna2                       414                      0
              0                     0                         3
      411

Cladonia_ecmocyna3                       335                      0
              0                     0                         2
      333

Cladonia_fimbriata                       267                      0
              0                     0                         0
      267

Cladonia_gracilis_elongata2               78                      0
              0                     0                         0
      78

Cladonia_grayi                           638                      0
              0                     0                         2
      636

Cladonia_leporina                        299                      0
              0                     0                         0
      299

After looking at these two things it seems like maybe the adaptors are too
restrictive and that's leaving me with not enough reads to continue...am I
on the right track? Thanks!

Carly

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
Hi Carly,
Yeah, it definitely looks like something went wrong earlier in the process.
It kind of looks more like the demultiplexing failed, in which case I would
recommend doublechecking your barcodes file, and rerunning step one and
inspecting the output. You should have hundreds of thousands or millions of
reads per sample if the demux works properly.

-isaac

**Comment by carlyraea** [comment]
Thanks. I'll give that a try. I tried running it with a parameters file
that has worked in the past, so I think you're right that it's something
wrong with the data instead.

Cheers,
Carly

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by carlyraea** [comment]
Hey again,

I've tried rerunning iPyrad on this data a bunch of different times and
I've still had no luck getting it past step 3. It seems to stall infinitely
on 3 and then just time out, yet I'm still getting the '0 values to unpack'
error popping up a lot. I redid cutadapt and demultiplexing and I don't see
how anything could be wrong with the output. Here's the last lines of the
ipyrad_log.txt file.

2018-06-18 14:05:06,993 pid=135560 [rawedit.py] ERROR error in
run_cutadapt(): IPyradError( error in cutadapt -a TTAAGATCGGAAGAGC
--quality-base 43 -q 20 --minimum-length 35 --max-n 50 --trim-n --output
/gpfs/summit/scratch/caan8813/peltigera3/ipyrad_assembly_cladonia_peltigera_edits/Cladonia_rangiferina.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladonia_rangiferina.demux.fq

 This is cutadapt 1.16 with Python 2.7.14

Command line parameters: -a TTAAGATCGGAAGAGC --quality-base 43 -q 20
--minimum-length 35 --max-n 50 --trim-n --output
/gpfs/summit/scratch/caan8813/peltigera3/ipyrad_assembly_cladonia_peltigera_edits/Cladonia_rangiferina.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladonia_rangiferina.demux.fq

Running on 1 core

Trimming 1 adapter with at most 10.0% errors in single-end mode ...

cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but
found 'HHVTJBGX3:'

)

2018-06-18 14:08:22,566 pid=135560 [assembly.py] ERROR ValueError(need more
than 0 values to unpack)


It also keeps saying that the first lines of fastq files are not starting
with @ but when I check those files, they are. Here's Cladonia_rangiferina:

@NB501447:153:HHVTJBGX3:1:11101:11315:14929 1:N:0:1

CAATTCTAGTCCTGTTGAAAGTATGAAATTTTAGGGGAGTGGCGAAGAAGAAGTTGTCCGTTGTCTCGGTTGTTCGGACGGC

+

AEA/EAEEEAA<EAEE/E/EEEAEAEEEE<EE/E6EEEEEEEEE//E6EEE6EAEEAE<EEEEEAE<EEEEEEEAEE/EEE/

@NB501447:153:HHVTJBGX3:1:11108:1643:18342 1:N:0:1

CGCTACACGCAGGACGCTTTTTCACGTTCTGGTTGGTTGTGGACTGTTGATGCTAAAGGTGAGCCGCTTAAAGCTACCAGTT

+

/EEEEE<E<EEEA<EEAAEEEEEA/EE/EAE/EA<<EEAE/6///EEEEAAEEEEEAEEEE/EEEEEA/EE/EE//AEEEE<

@NB501447:153:HHVTJBGX3:1:11209:3881:10761 1:N:0:1

GACAGATGTATCCATCTGAATGCAATGAAGAAAACCACCATTACCAGCATTAACCGTCAAACTATCAAAATATAACGTTGAC

+

/EEA6EE6/EEEEEEEE/EEEAEAEE/AAA/EEEE/AA</AE/E/EEEEEEEEE<EAAEEEEEEEEEEEEEAEE/EAEEEEE

@NB501447:153:HHVTJBGX3:1:11210:24344:13292 1:N:0:1

CAATTCTGTCCGCCATGAGAAGCATTCCCAACAACTTCTCCAGGTCTGAAAACAACCAAGTGATTCAACCAAACGCTTTACC

+

/<E/EAEEEE<AAA/EAEEAA<EEEA/AEE/EEAE/EEE<EEEA/E6EEEEEEEEEEEE6E/EE//A6AAEE/E<EE/EEEE




And here's the last 100 lines of the slurm output:


cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but
found 'EEEEEEEEEE'

)

ERROR:ipyrad.assemble.rawedit:error in run_cutadapt(): IPyradError( error
in cutadapt -a TTAAGATCGGAAGAGC --quality-base 43 -q 20 --minimum-length 35
--max-n 50 --trim-n --output
/gpfs/summit/scratch/caan8813/macilenta3/ipyrad_assembly_cladonia_macilenta_edits/Cladonia_confusa.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladonia_confusa.demux.fq

 This is cutadapt 1.16 with Python 2.7.14

Command line parameters: -a TTAAGATCGGAAGAGC --quality-base 43 -q 20
--minimum-length 35 --max-n 50 --trim-n --output
/gpfs/summit/scratch/caan8813/macilenta3/ipyrad_assembly_cladonia_macilenta_edits/Cladonia_confusa.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladonia_confusa.demux.fq

Running on 1 core

Trimming 1 adapter with at most 10.0% errors in single-end mode ...

cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but
found '</AEE/E/EA'

)

ERROR:ipyrad.assemble.rawedit:error in run_cutadapt(): IPyradError( error
in cutadapt -a TTAAGATCGGAAGAGC --quality-base 43 -q 20 --minimum-length 35
--max-n 50 --trim-n --output
/gpfs/summit/scratch/caan8813/macilenta3/ipyrad_assembly_cladonia_macilenta_edits/Cladonia_rangiferina.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladonia_rangiferina.demux.fq

 This is cutadapt 1.16 with Python 2.7.14

Command line parameters: -a TTAAGATCGGAAGAGC --quality-base 43 -q 20
--minimum-length 35 --max-n 50 --trim-n --output
/gpfs/summit/scratch/caan8813/macilenta3/ipyrad_assembly_cladonia_macilenta_edits/Cladonia_rangiferina.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladonia_rangiferina.demux.fq

Running on 1 core

Trimming 1 adapter with at most 10.0% errors in single-end mode ...

cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but
found 'HHVTJBGX3:'

)


  found an error in step2; see ipyrad_log.txt

  found an error in step2; see ipyrad_log.txt

  found an error in step2; see ipyrad_log.txt

  found an error in step2; see ipyrad_log.txt

  found an error in step2; see ipyrad_log.txt


  Step 3: Clustering/Mapping reads

  [####################] 100%  indexing reference    | 0:00:00

    Sample not ready for clustering. First run step2 on sample:
Cladia_retipora.demux

    Sample not ready for clustering. First run step2 on sample:
Cladia_aggregata.demux

    Sample not ready for clustering. First run step2 on sample:
Cladonia_subtenuis.demux

    Sample not ready for clustering. First run step2 on sample:
Cladonia_confusa.demux

    Sample not ready for clustering. First run step2 on sample:
Cladonia_rangiferina.demux

    Sample not ready for clustering. First run step2 on sample:
Cladonia_sp5.demux

  [####################] 100%  dereplicating         | 0:00:40

  [####################] 100%  mapping               | 0:04:03

  [####################] 100%  fetch mapped reads    | 0:00:03
ERROR:ipyrad.core.assembly:ValueError(need
more than 0 values to unpack)

ERROR:tornado.general:Uncaught exception, closing connection.

Traceback (most recent call last):

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 414, in _run_callback

    callback(*args, **kwargs)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py",
line 277, in null_wrapper

    return fn(*args, **kwargs)

  File "<decorator-gen-141>", line 2, in _dispatch_reply

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 69, in unpack_message

    return f(self, msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 888, in _dispatch_reply

    handler(msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 817, in _handle_apply_reply

    self.results[msg_id] = self._unwrap_exception(content)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 658, in _unwrap_exception

    eid = self._engines[e_uuid]

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/util.py",
line 79, in __getitem__

    return self._reverse[key]

KeyError: u'2d48e534-7339531d6c96e067aa99e53f'

ERROR:tornado.general:Uncaught exception, closing connection.

Traceback (most recent call last):

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 440, in _handle_events

    self._handle_recv()

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 472, in _handle_recv

    self._run_callback(callback, msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 414, in _run_callback

    callback(*args, **kwargs)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py",
line 277, in null_wrapper

    return fn(*args, **kwargs)

  File "<decorator-gen-141>", line 2, in _dispatch_reply

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 69, in unpack_message

    return f(self, msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 888, in _dispatch_reply

    handler(msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 817, in _handle_apply_reply

    self.results[msg_id] = self._unwrap_exception(content)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 658, in _unwrap_exception

    eid = self._engines[e_uuid]

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/util.py",
line 79, in __getitem__

    return self._reverse[key]

KeyError: u'2d48e534-7339531d6c96e067aa99e53f'

ERROR:tornado.application:Exception in callback None

Traceback (most recent call last):

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/tornado/ioloop.py",
line 888, in start

    handler_func(fd_obj, events)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py",
line 277, in null_wrapper

    return fn(*args, **kwargs)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 440, in _handle_events

    self._handle_recv()

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 472, in _handle_recv

    self._run_callback(callback, msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py",
line 414, in _run_callback

    callback(*args, **kwargs)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py",
line 277, in null_wrapper

    return fn(*args, **kwargs)

  File "<decorator-gen-141>", line 2, in _dispatch_reply

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 69, in unpack_message

    return f(self, msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 888, in _dispatch_reply

    handler(msg)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 817, in _handle_apply_reply

    self.results[msg_id] = self._unwrap_exception(content)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py",
line 658, in _unwrap_exception

    eid = self._engines[e_uuid]

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/ipyparallel/util.py",
line 79, in __getitem__

    return self._reverse[key]

KeyError: u'2d48e534-7339531d6c96e067aa99e53f'

Do any of these errors look familiar to you? I'm getting so frustrated
since this params file and data has already worked for me...I have no idea
what's causing it to fail this time. I'd appreciate any help.


Carly


*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
The problem still looks like it's in step 2, even though it manages not to crash for some of the samples, it seems that its not happy with the format of some of the reads in your demux files. This and the other errors like this are the relevant ones:

```
cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but
found 'HHVTJBGX3:'
```

There must be some reads buried in the .fq files that aren't formatted right and cutadapt isn't handling it very gracefully. If you want to dropbox me one of the samples I can look at it "Cladonia_rangiferina.demux.fq".

All the errors downstream of step 2 are just noise generated by ipyrad trying to recover from the early failure. We should fix step 2 so we know it works, before we move on to step 3.

**Comment by carlyraea** [comment]
Hey again, here's the Cladonia_rangiferina file. I tried running the
program again and removing all the offending files, but it still didn't
work (or at least it timed out at 10 hours which is much longer than it
needed to run successfully last time.)

https://www.dropbox.com/s/adw9el52u90n085/Cladonia_rangiferina.demux.fq?dl=0

Thanks for any help,
Carly

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
Hi Carly,

Yes, this is just as I suspected. The fastq file has malformed reads. Look in the file you sent me and line 1001 looks like this:

```
HHVTJBGX3:1:11210:8859:15771 1:N:0:1
GTATTCACAATAATTATCATGATAGAAATTTTGTAATATATTCATCTTTGAGAATCTTGAGTTTTAGTGGTTTCAAAAAATTAT
+
EEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA
```

You can see that the file is malformed. What doesn't help is that cutadapt reports the error is on line 1, when it clearly isn't. I created an issue on the cutadapt github to let them know the error is reporting wrong (https://github.com/marcelm/cutadapt/issues/312). For now you'll have to go through and make sure all your fastq files that are crashing are actually formatted correctly. I have no idea how these files could have gotten into this condition.

**Comment by carlyraea** [comment]
Ah I se....do you have a fast method of finding the problem, or were you
just skimming through looking? Thanks for this.

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
```
grep ":" <my_fastq_file>.fq | grep -vn "@"
6:K00337:98:HLJJTBBXX:2:1107:30107:31576 1:N:0:2
9:K00337:98:HLJJTBBXX:2:1107:16944:31593 1:N:0:2
10:K00337:98:HLJJTBBXX:2:1107:23460:31593 1:N:0:2
```
The first number is the line number with the bad sequence name.

**Comment by carlyraea** [comment]
Perfect, thank you. I'm going to update and rerun cutadapt and then just
search for the problem files. Cheers!

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by carlyraea** [comment]
Hey again, even with fixing and/or removing the malformed files, I get the same error. It must be coming from somewhere else. This is from the ipyrad log file:

  ipyrad [v.0.7.19]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Begin run: 2018-06-22 10:12
  Using args {'preview': False, 'force': False, 'threads': 2, 'results': False, 'quiet': False, 'merge': None, 'ipcluster': None, 'cores': 0, 'params': '/projects/caan8813/data/params_cladonia_peltigera2.txt', 'branch': None, 'steps': '1234567', 'debug': False, 'new': None, 'MPI': False}
  Platform info: ('Linux', 'shas0125', '3.10.0-693.33.1.el7.x86_64', '#1 SMP Thu May 24 16:41:13 UTC 2018', 'x86_64')2018-06-22 10:17:59,955 	pid=122711 	[assembly.py]	ERROR 	ValueError(need more than 0 values to unpack)

Could it be to do with a reference genome that is too far removed taxonomically from the reads?

**Comment by isaacovercast** [comment]
No, that wouldn't be the problem.

Are you sure step 2 is finishing without a problem? If you run step 2 with the -d flag what do you see in the ipyrad_log.txt file? What are the results of `ipyrad -p <yourparams>.txt -r`?

**Comment by isaacovercast** [comment]
Also, it wouldn't hurt to update to the most recent version of ipyrad. Always good to be on the current version.

**Comment by carlyraea** [comment]
Okay, I updated to the latest version so maybe that will help.

Steps 1 and 2 seem to go with no problems:

Step 1: Loading sorted fastq data to Samples

    Skipping: 85 Samples already found in Assembly
ipyrad_assembly_cladonia_macilenta.

    (can overwrite with force argument)


  Step 2: Filtering reads

    Skipping: All 85 selected Samples already edited.

    (can overwrite with force argument)




*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
What are the results of ipyrad -p <yourparams>.txt -r?

**Comment by isaacovercast** [comment]
Step 2 looked like it was completing fine before, but you had no data in your samples, so it could be in the same condition.

**Comment by carlyraea** [comment]
Whoops, here:

[caan8813@shas0137 scripts]$ ipyrad -p .txt -r?

Traceback (most recent call last):

  File "/projects/caan8813/software/miniconda2/bin/ipyrad", line 6, in
<module>

    from pkg_resources import load_entry_point

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3138, in <module>

    @_call_aside

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3122, in _call_aside

    f(*args, **kwargs)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3151, in _initialize_master_working_set

    working_set = WorkingSet._build_master()

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 664, in _build_master

    ws.require(__requires__)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 981, in require

    needed = self.resolve(parse_requirements(requirements))

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 867, in resolve

    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'jupyter' distribution was not
found and is required by ipyrad

Missing jupyter?

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
If you are convinced the raw files are fixed now you need to rerun steps 1 and 2 with the -f flag to force it to overwrite the status. If you fixed the raw files and reran ipyrad without the -f flag it'll just see that steps 1 and 2 already ran, and won't redo them.

**Comment by isaacovercast** [comment]
You need to tell it your params file.

 ipyrad -p your_params.txt -r

**Comment by carlyraea** [comment]
[caan8813@shas0137 data]$ ipyrad -p params_cladonia_macilenta2.txt -r

Traceback (most recent call last):

  File "/projects/caan8813/software/miniconda2/bin/ipyrad", line 6, in
<module>

    from pkg_resources import load_entry_point

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3138, in <module>

    @_call_aside

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3122, in _call_aside

    f(*args, **kwargs)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 3151, in _initialize_master_working_set

    working_set = WorkingSet._build_master()

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 664, in _build_master

    ws.require(__requires__)

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 981, in require

    needed = self.resolve(parse_requirements(requirements))

  File
"/projects/caan8813/software/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 867, in resolve

    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'jupyter' distribution was not
found and is required by ipyrad

Shoot, but looks similar.

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by isaacovercast** [comment]
conda install jupyter

**Comment by carlyraea** [comment]
Installing now. Odd because I've definitely installed it before.

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*
