### ISSUE TITLE
auto adjust threaded_view

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#30]
I'm thinking we should remove the parameter "engines_per_job" which splits up the jobs into the threaded view client. Instead we should just automatically calculate an optimal number of engines for each threaded_view client. 

For example, if there are very few CPUs (e.g., 4) then we start 4 jobs running with one thread each. If there are 20 CPUs we can start 5 jobs running with 4 threads each. If there are 100 we give each client 8 processors. I think there are diminishing returns above 6-8 threads, at least with vsearch. 

We might also find a way to modify this to partition optimally on HPC systems eventually. But something simple like above should work for now.

**Comment by isaacovercast** [comment]
This is old news too
