### ISSUE TITLE
typo in http://ipyrad.readthedocs.io/API_user-guide.html

### ISSUE THREAD

**Issue by tommydevitt** [dereneaton/ipyrad#303]
In the API User Guide (http://ipyrad.readthedocs.io/API_user-guide.html) under the section "Branching to subsample taxa"

print "Samples in data1:\n", "\n".join(subsamples)

should be

print "Samples in data1:\n", "\n".join(**data1.samples**)

I think. Just FYI.

**Comment by isaacovercast** [comment]
Fixed. Thanks tommy.
