### ISSUE TITLE
interrupted step3 doesn't kill vsearch

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#31]
Stopped step3 midstream and it left vsearch running. We need to ensure a kill signal is sent.

**Comment by dereneaton** [comment]
ipyclient.shutdown does not seem to be the answer. This messes up ipcluster so that it's hard to kill later. Looks like they have a shutdown with autorestart planned but implemented yet.

**Comment by isaacovercast** [comment]
This is fixed in 0.9
