### ISSUE TITLE
Step 3 : ValueError in build_clusters

### ISSUE THREAD

**Issue by tbarbette** [dereneaton/ipyrad#311]
Hi !
I get the following error :

`ValueError(invalid literal for int() with base 10: '1*\nCAGCT[···]` in build_clusters for Step 3.

The error is raised in line 486 of clustes_within.py : 

`int(x.split(";size=")[1].split(";")[0]), reverse=True)`

It seems to happen because an invalid line is added  by line 499 :` fseqs.append(">{}*\n{}".format(seed, alldereps[seed]))`
This last line seems to add fseqs a value like ">[...]1*\nCAGCT[...]" that is not correctly splitted by ` int(x.split(";size=")[1].split(";")[0])`.

Eventually leading to the int conversion of "1*\n..." which is indeed not a valid int. I don't see how this code path could actually work in any circumstance, actually. 
This has been added by @dereneaton  in 9d3acce19c962c234d58eafdd50a25fb66467b15 . Shouldn't you have appended an array already splitted in two instead of a \n sentence ? And then what is the purpose of "{}*", why the star ?

Thansk,
Tom

**Comment by isaacovercast** [comment]
Hi Tom,
Thanks for the detailed issue text. This block of code is sorting all reads that "match" to the seed sequence in descending order of number of dereplicated copies. The "{}*" is our internal indication that this first read is the seed sequence.

What version of ipyrad are you running? Have you tried with the most recent version of ipyrad pulled from conda?

**Comment by tbarbette** [comment]
Yes it is the most recent version, freshly pulled with conda.

Thanks for helping !

**Comment by tbarbette** [comment]
Note that with the proposed (wrong) fix, it ran up to the end. But I guess results should not be trusted then...

**Comment by tbarbette** [comment]
I think the older 0.7.12 was still used when the bug appeared. I re-ran the same test with 0.7.28 without my the change I proposed and it worked too. So i guess this has been fixed recently.

**Comment by tbarbette** [comment]
Unfortunately it actually came back even with the latest version...
ipyrad -p params-CL_cutNEW2.txt -s234567 -c 16 -t 16
 -------------------------------------------------------------
  ipyrad [v.0.7.28]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  loading Assembly: CL_cutNEW2
  from saved path: XX/Plate2/Plate2_demul_cutNEW_ipyrad/CL_cutNEW2.json
  establishing parallel connection:
  host compute node: [16 cores] on XX

  Step 2: Filtering reads 
    Skipping: All 15 selected Samples already edited.
    (can overwrite with force argument)    

  Step 3: Clustering/Mapping reads
  [####################] 100%  dereplicating         | 0:00:24  
  [##################  ]  93%  clustering            | 1:09:17  
  [####################] 100%  clustering            | 1:16:53  
  [####################] 100%  building clusters     | 0:00:03  

  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
ValueError(invalid literal for int() with base 10: '1-\nATGCGGTGTCAGGGATGGCGGCCCATACTCGGACTGCCCAATACCATAACGCCATATCCATGAATTTACGTCGCTGAAATACTCAATTTCCTGCAG')

**Comment by tbarbette** [comment]
The log : 
```
 -------------------------------------------------------------
  ipyrad [v.0.7.28]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Begin run: 2018-10-17 15:46
  Using args {'preview': False, 'force': False, 'threads': 16, 'results': False, 'quiet': False, 'merge': None, 'ipcluster': None, 'cores': 16, 'params': 'params-CL_cutNEW2.txt', 'branch': None, 'steps': '234567', 'debug': False, 'new': None, 'download': None, 'MPI': False}
  Platform info: ('Linux', 'XXX', '4.4.0-137-generic', '#163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018', 'x86_64')2018-10-17 17:04:08,763 	pid=21022 	[assembly.py]	ERROR 	ValueError(invalid literal for int() with base 10: '1-\nATGCGGTGTCAGGGATGGCGGCCCATACTCGGACTGCCCAATACCATAACGCCATATCCATGAATTTACGTCGCTGAAATACTCAATTTCCTGCAG')
```

I'm trying to grep the fastq files to find the one with this sequence.

**Comment by tbarbette** [comment]
I'm sending you the set of edits that contained that sequence by email, via wetransfer. Thanks !

**Comment by isaacovercast** [comment]
Thanks, I got the files. This is paired end GBS, yes?

**Comment by tbarbette** [comment]
Yes

**Comment by isaacovercast** [comment]
Hello, are you sure the sample you sent me was the one that failed? It passed step 3 for me fine:

```
ls -ltr tbarbette_clust_0.85/
-rw-rw-r-- 1 isaac isaac 101747690 Oct 17 19:22 136,2.trimmed.clustS.gz
-rw-rw-r-- 1 isaac isaac       325 Oct 17 19:23 s3_cluster_stats.txt

cat tbarbette_clust_0.85/s3_cluster_stats.txt 
              clusters_total  hidepth_min clusters_hidepth avg_depth_total avg_depth_mj avg_depth_stat sd_depth_total sd_depth_mj sd_depth_stat filtered_bad_align
136,2.trimmed        1368008            6            46041            1.68         8.57           8.57           2.11        7.77          7.77
```
Here's the params file I used:
```
------- ipyrad params file (v.0.7.28)-------------------------------------------
tbarbette                            ## [0] [assembly_name]: Assembly name. Used to name output directories for assembly steps
./                             ## [1] [project_dir]: Project dir (made in curdir if not present)
                               ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files
                               ## [3] [barcodes_path]: Location of barcodes file
./raws/136,2.trimmed_R*.fastq                               ## [4] [sorted_fastq_path]: Location of demultiplexed/sorted fastq files
denovo                         ## [5] [assembly_method]: Assembly method (denovo, reference, denovo+reference, denovo-reference)
                               ## [6] [reference_sequence]: Location of reference sequence file
pairgbs                            ## [7] [datatype]: Datatype (see docs): rad, gbs, ddrad, etc.
TGCAG,                         ## [8] [restriction_overhang]: Restriction overhang (cut1,) or (cut1, cut2)
5                              ## [9] [max_low_qual_bases]: Max low quality base calls (Q<20) in a read
33                             ## [10] [phred_Qscore_offset]: phred Q score offset (33 is default and very standard)
6                              ## [11] [mindepth_statistical]: Min depth for statistical base calling
6                              ## [12] [mindepth_majrule]: Min depth for majority-rule base calling
10000                          ## [13] [maxdepth]: Max cluster depth within samples
0.85                           ## [14] [clust_threshold]: Clustering threshold for de novo assembly
0                              ## [15] [max_barcode_mismatch]: Max number of allowable mismatches in barcodes
0                              ## [16] [filter_adapters]: Filter for adapters/primers (1 or 2=stricter)
35                             ## [17] [filter_min_trim_len]: Min length of reads after adapter trim
2                              ## [18] [max_alleles_consens]: Max alleles per site in consensus sequences
5, 5                           ## [19] [max_Ns_consens]: Max N's (uncalled bases) in consensus (R1, R2)
8, 8                           ## [20] [max_Hs_consens]: Max Hs (heterozygotes) in consensus (R1, R2)
4                              ## [21] [min_samples_locus]: Min # samples per locus for output
20, 20                         ## [22] [max_SNPs_locus]: Max # SNPs per locus (R1, R2)
8, 8                           ## [23] [max_Indels_locus]: Max # of indels per locus (R1, R2)
0.5                            ## [24] [max_shared_Hs_locus]: Max # heterozygous sites per locus (R1, R2)
0, 0, 0, 0                     ## [25] [trim_reads]: Trim raw read edges (R1>, <R1, R2>, <R2) (see docs)
0, 0, 0, 0                     ## [26] [trim_loci]: Trim locus edges (see docs) (R1>, <R1, R2>, <R2)
p, s, v                        ## [27] [output_formats]: Output formats (see docs)
                               ## [28] [pop_assign_file]: Path to population assignment file
```

**Comment by isaacovercast** [comment]
If you want to send me the raw data and the params file you're using I can try to reproduce this problem.

**Comment by isaacovercast** [comment]
It _looks_ like what is happening is if the orientation isn't recorded then this part of step 3 fails. I can't figure out why the orientation wouldn't be recorded though, it seems odd.

**Comment by isaacovercast** [comment]
Woop, it seems the orientation is there, but the separator is missing. The orientation is `-`, but there should be a `;` between the 1 and the -. Looking into why this might not be there....
```
ValueError(invalid literal for int() with base 10: '1-\nATGCGGTGTCAGGGATGGCGGCCCATACTCGGACTGCCCAATACCATAACGCCATATCCATGAATTTACGTCGCTGAAATACTCAATTTCCTGCAG')
```

**Comment by tbarbette** [comment]
The ability to reproduce the bug is a very good news ! We're stuck on this since quite some time.

**Comment by tbarbette** [comment]
I just had the error with "1+\n", I've been mislead thinking it was a problem with the seed because of the star in "1*", but last time it was actually "1-\n".
So is the problem in how vsearch writes its results? Or in build_clusters ?

**Comment by isaacovercast** [comment]
To be clear, I _cant_ reproduce the bug with the file you sent me, I just deduced this information from the code. The file you sent me runs fine, are you sure this is the sample that was failing?

**Comment by isaacovercast** [comment]
How did you determine the sample you gave me contained the sequence that generated the error? 

I restarted from step 1 using the R1/R2 trimmed files you gave me. It ran fine with the params you sent me. mindepth_majrule is not used during this part of step 3.

To use my params you'd have to start over from step 1, but I really don't think it's a parameters issue...

Here's exactly what's going on, but i'm still not sure why. `vsearch` writes out a '.utemp' file which has mappings from seeds to matching sequences, in a normal run it looks like this:
```
f5adbaada829ad6f7398d5431e1b962b;size=13;       aba917d543290e55cfc3abe04f0a67c5;size=13;       99.4    0       +       100.0
be04342a01c41ff4a0104e29ffe7b5df;size=12;       b24780b8bb9ec6ad5e8bb6804818b87c;size=13;       98.7    0       +       100.0
```

but for some reason when you are running it you're getting this:
```
cdd2b175b2cffccfbefde59a610568d8;size=126       e76daa53ade9cfcbd34a4d6b2b78c446;size=150       98.1    0       +       100.0
7c696736907d65c2c204c7d07ddfb466;size=67        40bd17455635cd439affe18f4a738b9b;size=81        98.1    0       +       100.0
```

See the difference?

**Comment by tbarbette** [comment]
Yes ok I see.

I just zcat'ed all the files grepping for "ATGCGGTGTCAGGGAT..."

By the way I just ran your parameter file, with the following command and it gave me the error :

```
ipyrad -p params.txt -s 123 -t 16 -c 16

 -------------------------------------------------------------
  ipyrad [v.0.7.28]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  New Assembly: tbarbette
  establishing parallel connection:
  host compute node: [16 cores] on XX

  Step 1: Loading sorted fastq data to Samples
  [####################] 100%  loading reads         | 0:00:01
  2 fastq files loaded to 1 Samples.

  Step 2: Filtering reads
  [                    ]   0%  processing reads      | 0:00:21
  [####################] 100%  processing reads      | 0:00:45

  Step 3: Clustering/Mapping reads
  [####################] 100%  dereplicating         | 0:00:23
  [                    ]   0%  clustering            | 0:07:55  ▒
  [####################] 100%  clustering            | 0:44:21  ▒N
  [####################] 100%  building clusters     | 0:00:03

  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
ValueError(invalid literal for int() with base 10: '1-\nATGCGGTGTCAGGGATGGCGGCCC
ATACTCGGACTGCCCAATACCATAACGCCATATCCATGAATTTACGTCGCTGAAATACTCAATTTCCTGCAG')

```

**Comment by isaacovercast** [comment]
Is there any chance you changed the version of vsearch that ipyrad is using internally?

**Comment by isaacovercast** [comment]
I finally figured out how to replicate this behavior, but I had to "update" vsearch in the ipyrad/bins directory. The version we use internally is 2.0.3, but if i download the latest version, and change the `vsearch-linux-x86_64` symlink to point to vsearch-2.8.4

```
  Step 3: Clustering/Mapping reads
  [####################] 100%  dereplicating         | 0:00:01  
  [####################] 100%  clustering            | 0:00:03  
  [####################] 100%  building clusters     | 0:00:01  

  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
ValueError(invalid literal for int() with base 10: '1-\nTCTCTGGCACAGAGTTAGCCGATGCTTATTCCTCAGATACCGTCATTACTTCTTCTCTGAGAAAAGGAGTTTACGACCCGTGGGnnnnGACCCGTGGGCCTTCTACCTCCACGCGGCATTGCTCCGTCAGGCTTTCGCCCATTGCGGAAAATTCCCCACTGCTG')
```

**Comment by isaacovercast** [comment]
Ahh, yes, thanks for the info @hmontenegro. vsearch recently refactored their fasta writing code, and it (obviously) breaks something ipyrad is currently relying (the trailing ';' in the read id appended during dereplication). Is there some specific feature of the new vsearch that you're interested in? We can update the ipyrad internal vsearch if there's a compelling reason.

**Comment by hmontenegro** [comment]
> Is there some specific feature of the new vsearch that you're interested in?

Not really, I just installed this version because it was the latest at the time I installed ipyrad. As ipyrad works fine with older vsearch releases, I think the only compelling reason to update is if newer versions offer performance gains (which I am not aware of).

**Comment by tbarbette** [comment]
Now that you mention it, I did recompile vsearch quite some time ago... Sorry, I should have thought of that.
It's not really about feature, I recompiled it with -march=native and -O3 options to improve the speed. The version shipped with ipyrad is compiled for generic cpus and I had a lot of slow downs because of calls to functions that can be inlined. Profiling with the newer, compiled locally, version looks much better. But compiling with an older version would lead to the same improvements.
If compatibility can be insured it would probably be good anyway.

**Comment by isaacovercast** [comment]
We distribute generic binaries for (hopefully) obvious reasons: 1) installation is easier for users, 2) compatibility and program behavior are guaranteed and easy to validate & 3) An ounce of sacrificed performance is worth saving hours of painful troubleshooting downstream.

What brings you to ipyrad? Your cv doesn't contain much computational biology. Just curious.

**Comment by tbarbette** [comment]
I only helped someone which had performance problems. My day to day research is mainly about high-performance programming. In this case, considering she has to run ipyrad for multiple species that spend days on the same bits of unoptimized code in vsearch (I mean that after profiling vsearch with linux perf), I thought a simple recompilation with the rights parameters could improve performance quite much. I'll recompile 2.4.4 and report the improvements it made, so this whole mess won't have been for nothing...

Thanks for the help !

**Comment by tbarbette** [comment]
With the shipped version the clustering time was 1h02m for a total (step 2 to 7) of 132minutes. With the recompiled (and added a few inlining) the clustering took 56m for a total of 126minutes. So we're looking at a little 10% for vsearch itself but overall, a mere 5%. Not that much...

**Comment by tbarbette** [comment]
Note that this ran on latest Xeon Gold, so the re-compiling itself probably allows to take advantage of the latest arch improvements. Recompiling on a Sandy Bridge would not give that much, probably.
