### ISSUE TITLE
ipyrad fails to find binaries when installed into virtual-environment

### ISSUE THREAD

**Issue by ostueker** [dereneaton/ipyrad#312]
**The Error:**
When installing ipyrad-0.7.28 into a virtualenv on our HPC clusters, it fails to find binaries that are distributed with ipyrad:

```console
[user@cedar5 ipyrad]$ module load python/2.7.14 
[user@cedar5 ipyrad]$ . ipyrad_env/bin/activate
(ipyrad_env) [user@cedar5 ipyrad]$ cd test/
(ipyrad_env) [user@cedar5 test]$ ipyrad -n
Traceback (most recent call last):
  File "/home/user/ipyrad/ipyrad_env/bin/ipyrad", line 7, in <module>
    from ipyrad.__main__ import main
  File "/home/user/ipyrad/ipyrad_env/lib/python2.7/site-packages/ipyrad/__init__.py", line 235, in <module>
    for _binn, _binx in zip(_binnames, _getbins()):
  File "/home/user/ipyrad/ipyrad_env/lib/python2.7/site-packages/ipyrad/__init__.py", line 222, in _getbins
    assert _cmd_exists(muscle), "muscle not found here: "+muscle
AssertionError: muscle not found here: /home/user/ipyrad/ipyrad_env/lib/python2.7/site-packages/bin/muscle-linux-x86_64
(ipyrad_env) [user@cedar5 test]$
```

**Installation Procedure:**
* Create and activate new virtualenv with Python 2.7.14
* Downloaded [ipyrad-0.7.28 as .tar.gz from GitHub](https://github.com/dereneaton/ipyrad/archive/0.7.28.tar.gz)
    * either install from the extracted sources using `python setup.py install` after installing requirements using `pip install -r requirements.txt` or
   * alternatively build wheel and install that using `pip install ipyrad-0.7.28-py2-none-any.whl`

**Workaround:**
The binaries (muscle, bedtools, samtools, etc.) are actually being installed and located in `/home/user/ipyrad/ipyrad_env/bin` along with the main `ipyrad` script.  I was able to work around the error by creating a symlink `ipyrad_env/lib/python2.7/site-packages/bin` pointing to `ipyrad_env/bin`.

I'm not sure whether the setup.py script should really install those binaries in `ipyrad_env/lib/python2.7/site-packages/bin` or `__init__.py` gets the `bin_path` wrong.

**Why not just use Anaconda?**
For several reasons using Anaconda doesn't work well in our High Performance Computing environment.  For one, the binaries distributed by Anaconda are compiled for maximum compatibility, whereas the wheels compiled by us can make use of newer architecture and are more efficient.
Further the conda packages don't always find/use our centrally installed libraries to play nice with our Infiniband or OminiPath network, scheduler, etc.

**Comment by ostueker** [comment]
Another workaround is to apply the following patch:

```patch
diff --git a/ipyrad/__init__.py b/ipyrad/__init__.py
index e05424c..8e62b1a 100644
--- a/ipyrad/__init__.py
+++ b/ipyrad/__init__.py
@@ -168,7 +168,10 @@ def _getbins():
     path = _os.path.abspath(_os.path.dirname(__file__))
 
     ## find bin directory
-    ipyrad_path = _os.path.dirname(path)
+    if 'VIRTUAL_ENV' in _os.environ:
+        ipyrad_path = _os.environ['VIRTUAL_ENV']
+    else:
+        ipyrad_path = _os.path.dirname(path)
     bin_path = _os.path.join(ipyrad_path, "bin")
 
     ## get the correct binaries
```

**Comment by isaacovercast** [comment]
Thanks for the awesome detail in this issue. Sounds like you have a pretty good handle on the pip install, even though it's not strictly supported and i'm a little surprised it worked, but it's cool that you got it working. Also, i've don't use veritualenv, so this hasn't come up for me before. The patch seems straightforward though, so if it helps you I applied the patch and pushed it to the repo. If you want to test it out to verify functionality, that'd be great. Thanks for the issue.

**Comment by ostueker** [comment]
Well, it's kind of a hack that turned out to work.  I have another issue that I've just posted on Gitter. Not sure if that is related.
