### ISSUE TITLE
ideas for speed improvements to step2

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#32]
Ideas: 

1. Parallelize tmp file concatenation step. 
2. ~~Don't gzip temp files~~ (Done.)
3. Use heapq method to concatenate files.

**Comment by isaacovercast** [comment]
Removed the gzip for tempfiles and also for the final output fastq file. It's WAY faster. 500Mb test file w/ gzip timed out ~20 minutes. Without gzip ~5 minutes. Big improvement.

**Comment by dereneaton** [comment]
closing this as we now have: 
1. No gzip
2. better chunking
3. we know we can't really improve on concatenating tmp files.
