### ISSUE TITLE
"denovo+reference" returning too much missing info when comparing with "reference"

### ISSUE THREAD

**Issue by saraema-silva** [dereneaton/ipyrad#322]
I performed the "denovo+reference" assembly method on my RADseq data and I obtained a vcf file with too much missing information, even for the reference aligned markers, when comparing with the vcf file resulted after using the "reference" method. When I filtered my denovo+ref vcf file for missing data >0.25 (max miss 0.75 in vcftools) an entire chromosome is discarded (LGB01). On the other hand this do not occur with the vcf file resulted from the "reference" which seems to be ok. What is the explanation for this huge difference even for the reference aligned markers? The information for the reference aligned markers resulted from both methods seems to be very different.
You can see in the link below both vcf and parameter files (data 1 is denovo+reference assembled, data 2 is only reference assembled).
https://www.dropbox.com/s/dgs2uo2laijov6q/lane1234_ipyrad.tar.xz?dl=0
Also, even when using only "reference", reads that don't map to the reference are denovo assembled and included in the outfiles, as I commented in another issue.

**Comment by tahamimo** [comment]
have you checked your data against contaminants like Wolbachia?

**Comment by isaacovercast** [comment]
denovo+reference is unsupported in the current version and v0.7 is deprecated, so this isn't really an issue anymore. I would love to get denove+reference working again in v0.9, for sure, but it might take some time.
