### ISSUE TITLE
format of .snps.map

### ISSUE THREAD

**Issue by tangerzhang** [dereneaton/ipyrad#323]
Could you please explain the format of *.snps.map?
1       rad0_snp0       0       1
1       rad0_snp1       0       2
1       rad0_snp2       0       3
1       rad0_snp3       0       4
1       rad0_snp4       0       5
2       rad1_snp0       0       6
2       rad1_snp1       0       7
2       rad1_snp2       0       8
2       rad1_snp3       0       9
3       rad2_snp0       0       10
3       rad2_snp1       0       11
3       rad2_snp2       0       12
3       rad2_snp3       0       13
3       rad2_snp4       0       14
3       rad2_snp5       0       15
3       rad2_snp6       0       16
I can see the first column is chromosome ID. Second one is name of SNPs.
What are the third and fourth column?
Thanks!

**Comment by isaacovercast** [comment]
If you have questions like this in the future it's probably easier and faster to jump on the gitter channel:

https://gitter.im/dereneaton/ipyrad#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications
