### ISSUE TITLE
changed nomenclature in package allel

### ISSUE THREAD

**Issue by eikemq** [dereneaton/ipyrad#325]
Hi,

testing the pca.py function I recognized a change how allel names its functions in the 1.2.0 version.

In the pca.py you refer to the pca and pairwise_distance function with:

    allel.stats.pca
    allel.stats.pairwise_distance

this needs to be changed to

    allel.pca
    allel.pairwise_distance

all the best
eike

**Comment by isaacovercast** [comment]
Fixed. Thanks for the tip. 944e035a6e3e4e557e5ad46370539658f0b2c9c8
