### ISSUE TITLE
TypeError(Can't broadcast (115, 8309, 108) -> (115, 8304, 108))

### ISSUE THREAD

**Issue by bosquerj** [dereneaton/ipyrad#327]
Dear Deren, 

My dataset consist of 4 species and I am running IPYRAD on a cluster. When I run IPYRAD with just one of the species I get nice results. However when running IPYRAD with all 4 species at the same time I consistently get this error message during step 6: 

Step 6: Clustering at 0.85 similarity across 115 samples
  [####################] 100%  concat/shuffle input  | 0:01:40  
  [####################] 100%  clustering across     | 12:31:15  
  [####################] 100%  building clusters     | 0:02:40  
  [####################] 100%  aligning clusters     | 0:37:56  
  [################### ]  97%  database indels       | 0:04:25  
  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
TypeError(Can't broadcast (115, 8309, 108) -> (115, 8304, 108))

I have tried to run with just a single command from steps 1 until 7 and also using subdata to select for samples with good reads. I know that other people had similar issues with this error but their solutions does not seems to be working for me. My restrictions sites are correct and I have good consensus reads. Any help will be really appreciated. 

Summary stats of Assembly subdata
------------------------------------------------
                                      state  reads_raw  reads_passed_filter  ...  hetero_est  error_est  reads_consens
Mic_bras_CaroMA_CHUNB52143_Trim2          5    1669148              1669016  ...    0.014146   0.004279          47246
Mic_bras_EstrMA_CTMZ-18270_Trim2          5   10551651             10551373  ...    0.013984   0.003566         161446
Mic_bras_EstrMA_CTMZ-18271_Trim2          5    1481923              1481818  ...    0.015323   0.004553          37690
Mic_bras_EstrMA_CTMZ-18272_Trim2          5    1525507              1525389  ...    0.012660   0.003720          36805
Mic_bras_EstrMA_CTMZ-18273_Trim2          5    1749656              1749494  ...    0.015350   0.003965          41589
Mic_bras_EstrMA_CTMZ-18275_Trim2          5    1516476              1516340  ...    0.014839   0.004666          41913
Mic_bras_EstrMA_CTMZ-18276_Trim2          5    3488313              3488246  ...    0.026093   0.013961          60589
Mic_bras_EstrMA_CTMZ-18277_Trim2          5    1375768              1375630  ...    0.015046   0.004967          39748
Mic_bras_EstrMA_CTMZ-18278_Trim2          5    1310721              1310629  ...    0.015202   0.004951          39026
Mic_bras_EstrMA_CTMZ-18279_Trim2          5    1564260              1564132  ...    0.014328   0.004527          42632
Mic_bras_EstrMA_CTMZ-18280_Trim2          5    2096237              2096062  ...    0.015790   0.003820          45786
Mic_bras_EstrMA_CTMZ-18281_Trim2          5    1588959              1588822  ...    0.013719   0.004138          42727
Mic_bras_EstrMA_CTMZ-18282_Trim2          5    1676230              1676102  ...    0.014993   0.004511          45002
Mic_bras_MA_CTMZ-10851_Trim2              5    2235143              2234945  ...    0.017398   0.004340          47523
Mic_bras_MateTO_CHUNB25352_Trim2          5    1855877              1855733  ...    0.015480   0.004558          48774
Mic_bras_SaoFMG_CHUNB71353_Trim2          5    6379611              6379482  ...    0.013289   0.004215         152697
Mic_ibib_CratCE_CHUNB64751_Trim2          5    1652507              1652354  ...    0.013791   0.004324          43578
Mic_ibib_CratCE_CHUNB64753_Trim2          5    1140798              1140712  ...    0.014658   0.005138          33293
Mic_lemn_AlmePA_CTMZ-18316_Trim2          5    2019630              2019483  ...    0.011930   0.003863          47075
Mic_lemn_BelePA_CTMZ-14750_Trim2          5    2735225              2735028  ...    0.013789   0.003872          61242
Mic_lemn_CaroMA_CTMZ-18318_Trim2          5    2037785              2037630  ...    0.014270   0.003924          49332
Mic_lemn_CaroMA_CTMZ-18319_Trim2          5    2165249              2165171  ...    0.010387   0.004850          64252
Mic_lemn_CaroMA_CTMZ-18320_Trim2          5    1376548              1376506  ...    0.009989   0.005164          47486
Mic_lemn_CaroMA_CTMZ-18321_Trim2          5    2434253              2434173  ...    0.010625   0.004776          66569
Mic_lemn_CaroMA_CTMZ-18324_Trim2          5    4414720              4414293  ...    0.012179   0.003275          71340
Mic_lemn_CaroMA_CTMZ-18326_Trim2          5    4484652              4484239  ...    0.013177   0.003323          73443
Mic_lemn_CaroMA_CTMZ-18327_Trim2          5    6381898              6381304  ...    0.012489   0.003209         100403
Mic_lemn_CaroMA_CTMZ-18328_Trim2          5    5043989              5043522  ...    0.013118   0.003143          76046
Mic_lemn_CruzPB_CHUFPB-12564_Trim2        5     364759               364715  ...    0.025532   0.009506           8681
Mic_lemn_CruzPB_CHUPB-L372_Trim2          5     900686               900647  ...    0.009399   0.004428          29488
Mic_lemn_CruzPB_CHUPB-L403_Trim2          5     584137               584104  ...    0.009060   0.004686          22642
Mic_lemn_EstrMA_CTMZ-18303_Trim2          5    7310371              7309720  ...    0.012060   0.003254         129306
Mic_lemn_EstrMA_CTMZ-18304_Trim2          5    6680647              6679989  ...    0.012376   0.003331         113749
Mic_lemn_EstrMA_CTMZ-18305_Trim2          5    3956114              3955784  ...    0.012391   0.003673          68414
Mic_lemn_EstrMA_CTMZ-18306_Trim2          5    4673854              4673419  ...    0.011966   0.003441          80989
Mic_lemn_EstrMA_CTMZ-18307_Trim2          5    6154462              6153913  ...    0.011540   0.003261         106649
Mic_lemn_EstrMA_CTMZ-18308_Trim2          5    8714717              8714168  ...    0.010114   0.003773         168721
Mic_lemn_EstrMA_CTMZ-18310_Trim2          5    3744382              3744262  ...    0.017594   0.008565         101959
Mic_lemn_EstrMA_CTMZ-18312_Trim2          5    2058862              2058759  ...    0.010240   0.003794          51307
Mic_lemn_EstrMA_CTMZ-18322_Trim2          5    7538289              7537810  ...    0.009172   0.003654         161698
Mic_lemn_EstrMA_CTMZ-18323_Trim2          5    4868702              4868404  ...    0.011329   0.004025          91544
Mic_lemn_EstrMA_CTMZ-18325_Trim2          5    5871480              5871099  ...    0.010975   0.003473         112793
Mic_lemn_EstrMA_CTMZ-18329_Trim2          5    5985518              5985152  ...    0.011434   0.003768         105984
Mic_lemn_GoiaGO_CTMZ-18302_Trim2          5    9530383              9529848  ...    0.010105   0.003579         182759
Mic_lemn_Guya_BPN-3525_Trim2              5    1477076              1476990  ...    0.012709   0.004600          40372
Mic_lemn_ItacAM_CTMZ-18317_Trim2          5    8765515              8764935  ...    0.009038   0.003644         194305
Mic_lemn_JoaPPB_CTMZ-10859_Trim2          5    1149017              1148989  ...    0.036385   0.018058          12730
Mic_lemn_JoaPPB_CTMZ-10862_Trim2          5    1627965              1627876  ...    0.011323   0.004528          46418
Mic_lemn_JoaPPB_CTMZ-10863_Trim2          5    1581339              1581221  ...    0.012220   0.004570          41205
Mic_lemn_JoaPPB_CTMZ-10865_Trim2          5    1573913              1573800  ...    0.012072   0.004276          41678
Mic_lemn_MT_CTMZ-05297_Trim2              5    2581451              2581293  ...    0.012161   0.004131          58464
Mic_lemn_MachRO_CTMZ-15710_Trim2          5    1840319              1840184  ...    0.011348   0.003799          43550
Mic_lemn_MachRO_CTMZ-17089_Trim2          5    3649398              3649184  ...    0.011394   0.003748          85655
Mic_lemn_MachRO_CTMZ-17093_Trim2          5    3244016              3243829  ...    0.012719   0.003910          77605
Mic_lemn_MachRO_CTMZ-17109_Trim2          5    8236150              8235574  ...    0.009470   0.003746         200040
Mic_lemn_MelgPA_CTMZ-14573_Trim2          5    1695789              1695667  ...    0.010829   0.004280          41742
Mic_lemn_MelgPA_CTMZ-18313_Trim2          5    2121215              2121064  ...    0.011394   0.003748          48458
Mic_lemn_NisiRN_AAGARDA-8890_Trim2        5     841533               841531  ...    0.017299   0.006961          25492
Mic_lemn_OuviGO_CTMZ-18295_Trim2          5     645238               645228  ...    0.047337   0.021231           7116
Mic_lemn_PA_CTMZ-09985_Trim2              5    5108956              5108838  ...    0.008935   0.002907         100219
Mic_lemn_PA_H-14183_Trim2                 5    8629637              8629324  ...    0.007995   0.004120         275279
Mic_lemn_PA_H-14316_Trim2                 5    5834265              5833880  ...    0.009502   0.004290         159112
Mic_lemn_PontGO_CTMZ-18298_Trim2          5    1406728              1406693  ...    0.026538   0.011051          31204
Mic_lemn_PorTPA_CTMZ-18314_Trim2          5     836820               836792  ...    0.048861   0.020464           6285
Mic_lemn_PorUAM_CTMZ-18315_Trim2          5    8443716              8443124  ...    0.009620   0.003791         189416
Mic_lemn_RO_H-17765_Trim2                 5    7948903              7948404  ...    0.010158   0.003783         199713
Mic_lemn_RioTPB_CHUFPB-608_Trim2          5     844140               844096  ...    0.011872   0.004554          28116
Mic_lemn_SaoDBA_CTMZ-18300_Trim2          5    4312866              4312662  ...    0.026375   0.013042          52504
Mic_lemn_SaoDBA_CTMZ-18301_Trim2          5   14317930             14317360  ...    0.010796   0.003740         198285
Mic_lemn_TO_CTMZ-00072_Trim2              5    1714295              1714168  ...    0.011755   0.004542          47845
Mic_lemn_TO_CTMZ-00934_Trim2              5    2747571              2747393  ...    0.011336   0.003748          62905
Mic_lemn_VianGO_CTMZ-18299_Trim2          5    1610279              1610188  ...    0.042151   0.005229          11361
Mic_lemn__INPA-911_Trim2                  5    1136943              1136881  ...    0.010882   0.004511          32817
Mic_suri_AC_H-13605_Trim2                 5    1619165              1619099  ...    0.013807   0.005738          42237
Mic_suri_AP_INPA-113_Trim2                5    1542828              1542726  ...    0.021251   0.010720          34812
Mic_suri_AP_INPA-215_Trim2                5    1917186              1917059  ...    0.015991   0.007764          55459
Mic_suri_AP_INPA-293_Trim2                5     881679               881614  ...    0.025924   0.012246           9939
Mic_suri_AltaPA_CTMZ-16007_Trim2          5     540272               540217  ...    0.068171   0.028461            913
Mic_suri_CaraRR_INPA-555_Trim2            5    1456188              1456089  ...    0.020856   0.010220          30779
Mic_suri_CaraRR_INPA-595_Trim2            5    2004381              2004365  ...    0.011526   0.005667          46061
Mic_suri_CaraRR_INPA-596_Trim2            5    1135678              1135656  ...    0.062314   0.023660           4823
Mic_suri_CaraRR_INPA-667_Trim2            5    2092899              2092843  ...    0.006708   0.003924          67008
Mic_suri_CaroMA_CTMZ-18345_Trim2          5    1586431              1586364  ...    0.013305   0.005790          47213
Mic_suri_CaroMA_CTMZ-18350_Trim2          5    1495082              1494962  ...    0.017798   0.007977          37397
Mic_suri_CaroMA_CTMZ-18351_Trim2          5    1154237              1154140  ...    0.019044   0.008394          28391
Mic_suri_CaroMA_CTMZ-18352_Trim2          5    1006811              1006743  ...    0.019179   0.009125          24283
Mic_suri_CaroMA_CTMZ-18353_Trim2          5    1990354              1990216  ...    0.016165   0.007320          55675
Mic_suri_EstrMA_CTMZ-18338_Trim2          5      36559                36556  ...    0.069388   0.023427            111
Mic_suri_EstrMA_CTMZ-18339_Trim2          5    1378316              1378231  ...    0.017531   0.007835          34734
Mic_suri_EstrMA_CTMZ-18340_Trim2          5    1730881              1730775  ...    0.016137   0.007795          48594
Mic_suri_EstrMA_CTMZ-18347_Trim2          5    1892187              1892048  ...    0.015973   0.007328          52526
Mic_suri_EstrMA_CTMZ-18348_Trim2          5    1691388              1691263  ...    0.016555   0.007511          46532
Mic_suri_EstrMA_CTMZ-18349_Trim2          5    1781178              1781065  ...    0.015405   0.007603          52600
Mic_suri_FaroPA_CTMZ-14655_Trim2          5    1580032              1579968  ...    0.012873   0.004567          43274
Mic_suri_FilaTO_CTMZ-18346_Trim2          5    1852803              1852727  ...    0.012376   0.005307          52398
Mic_suri_Guya_AMNH-R152304_Trim2          5    1834386              1834293  ...    0.012491   0.005168          51003
Mic_suri_Guya_AMNH-R152305_Trim2          5     742610               742587  ...    0.029976   0.015348          11475
Mic_suri_JacaPA_CTMZ-06425_Trim2          5    1413389              1413335  ...    0.013379   0.006061          41129
Mic_suri_JuruPA_CTMZ-14676_Trim2          5    2128021              2127933  ...    0.013277   0.005289          60552
Mic_suri_JuruPA_CTMZ-18342_Trim2          5     911706               911644  ...    0.008465   0.003690          34292
Mic_suri_JuruPA_CTMZ-18343_Trim2          5    1196445              1196368  ...    0.018235   0.009079          29276
Mic_suri_LetiColomb_CTMZ-18337_Trim2      5     354139               354110  ...    0.074453   0.031137            911
Mic_suri_ManaAM_INPA-100_Trim2            5    1072272              1072204  ...    0.028559   0.013120          16956
Mic_suri_ManaAM_INPA-120_Trim2            5     730007               729956  ...    0.047514   0.017713           3363
Mic_suri_ManaAM_INPA-49_Trim2             5    1452479              1452375  ...    0.020897   0.009923          32870
Mic_suri_MelgPA_CTMZ-14579_Trim2          5    1621986              1621926  ...    0.011308   0.004277          43987
Mic_suri_MelgPA_CTMZ-18341_Trim2          5    1921195              1921112  ...    0.012139   0.004687          67780
Mic_suri_MelgPA_CTMZ-18344_Trim2          5    1858521              1858447  ...    0.013006   0.005481          53565
Mic_suri_NapoEcuad_KU-202957_Trim2        5    1748565              1748467  ...    0.019508   0.008950          46302
Mic_suri_PotaGuya_BPN3546_Trim2           5    1314336              1314225  ...    0.011648   0.004514          32858
Mic_suri_RO_H-17766_Trim2                 5    1477176              1477093  ...    0.012801   0.005081          38319
Mic_suri_RO_H-17767_Trim2                 5    1601752              1601676  ...    0.013182   0.005142          41639
Mic_suri_RO_LSUMZ-H17768_Trim2            5    1483636              1483571  ...    0.013032   0.005257          39164
Mic_suri_RuroPA_CTMZ-11633_Trim2          5    1598173              1598120  ...    0.013669   0.005864          46916
Mic_suri_SapeMT_CTMZ-05799_Trim2          5    1359331              1359271  ...    0.011091   0.004819          38621

[115 rows x 8 columns]

------- ipyrad params file (v.0.7.29)-------------------------------------------
subdata                        ## [0] [assembly_name]: Assembly name. Used to name output directories for assembly steps
/ddn/home7/r1978/ptmp/IPYRAD/IPYRAD_runs/Micrurus/Micrurus50seq ## [1] [project_dir]: Project dir (made in curdir if not present)
                               ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files
                               ## [3] [barcodes_path]: Location of barcodes file
/home/ums/r1978/ptmp/IPYRAD/Combined/6_conc_4Dec_BrazilSnakeFish/Mic_* ## [4] [sorted_fastq_path]: Location of demultiplexed/sorted fastq files
denovo                         ## [5] [assembly_method]: Assembly method (denovo, reference, denovo+reference, denovo-reference)
                               ## [6] [reference_sequence]: Location of reference sequence file
ddrad                          ## [7] [datatype]: Datatype (see docs): rad, gbs, ddrad, etc.
GTAC, GAATTC                   ## [8] [restriction_overhang]: Restriction overhang (cut1,) or (cut1, cut2)
5                              ## [9] [max_low_qual_bases]: Max low quality base calls (Q<20) in a read
33                             ## [10] [phred_Qscore_offset]: phred Q score offset (33 is default and very standard)
6                              ## [11] [mindepth_statistical]: Min depth for statistical base calling
6                              ## [12] [mindepth_majrule]: Min depth for majority-rule base calling
10000                          ## [13] [maxdepth]: Max cluster depth within samples
0.85                           ## [14] [clust_threshold]: Clustering threshold for de novo assembly
2                              ## [15] [max_barcode_mismatch]: Max number of allowable mismatches in barcodes
0                              ## [16] [filter_adapters]: Filter for adapters/primers (1 or 2=stricter)
62                             ## [17] [filter_min_trim_len]: Min length of reads after adapter trim
2                              ## [18] [max_alleles_consens]: Max alleles per site in consensus sequences
5                              ## [19] [max_Ns_consens]: Max N's (uncalled bases) in consensus (R1, R2)
8                              ## [20] [max_Hs_consens]: Max Hs (heterozygotes) in consensus (R1, R2)
57                             ## [21] [min_samples_locus]: Min # samples per locus for output
20                             ## [22] [max_SNPs_locus]: Max # SNPs per locus (R1, R2)
8                              ## [23] [max_Indels_locus]: Max # of indels per locus (R1, R2)
0.5                            ## [24] [max_shared_Hs_locus]: Max # heterozygous sites per locus (R1, R2)
0, 0, 0, 0                     ## [25] [trim_reads]: Trim raw read edges (R1>, <R1, R2>, <R2) (see docs)
0, 0, 0, 0                     ## [26] [trim_loci]: Trim locus edges (see docs) (R1>, <R1, R2>, <R2)
G, a, g, k, m, l, n, p, s, u, t, v ## [27] [output_formats]: Output formats (see docs)
                               ## [28] [pop_assign_file]: Path to population assignment file

**Comment by bosquerj** [comment]
now running the step 6 with the -d flag:




2019-02-10 15:27:33,588 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:33,588 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:34,199 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:34,199 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:34,815 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:34,816 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:36,738 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:36,739 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:39,428 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:39,439 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:41,408 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:41,408 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:44,155 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:44,155 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:47,666 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:47,762 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:48,586 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:48,587 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:49,345 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:49,345 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:50,951 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:51,014 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:58,720 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:58,721 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:27:59,513 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:27:59,513 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:28:01,784 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 9954, 108)
2019-02-10 15:28:01,784 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:28:03,663 	pid=12518 	[cluster_across.py]	INFO 	inarr shape (115, 8309, 108)
2019-02-10 15:28:03,663 	pid=12518 	[cluster_across.py]	INFO 	iset shape (115, 476142, 108)
2019-02-10 15:28:06,130 	pid=12441 	[assembly.py]	ERROR 	TypeError(Can't broadcast (115, 8309, 108) -> (115, 8304, 108))
2019-02-10 15:28:08,300 	pid=12441 	[assembly.py]	INFO 	  shutting down engines
2019-02-10 15:28:08,340 	pid=12441 	[assembly.py]	INFO 	  finished shutdown
2019-02-10 15:28:08,346 	pid=12441 	[__init__.py]	INFO 	debugging turned off

**Comment by isaacovercast** [comment]
Try branching and removing samples with very low consensus read count (e.g. Mic_suri_EstrMA_CTMZ-18338_Trim2 has 111 consensus reads). I _think_ there's a problem with these very very poor quality samples.

**Comment by isaacovercast** [comment]
Inside `sub_building_indels` the number of loci in the assembly comes from `get_nloci` which asks for the len() of the tmparrs.h5["seedsarr"] array. However, indels_*.tmp.npy can sometimes be longer (in the # of loci) than the length of the seedsarr, and you'll get this broadcast error. As for how we get in this mess i'm not sure yet.

One clue, samples are in the catcons file that don't make it into the catclust. If they don't make it to catclust, then it means they aren't in the temp align_*.fa files. Another clue, the shape of all the files in indels_*.tmp.npy and the shape of catclust agree. If you run the sub_building_indels code by hand and force nloci to be the true length of catclust then it works perfectly.

It seems that some good loci, for whatever reason, end up in catclust fine, but are missing from the seedsarr. It must have something to do with very poor quality samples, maybe with loci that are seeds that don't have hits from any other sample?

**Comment by isaacovercast** [comment]
Looks like the align_*, duples_* and indels_* files in the tmpalign directory all agree, and agree with the catclust.gz file. I think get_seeds_and_hits is the bad apple. I think it's dropping loci for some reason.

**Comment by isaacovercast** [comment]
I figured it out. Long sample names! I was _right_ about get_seeds_hits(). When you do np.loadtxt to read in the utemp.sort file the default string size is 37 characters, and it simply truncates anything longer. I don't know how np decides on "S|37", but you can see here that it happens:

![image](https://user-images.githubusercontent.com/5974975/55205938-301d6100-51ab-11e9-8910-fa9981ff32f0.png)

I ended up doing a bunch of notebook hacking to try to figure out what was going on because it was bugging the shit out of me. Ended up with 2 sets, one from using np.loadtext, and open(conshandle) as inside `sub_build_clustbits`. Making sets of each of these and taking diffs you can see what's happening:

set(['Dolan_Falls_JKK_Dolan_Falls_Pres_1274', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1096', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1090', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1100', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1219', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1029', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1217', 'Dolan_Falls_JKK_Dolan_Falls_Pres_1221'])

set(['Dolan_Falls_JKK_Dolan_Falls_Pres_10292', 'Dolan_Falls_JKK_Dolan_Falls_Pres_11002', 'Dolan_Falls_JKK_Dolan_Falls_Pres_12217', 'Dolan_Falls_JKK_Dolan_Falls_Pres_12190', 'Dolan_Falls_JKK_Dolan_Falls_Pres_10904', 'Dolan_Falls_JKK_Dolan_Falls_Pres_10967', 'Dolan_Falls_JKK_Dolan_Falls_Pres_10961', 'Dolan_Falls_JKK_Dolan_Falls_Pres_12748', 'Dolan_Falls_JKK_Dolan_Falls_Pres_12172'])

**Comment by isaacovercast** [comment]
Unbelievably difficult to debug. No fix yet.

**Comment by isaacovercast** [comment]
Fixed in 6c9b003e2b8e5193413c2767389ad0c96f28e8c5

**Comment by bosquerj** [comment]
Thanks a lot!!! I will try to run again with this update
