### ISSUE TITLE
Step7-rror in filter_stacks on chunk 0: ValueError(zero-size array to reduction operation minimum which has no identity)

### ISSUE THREAD

**Issue by dxkyq917** [dereneaton/ipyrad#328]
I have searched this error in ipyrad supporting documents.  It’s probably because one of your filtering parameters is too strict. And I have checked my *_consens directory. I don't know which data is unreasonable, how to adjust my filtering parameters.
This is my s5_consens_stats.txt  and parameter file
![x9ki0v h3o9kw65 9_miei7](https://user-images.githubusercontent.com/31763354/52831754-bfe1e100-3110-11e9-9402-e837f6ff5c41.png)
![x4aa4xwvn 7alrfrgs o2j](https://user-images.githubusercontent.com/31763354/52831774-d5570b00-3110-11e9-8e56-3b07a5784390.png)
Looking forward to your help

**Comment by isaacovercast** [comment]
Fixed in 0.7.30
