### ISSUE TITLE
Export SNP alignment from tetrad?

### ISSUE THREAD

**Issue by johngphillips** [dereneaton/ipyrad#329]
Sorry if this is not the place for such a comment, I'm new to Github.

I am running tetrad on snps output from ipyrad. While I am of the understanding that tetrad is randomly selecting one SNP per locus, I am only able to figure out how to get the output tree, not the alignment used to create said tree. Is it possible to get this SNP alignment?

I would like to verify my topology by running the same data through some other methods with different models of evolution.

Thanks!
-John

**Comment by isaacovercast** [comment]
Hi John,
You're right that this is not the best place for the comment, but welcome to the ipyrad community! There's actually [an ipyradgitter channel](https://gitter.im/dereneaton/ipyrad#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications) for questions, comments, and discussion just like this.

If i'm understanding your question correctly, it's not tetrad that is randomly sampling one snp per locus, it's ipyrad when it writes out the output files. The only thing tetrad does randomly internally (that would affect the alignment) is that it randomly resolves ambiguous bases. There's not really a good way to get these out from inside tetrad, that I'm aware of. If you want to follow up more please hop over to the gitter channel.
