### ISSUE TITLE
dfoil analyses with ipyrad

### ISSUE THREAD

**Issue by jferrerobiol** [dereneaton/ipyrad#337]
Hi Isaac,
I am working on introgression analyses using ipyrad. I was wondering if it is possible to perform dfoil analyses with ipyrad as I saw a comment on the baba.py script about the library scipy.stats that should be loaded for dfoil but I could not find any instructions in how to use it.

Thank you very much for your clarifications,
Joan

**Comment by isaacovercast** [comment]
Did you check out the [D-statistics testing jupyter notebook](https://nbviewer.jupyter.org/github/dereneaton/ipyrad/blob/3992e3232082ef9a7d0970cc73dd339551617df9/tests/dstats.ipynb)? I haven't used this in a while, so no promises, but it would be a good place to start.

A better place for quick questions like this in the future is the [ipyrad gitter channel](https://gitter.im/dereneaton/ipyrad), feel free to hop on and join the conversation, more people monitor the chat than the github issues in the repo.
