### ISSUE TITLE
Update ipyrad STRUCTURE notebook with new argument names

### ISSUE THREAD

**Issue by ricoperdiz** [dereneaton/ipyrad#338]
Dear ipyrad authors,

First, congratulations for this awesome tool. Well done!

I've been trying to run ipyrad STRUCTURE notebooks <http://nbviewer.jupyter.org/github/dereneaton/ipyrad/blob/master/tests/cookbook-structure-pedicularis.ipynb> and I had few problems, until I realized that some attributes and/or arguments from few ipyrad analysis module  functions had their names changed. For example, attribute "structure" does not have anymore an argument named "data"; now it is strfile (according to structure.py); and there is not anymore an attribute named "run", it was substituted by "submit_structure_jobs". 

I think other users may be having trouble with this.

I'm using module versions cited below:

ipa 0.6.18
toyplot 0.18.0

At last, congratulations again. It's been helpful to a lot of people.

Best,

Perdiz

**Comment by isaacovercast** [comment]
fixed. sorry for the delay.
