### ISSUE TITLE
hotfix - merge forcing project_dir to ./

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#340]
merging assemblies in the hotfix branch forces project_dir to be ./ which is annoying if that's not where you want it to live. I think it would make more sense to inherit project_dir from the first of the merged assemblies. Guaranteed to keep all the assemblies in the same place. Maybe it's just me, but i tend to have my params files in a different directory than ./ when doing assemblies.

**Comment by eaton-lab** [comment]
agreed, inherit sounds right.

**Comment by isaacovercast** [comment]
This has been fixed for a long time.
