### ISSUE TITLE
v0.9 - Write unlinked formats

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#343]
Output formats with unlinked snps would be useful for people, I think. Some people won't want to mess with analysis tools to get the unlinked snps, even though this is the best way to do it. If it's easy to write out unlinked as well that would be good.

**Comment by eaton-lab** [comment]
usnps is back.

**Comment by isaacovercast** [comment]
Question: Is it better to have the ustr file use the same snps as the usnps file or is it better to have the codebase be cleaner and more consistent, and have the ustr file include different snps? I'm thinking a  write_ustr() function patterned after write_usnps(), but the random sample of snps would be different. I can see this being confusing for people.

**Comment by isaacovercast** [comment]
Fixed - aba941c

**Comment by isaacovercast** [comment]
I added write_ustr and write_ugeno calls inside the write_usnps function, which passes in the subsampled snp array, so that all the *.u* files have the same subset of snps.
