### ISSUE TITLE
Ipyrad issue when using reference genome

### ISSUE THREAD

**Issue by mataman2017** [dereneaton/ipyrad#344]
Dear all, 

I am getting an error when running ipyrad with the reference genome. It worked well with the same parametres but running it de novo. It seems that in step 3 it completes correctly the following phases: indexing reference(100%), the dereplicating(100%), mapping (98%), fetch mapped reads (98-100%).

The problem is that it can't find the "filename_chunk_0.ali" which I assume that it is an intermediate file stored in the putative intermediate directory "directoryname_tmpalign".

The **slurm file:**
...
  [####################] 100%  fetch mapped reads    | 0:01:00  ERROR:ipyrad.core.assembly:IOError([Errno 2] No such file or directory: '/wrk/salajavi/ipyrad/prova3/prova3-tmpalign/Pieris_CGATGT_S2_L001001_Pnapibal_RVcoll17F995_alb_chunk_0.ali')
ERROR:ipyrad.core.assembly:shutdown warning: [Errno 3] No such process

  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
IOError([Errno 2] No such file or directory: '/wrk/salajavi/ipyrad/prova3/prova3-tmpalign/Pieris_CGATGT_S2_L001001_Pnapibal_RVcoll17F995_alb_chunk_0.ali')
warning: error during shutdown:
[Errno 3] No such process

**The log file:**
...
 Begin run: 2019-05-29 00:32
  Using args {'preview': False, 'force': False, 'threads': 2, 'results': False, 'quiet': False, 'merge': None, 'ipcluster': None, 'cores': 24, 'params': 'params-prova3.txt', 'branch': None, 'steps': '1234567', 'debug': False, 'new': None, 'download': None, 'MPI': True}
  Platform info: ('Linux', 'c657', '2.6.32-642.15.1.el6.x86_64', '#1 SMP Wed Oct 3 15:38:52 EEST 2018', 'x86_64')2019-05-29 01:43:37,766 	pid=12392 	[assembly.py]	ERROR 	OSError([Errno 2] No such file or directory: '/wrk/salajavi/ipyrad/prova3/prova3-tmpalign/Pieris_ATCACG_S1_L001001_Pnapi_RVcoll11G668_kaz_chunk_4.ali')
2019-05-29 01:43:37,917 	pid=29273 	[cluster_within.py]	ERROR 	Error in reconcat [Errno 2] No such file or directory: '/wrk/salajavi/ipyrad/prova3/prova3-tmpalign/Pieris_CGATGT_S2_L001001_Pnapi_RVcoll09V598_spa_chunk_0.aligned'
2019-05-29 01:54:26,426 	pid=20519 	[assembly.py]	ERROR 	IOError([Errno 2] No such file or directory: '/wrk/salajavi/ipyrad/prova3/prova3-tmpalign/Pieris_CGATGT_S2_L001001_Pnapibal_RVcoll17F995_alb_chunk_0.ali')
2019-05-29 01:54:27,591 	pid=20519 	[assembly.py]	ERROR 	shutdown warning: [Errno 3] No such process

Any ideas? I checked the paths and the params file many times. Could it be due to the nature of the genome file (unpublished yet)?

Thank you!

**Comment by isaacovercast** [comment]
I highly doubt the reference genome format is causing this issue. More
likely is resource allocation. The reference mapping step uses
significantly more disk space for temporary files. Have you checked to make
sure you aren't running out of disk? I'll bet that's the problem.

**Comment by mataman2017** [comment]
Hi Issac,
Thank you for the tip. I have submitted the job with memory-per-cpu. I'll keep you updated on its succes.

**Comment by mataman2017** [comment]
Thank you! that seemed to be the problem. Issue solved!

**Comment by isaacovercast** [comment]
Nice! Thanks for letting me know. Glad it worked.
