### ISSUE TITLE
'module' object has no attribute 'bucky'

### ISSUE THREAD

**Issue by yexiaying** [dereneaton/ipyrad#346]
I have install bucky using conda as you inferred in 'Cookbook for running BUCKy in parallel in a Jupyter notebook' and import it, but I still got the error informattion
import ipyrad as ip
import toytree
import ipyrad.analysis as ipa
import ipyparallel as ipp
ipyclient = ipp.Client()

c = ipa.bucky(name="buckytest",
             data="/ds3200_1/users_root/lidezhu/yexiaying/newassembly/alldata_outfiles/alldata.loci",
             workdir="analysis-bucky",
              samples=samples,
              minsnps=0,
             )

AttributeErrorTraceback (most recent call last)
<ipython-input-9-a34ceeb6c861> in <module>()
----> 1 c = ipa.bucky(name="buckytest",
      2              data="/ds3200_1/users_root/lidezhu/yexiaying/newassembly/alldata_outfiles/alldata.loci",
      3              workdir="analysis-bucky",
      4               samples=samples,
      5               minsnps=0,

AttributeError: 'module' object has no attribute 'bucky'

What do you think the cause of this problem?

**Comment by isaacovercast** [comment]
ipyrad version?

Something is wrong with your install or you are using an old version. Did you try reinstalling?

**Comment by ricoperdiz** [comment]
I'm having similar issue. I've tried reinstalling, also did a fresh install. My ipyrad  version now is 0.6.27. When I try to run `conda install -c ipyrad bucky`, I receive the following message:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - bucky
```

Any idea?

**Comment by isaacovercast** [comment]
Update to the newest version of ipyrad (0.7.30) `conda install -c ipyrad ipyrad -f`. What happens if you try this?

**Comment by ricoperdiz** [comment]
I've just seen on gitter that it looks like that OSX version is not available yet. And I'm running on Mac OS X. I forgot telling you this. 

Anyway, I tried and, as expect after reading gitter messages, it remained on version `0.6.27`.

Thank you.

R.

**Comment by isaacovercast** [comment]
OSX version should be up to date:
[image: image.png]

What did you try exactly and what was the exact result?

**Comment by ricoperdiz** [comment]
Hi,

First, I tried updating conda, then updating ipyrad through commands below:

```
conda update conda
conda install -c ipyrad ipyrad
```

It did not work.

Then you proposed to force update using option `-f`. It also did not work.

Then I decided to remove miniconda from my computer, and make a new fresh install.

So I followed instructions from `https://ipyrad.readthedocs.io/installation.html`. The result was that I was not able to install ipyrad. I got the following error message:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ipyrad -> mpi4py

Current channels:

  - https://conda.anaconda.org/ipyrad/osx-64
  - https://conda.anaconda.org/ipyrad/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Any guess?

**Comment by isaacovercast** [comment]
The conda install failed because of a missing dependency (mpi4py). I fixed this and tested it so the `conda install -c ipyrad ipyrad` should work now.

**Comment by isgilman** [comment]
Hello all,

I know this is late, but I'm also having trouble finding the `bucky` conda package. I tried the steps above (force reinstall of `ipyrad`). I'm currently working with 

```bash
ipyrad                    0.9.54             pyh9f0ad1d_0    bioconda
```

and see the package on Anaconda Cloud, but can't find it when trying to install:

```bash
$ conda install -c ipyrad bucky
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - bucky

Current channels:

  - https://conda.anaconda.org/ipyrad/osx-64
  - https://conda.anaconda.org/ipyrad/noarch
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/osx-64
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/daler/osx-64
  - https://conda.anaconda.org/daler/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I've attached the environment information from `conda info` and `conda list` here: [phylo.conda.list.txt](https://github.com/dereneaton/ipyrad/files/4831606/phylo.conda.list.txt).

Thanks,
Ian

**Comment by isaacovercast** [comment]
There is only a linux build of bucky in the ipyrad conda repo. I am guessing you are on mac? If you install bucky by hand the ipyrad bucky analysis tool will find it.

**Comment by isgilman** [comment]
Ah, thanks Isaac, I misinterpreted your comment about the OS X update above. I'll try installing bucky from source and working it into ipyrad.

Thank you!
