### ISSUE TITLE
dear ipyrad support

### ISSUE THREAD

**Issue by huangl07** [dereneaton/ipyrad#348]
I install ipyrad from source code and get a version 7.30
but if I install ipyrad by conda,it get a version 9.10

which is the lastest?

and there are some difference by using the parameters. could you show me an example

**Comment by isaacovercast** [comment]
0.7.30 is latest stable. 0.9 is beta. This is not an issue with the code, but a simple question which is more appropriate for the gitter channel: https://gitter.im/dereneaton/ipyrad
