### ISSUE TITLE
Refseq mapping - PE todo list

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#35]
* How to handle variable insert size for PE? Need a good way to set the `-d` flag for bedtools (distance between reads). Should this be a user defined parameter? We could calculate max insert size from the real data? Right now it's a hard coded global in refmap.py: MAX_PE_DISTANCE=60
* Get the right `-l` flag for PE orientation. I think _pe_ is probably the right one.
 * For the simulated pairddrad and the sim_mt the orientation is `mp`, both in the same direction on the same strand. This is probably wrong for real data.

**Comment by isaacovercast** [comment]
* ~~Switch on samtools view for PE to output only reads with properly mapped pairs~~
* ~~`samtools bam2fq` output both reads to separate files?~~
* ~~Better handling when no reads map~~
 * If no reads map finalize_aligned_reads() bails out.
* ~~mapreads() preserve both original _R1.fq and _R2.fq files~~

**Comment by dereneaton** [comment]
Handling the insert size is an interesting problem. I assume setting too large of value decreases speed and accuracy. I would assume the insert could be larger than 60 in real data, but users will probably rarely know the correct value, so it would be nice to have either a very reliable hard coded value, or a good default that users rarely need to change (maybe using the hackers dict).

It's possible I screwed up the orientation in the simulated PEddRAD data. I'll have to check that out.

**Comment by isaacovercast** [comment]
Fixed
