### ISSUE TITLE
Step 4 fails with tuple index error while heterozygosity estimation

### ISSUE THREAD

**Issue by eikemq** [dereneaton/ipyrad#352]
Hi,

I get with some data, which were already analysed in a different setting a strange error during Heterozygosity estimation. In this analysis 162 samples (paired GBS) are included (in the folder the R1 and R2 files of another sample are still present but without the *.gz file ending I defined in the params file). My first thought of this error related to the `filter_adapters = 2` (as this is the main difference to the analysis run before) do not hold true as also with `filer_adapters = 0` the error still show up.
```
  [####################] 100% 0:00:21 | inferring [H, E]       

  Encountered an Error.
  Message: IndexError: tuple index out of range

  Parallel connection closed.
IndexErrorTraceback (most recent call last)<string> in <module>()
/user//miniconda2/lib/python2.7/site-packages/ipyrad/assemble/jointestimate.pyc in optim(data, sample)
    407     try:
    408         ## get array of all clusters data
--> 409         stacked = stackarray(data, sample)
    410 
    411         ## get base frequencies
/user//miniconda2/lib/python2.7/site-packages/ipyrad/assemble/jointestimate.pyc in stackarray(data, sample)
    337     try:
    338         cutlens[0] = len(data.params.restriction_overhang[0])
--> 339         cutlens[1] = maxlen - len(data.params.restriction_overhang[1])
    340     except TypeError:
    341         pass
IndexError: tuple index out of range
```
Any idea whats happening here?

all the best
eike

**Comment by eikemq** [comment]
Hi,
I tried some troubleshooting and got a new conda env setup with ipyrad 0.7.30 and all dependencies set up. With this the pipeline is not stuck at step 4 but got to step 6 and is still running. 

Now I am confused about the different versions, which are floating on anaconda (and which are not congruent with the github repo). There you can specify 0.9.11 and 0.9.12 as newest version, where did this come from and are these beta versions of a completely different branch/channel? Previoulsy I just updated my normal conda environment regularly and so endet up with ipyrad 0.9.11 and the described error.

all the best
eike

**Comment by isaacovercast** [comment]
0.7.30 is the current master version. The 0.9 versions are beta, which we will be switching to very soon. The ipyrad conda channel will continue to hold the 0.7 version, but the 0.9 branch will only use the bioconda channel.

Glad to hear step 4 works now. Step 6 is probably not 'stuck', it usually just takes a long time. This is part of the reason for the 0.9 version is we made this step much quicker.
