### ISSUE TITLE
how to convert python 2 to python 3 when using ipyrad 0.9.12 in jupyter

### ISSUE THREAD

**Issue by yexiaying** [dereneaton/ipyrad#353]
I install the ipyrad 0.9.12 version using commands you provided in gitter. I activate the ipyrad_py3 environment and submit the jupyter job to the server. But when I open the jupyter notebook, the python version is still 2 and ipyrad version is 0.7.30, how can I convert it to 3 and using the ipyrad 0.9.12 version.

**Comment by isaacovercast** [comment]
This is more appropriate as a gittter conversation, as it is not an issue with ipyrad.
