### ISSUE TITLE
Step 2: Error in cutadapt

### ISSUE THREAD

**Issue by caranlove** [dereneaton/ipyrad#355]
Hi all, 

I am working with demultiplexed samples and am getting an error in step 2. 

> 2019-09-06 21:10:20,025 	pid=83157 	[rawedit.py]	DEBUG 	Entering cutadaptit_pairs - LG434_P8
2019-09-06 21:10:20,025 	pid=83157 	[rawedit.py]	WARNING 	  error adding barcodes info:     Barcodes file not found. You entered: 
2019-09-06 21:10:20,025 	pid=83157 	[rawedit.py]	DEBUG 	cutadapt -A XXX --trim-n --max-n 5 --minimum-length 30 -o /ante_edits/LG434_P8.trimmed_R1_.fastq.gz -p /ante_edits/LG434_P8.trimmed_R2_.fastq.gz LG434_P8_R1_.fq.gz LG434_P8_R2_.fq.gz
2019-09-06 21:10:24,144 	pid=83224 	[rawedit.py]	DEBUG 	Exiting cutadaptit_pairs - LG673_P8
 
My params is as follows: 
`------- ipyrad params file (v.0.7.30)-------------------------------------------
ante                           ## [0] [assembly_name]: Assembly name. Used to name output directories for assembly steps
./                             ## [1] [project_dir]: Project dir (made in curdir if not present)
                               ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files
                               ## [3] [barcodes_path]: Location of barcodes file
./*fq.gz                       ## [4] [sorted_fastq_path]: Location of demultiplexed/sorted fastq files
denovo+reference               ## [5] [assembly_method]: Assembly method (denovo, reference, denovo+reference, denovo-reference)
./Ante_reference.fasta         ## [6] [reference_sequence]: Location of reference sequence file
pairddrad                      ## [7] [datatype]: Datatype (see docs): rad, gbs, ddrad, etc.
CTAGC,AATTC                    ## [8] [restriction_overhang]: Restriction overhang (cut1,) or (cut1, cut2)
5                              ## [9] [max_low_qual_bases]: Max low quality base calls (Q<20) in a read
33                             ## [10] [phred_Qscore_offset]: phred Q score offset (33 is default and very standard)
6                              ## [11] [mindepth_statistical]: Min depth for statistical base calling
6                              ## [12] [mindepth_majrule]: Min depth for majority-rule base calling
10000                          ## [13] [maxdepth]: Max cluster depth within samples
0.85                           ## [14] [clust_threshold]: Clustering threshold for de novo assembly
0                              ## [15] [max_barcode_mismatch]: Max number of allowable mismatches in barcodes
0                              ## [16] [filter_adapters]: Filter for adapters/primers (1 or 2=stricter)
30                             ## [17] [filter_min_trim_len]: Min length of reads after adapter trim
2                              ## [18] [max_alleles_consens]: Max alleles per site in consensus sequences
5, 5                           ## [19] [max_Ns_consens]: Max N's (uncalled bases) in consensus (R1, R2)
8, 8                           ## [20] [max_Hs_consens]: Max Hs (heterozygotes) in consensus (R1, R2)
4                              ## [21] [min_samples_locus]: Min # samples per locus for output
20, 20                         ## [22] [max_SNPs_locus]: Max # SNPs per locus (R1, R2)
8, 8                           ## [23] [max_Indels_locus]: Max # of indels per locus (R1, R2)
0.5                            ## [24] [max_shared_Hs_locus]: Max # heterozygous sites per locus (R1, R2)
0, 0, 0, 0                     ## [25] [trim_reads]: Trim raw read edges (R1>, <R1, R2>, <R2) (see docs)
0, 0, 0, 0                     ## [26] [trim_loci]: Trim locus edges (see docs) (R1>, <R1, R2>, <R2)
p, s, v                        ## [27] [output_formats]: Output formats (see docs)
    ## [28] [pop_assign_file]: Path to population assignment file
`

And I am running v.0.7.30 and cannot seem to determine how to remedy the issue. As these samples come from various different plates I need to work with demultiplexed samples from stacks and then bring them into ipyrad. Does anyone have any ideas?
Thanks for the help!

**Comment by isaacovercast** [comment]
Did you resolve this issue? What was the problem?
