### ISSUE TITLE
(0.6.27) Step 7 error in introductory tutorial

### ISSUE THREAD

**Issue by AlexaDiNicola** [dereneaton/ipyrad#357]
Hello all,

I'm just learning to use ipyrad, but I've run into a bit of a problem while running through the [introductory tutorial](https://ipyrad.readthedocs.io/tutorial_intro_cli.html). Everything goes great right up to step 7, where I get the ValueError mentioned in the FAQs. I'm using the default params, which the tutorial implies should work fine, and increasing parameter permissiveness has had no effect so far.

The error, for the record, is as follows:
> error in filter_stacks on chunk 0: ValueError(zero-size array to reduction operation maximum which has no identity)

I've attached two of the param files I've been using (the default and the least-restrictive version yet, both of which hit this problem). Also attached is the output and logs from the last two times I ran this thing, once with each of the attached params.

Ordinarily I'd assume this was user error, but given that this is the data from the sample file downloaded through an official tutorial, I'm stumped. Thanks in advance for your help untangling this!

Params: [params-test_default.txt](https://github.com/dereneaton/ipyrad/files/3607549/params-test_default.txt) & [params-test_permissive.txt](https://github.com/dereneaton/ipyrad/files/3607550/params-test_permissive.txt)
Logs: [test_default-run-20190911.txt](https://github.com/dereneaton/ipyrad/files/3607551/test_default-run-20190911.txt), [test_permissive-run-20190911.txt](https://github.com/dereneaton/ipyrad/files/3607552/test_permissive-run-20190911.txt), & [ipyrad_log.txt](https://github.com/dereneaton/ipyrad/files/3607554/ipyrad_log.txt)

**Comment by AlexaDiNicola** [comment]
Welp, that fixed it quite neatly. Thank you! I wonder why the standard install command (`conda install -c ipyrad ipyrad`) got me an old version, though. I even tried to update it a couple times; it always behaved as though 0.6.27 was the current version. Is *that* a known issue?

In case it's relevant, I'm using Terminal in Mac OS Mojave 10.14.5 with Anaconda 4.7.11 and Python 2.7.16 (Python 3.6.8 in my base environment; Python 2 is in the ipyrad-specific conda environment).

**Comment by isaacovercast** [comment]
Yeah there's some kind of version collision with one of the dependencies which causes this, it's annoying I know. I haven't wanted to waste a bunch of time debugging it because we're moving to a new ipyrad version (0.9) which is python3 compatible. Sorry for the trouble, glad it got sorted out.

**Comment by AlexaDiNicola** [comment]
Thanks so much for the fix!
