### ISSUE TITLE
Problem when running tetrad : OSError(libmkl_rt.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by rancilhac** [dereneaton/ipyrad#360]
Hello,

I'm trying to run tetrad with ipyrad v 0.7.30 and toytree v 0.1.16, and I got the following error :

`(base) lois@lois-Precision-Tower-7810:~/Documents/Projects/Species_delimitation/RADseq/Discoglossus/assembly/Discoglossus_only/Step_2_accross_sample_t/in_95/tetrad$ tetrad -s disco_95.snps.phy -n test 

tetrad [v.0.7.30] (ipyrad.analysis toolkit)
Quartet inference from phylogenetic invariants

tetrad instance: test
loading seq array [26 taxa x 32879 bp]
inferring 14950 quartet tree sets
establishing parallel connection:
host compute node: [32 cores] on lois-Precision-Tower-7810
[####################] 100% generating q-sets | 0:00:04 |  
[                    ]   0% initial tree      | 0:00:00 |  
Unknown exception encountered: OSError(libmkl_rt.so: cannot open shared object file: No such file or directory)
(base) lois@lois-Precision-Tower-7810:~/Documents/Projects/Species_delimitation/RADseq/Discoglossus/assembly/Discoglossus_only/Step_2_accross_sample_t/in_95/tetrad$ 
`
I couldn't find the libmkl_rt.so file so either I did't look at the right place or it is not installed. Any idea on how to solve this problem ?

**Comment by isaacovercast** [comment]
Looks like a bad conda config. Try: `conda install mkl`

**Comment by rancilhac** [comment]
worked fine, thank you very much.
