### ISSUE TITLE
v0.9 - 'jupyter' not coming down as a dependency during bioconda install

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#362]
`conda install jupyter` fixes it. Is this on purpose?

**Comment by dereneaton** [comment]
Yes, I removed it from conda. I had a revelation and now I lean philosophically towards atomizing dependencies, meaning that b/c we don't **need** jupyter to run ipyrad we shouldn't make it a dependency. The new docs **recommend** installing jupyter as an additional install command though. I like it this way. I'm working on pushing the new docs today by the way!
