### ISSUE TITLE
Feature Request: sanples with different ploidy levels in same analysis

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [dereneaton/ipyrad#365]
We are several plant systematicists working on a range of non-model groups including Ranunculus and Salix, both of which show a range of ploidy levels in closely related species. 
We would like to see ipyrad being able to handle assemblies with taxa of different ploidy levels. (Currently, we run steps 1-5 separately for the ploidy levels, then merge the projects for steps 6-7, as per your advice, Deren and Isaac. But this is suboptimal). 
Ideally, ipyrad would be able to take a file(?) with the ploidy level per sample as input (similar to the population file) and select values for e.g. max_alleles and max_het accordingly. Do you think that is possible? 

Anyway, thank you for all the hard work you put into ipyrad. It made many lifes much easier.

Kevin, Natascha, and Claudia (account-holder) from Germany

**Comment by eaton-lab** [comment]
Hi Claudia, 

We do not plan to support a separate ploidy argument. The branching workflow works quite well to accomplish this. Please let me know if I can provide any further help in implementing it. An example outline is below. 

```bash
# run all samples up to step 3
ipyrad -p params-all-samples.txt -s 123

# branch to create a polyploid and diploid assembly by giving text file with names
ipyrad -p params-all-samples.txt -b diploids diploids.txt
ipyrad -p params-all-samples.txt -b polyploids polyploids.txt

# run each assembly through the base calling steps
ipyrad -p params-diploids.txt -s 45
ipyrad -p params-polyploids.txt -s 45

# merge them back together
ipyrad -m postmerge params-diploids.txt params-polyploids.txt

# finish assembly
ipyrad -p params-postmerge.txt -s 67
```

**Comment by linghu114** [comment]
Hi Eaton,

I have been using ipyrad to analyze a mixed group of diploids and polyploids. I have two separate questions that you might be able to help answer:

1. As in your reply to Claudia above, when running diploids vs. polyploids assemblies through steps 45, which parameters should be different? Should the [18] [max_alleles_consens] be set to the highest ploidy level in polyploids? 

3. There are mindepth and maxdepth values for base calling. Are we able to find this depth information in any result file? I have been looking to check this.

Thank you!

**Comment by isaacovercast** [comment]
Hello,

1. If you are running diploid and polyploid data together the value of max_alleles_consens will be the most important. Setting this to the highest ploidy level is one strategy, though I have never tried this myself.

2. Average depth values are reported in the s3 stats file in the _clust directory and also in the final stats file in the _outfiles directory after step 7.

Hope that helps!
-isaac

**Comment by isaacovercast** [comment]
Hi @MarekSlenker,
During step 5 we use a diploid model for calling genotypes, so the exact ploidy information for each sample is collapsed to diploid basecalls per SNP. Because of this you will see the 0/0 format in the vcf. This is the best we can do at the moment, and people who have used ipyrad for mixed ploidy have had reasonable success getting meaningful results. Let me know if you have other questions.
