### ISSUE TITLE
Step 3 fails for FASTQ+64 formatted data

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#368]
FASTQ+64 files apparently don't work anymore:

![image](https://user-images.githubusercontent.com/5974975/68128842-c6bbb880-ff18-11e9-8389-e0a669b19cd5.png)

Fails during step 3 with:
```
Fatal error: FASTQ quality value (70) above qmax (41)
By default, quality values range from 0 to 41.
To allow higher quality values, please use the option --fastq_qmax 70
```

Not sure when this stopped working but it could have been a while ago. I _thought_ that cutadapt used to modify the quality score values based on the Phred_qscore_offset parameter, but it definitely isn't, and then vsearch is complaining downstream. 

Related: https://github.com/torognes/vsearch/issues/194

The fix is to set `--fastq_qmax` and `--fastq_qmin` based on the offset value, and it'll have to be done for all the vsearch calls in step 3, I think.

**Comment by eaton-lab** [comment]
Don't we usually hand in derep'd data to vsearch where the scores are gone..., maybe this is only coming up in data sets that are doing pair-merging?

**Comment by isaacovercast** [comment]
Confirmed. This only happens for paired data. I tested with the sim data
and SE with fasq+64 qscores works fine. It dies during pair-merging, good
call.

**Comment by eaton-lab** [comment]
Another person just ran into this bug. I'm gonna set the merge qmax to 100 and see if it fixes .

**Comment by isaacovercast** [comment]
I did this. Testing the fix in v.0.9.49.

**Comment by isaacovercast** [comment]
This is fixed. qmax is set to 93 in merge_pairs_with_vsearch to allow fastq+64 formatted data.
