### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by brpark29** [dereneaton/ipyrad#370]
Hello! I have been happily using iPyrad for a long time, and was wondering if it would be possible to update the documentation. I know there have been some significant re-writes, and would like to get a firmer handle on the changes that have been implemented post v 0.7.xx. Thank you!

**Comment by isaacovercast** [comment]
Hi Brian,
The documentation that is live on the rtd site should be 100% correct for
the current version. It's not complete, as there's still some stuff we
haven't gotten around to, but it's probably 90% complete. Is there
something specific you'd like to have better documented?

**Comment by brpark29** [comment]
Ah, got it! I was a bit unsure of the order of operations for when the different tools like bedtools were being used in the reference pipeline, but I dug through the source code and was able to figure it out. Thank you!
