### ISSUE TITLE
insert size hackersonly override

### ISSUE THREAD

**Issue by eaton-lab** [dereneaton/ipyrad#372]
Currently it seems that the hackersonly max_insert_size arg is only used if it fails to estimate the insert size from the data itself. We should change it so that if the user sets a hacker value then it overrides the estimated value. 

Sandra and I are doing some testing on a digested genome with known size selection mapped back to the genome and it seems we are throwing away a fair number of read pairs b/c of the max_insert_size.

**Comment by isaacovercast** [comment]
Near as I can tell this was fixed some time ago.
