### ISSUE TITLE
Unbound local error

### ISSUE THREAD

**Issue by MarnusStoltz** [dereneaton/ipyrad#381]
Hi there,

Getting the following error when trying to sort reads
------------------------------------------------------------
  [                    ]   0% 0:00:03 | sorting reads        
  [                    ]   0% 0:00:03 | sorting reads        
  Encountered an Error.
  Message: UnboundLocalError: local variable 'barcode' referenced before assignment
  Use debug flag (-d) for full code traceback.

  Parallel connection closed.
------------------------------------------------------------

Is there an obvious reason for this?

Regards
Marnus

[params-robins.txt](https://github.com/dereneaton/ipyrad/files/4051487/params-robins.txt)

**Comment by isaacovercast** [comment]
What version of ipyrad are you running? Can you do this "Use debug flag
(-d) for full code traceback." and post the full error message text?

**Comment by isaacovercast** [comment]
Also, in your params file you need to specify the restriction_overhang
sequence (#8) also you have "p,s,1" as output_formats, but '1' is not
a valid output format, see the docs for a list of available formats.

**Comment by isaacovercast** [comment]
Also, can you post the first 10 lines of your barcodes file?

**Comment by isaacovercast** [comment]
All good? If not please comment and reopen this issue.
