### ISSUE TITLE
mrbayes install UnsatisfiableError

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#384]
mrbayes will not install in the current configuration. I tested this in both python 2.7 and python 3.6/3.7. In a clean conda env run `conda install -c bioconda ipyrad -y`, then run `conda install -c bioconda mrbayes -y` and it will spin for a while and eventually fail to solve the dependency problem. I _can_ get mrbayes to install from another channel (BioBuilds), but when you run `mb` it complains about libreadline ("mb: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory"), ipyrad installs readline 7.0 from the default channel (no readline in bioconda). I tried installing readline 8 by hand from conda-forge, and then installing mrbayes, which works, but then `mb` segfaults with an Illegal instruction error. What the heck?!?!

**Comment by isaacovercast** [comment]
If you do this it will install in a clean conda env: `conda install -c conda-forge -c bioconda ipyrad mrbayes`, but then when you run `mb` you get:
```
Illegal instruction (core dumped)
```

**Comment by isaacovercast** [comment]
A workaround: `sudo apt-get install mrbayes`, but this defeats the purpose of conda....

**Comment by eaton-lab** [comment]
What a pain. It seems the conda-forge install is working on some systems at least.

**Comment by isaacovercast** [comment]
This works now `conda install -c conda-forge -c bioconda ipyrad mrbayes`.

**Comment by isaacovercast** [comment]
Whoops, it's broken again (core dumped):
```
mrbayes                   3.2.7                h5465cc4_5    bioconda

```
