### ISSUE TITLE
Step 3 Fatal error: Files compressed with gzip are not supported

### ISSUE THREAD

**Issue by lz41** [dereneaton/ipyrad#389]
Hey all,

I was running step 3 in ipyrad and it gave out this error: 

"Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:03:01 | dereplicating          

  Encountered an Error.
  Message: IPyradError: 

Fatal error: **Files compressed with gzip are not supported**

  Use debug flag (-d) for full code traceback."

After i used debug flag, it gave the error in detail:
---------------------------------------------------------------------------IPyradError                               Traceback (most recent call last)<string> in <module>
/projects/spe1/software/miniconda3/lib/python3.7/site-packages/ipyrad/assemble/clustmap.py in dereplicate(data, sample, nthreads)
    760     errmsg = proc.communicate()[0]
    761     if proc.returncode:
--> 762         raise IPyradError(errmsg.decode())
    763 
    764 
IPyradError: 

Fatal error: Files compressed with gzip are not supported

**What i don't understand is that all the files i use are in .gz and step 1, step 2 went just fine.** 

**Anyone has insights on what's going on and how to fix it?**

Thanks!

**Comment by isaacovercast** [comment]
Looks like a stale conda environment. Try this:

conda install -c bioconda vsearch -f

I bet that'll fix it. You might have other problems though. did you install
ipyrad in a clean conda environment? Maybe you updated ipyrad and it didn't
update all the dependencies? Try installing in a clean environment as well,
that's guaranteed to work.

**Comment by isaacovercast** [comment]
All good? Reopen and comment if not.

**Comment by eaton-lab** [comment]
@lz41 Our conda recipe on bioconda now includes `zlib` (even though it is available by default on many systems), which when available will allow `vsearch` to read zipped files. So updating `ipyrad` should fix the problem if the directions above do not work.

**Comment by lz41** [comment]
Thanks! I tried to reinstall the conda environment and it looks like it works now!
