### ISSUE TITLE
cluster_across - maxlen hard coded, consider making this a global/parameter

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#39]
cluster_across.py line 98:

              maxlen = [225 if 'pair' in data.paramsdict["datatype"] else 125][0]

This maxlen value is used several times, and i think it should be easier/more explicit to configure, given that read lengths are highly variable and only still increasing (miseq can do 2x300bp). Seems like this wants to be a module level variable, or maybe even an assembly parameter, set once accessed everywhere. Makes it easier to change in the future. I recall we were talking about making a hackers only parameter dict, for advanced config, this seems like a good candidate. Any thoughts?

**Comment by dereneaton** [comment]
I agree. Hard coding it is probably sufficient for most data sets. And makes filling these arrays way way faster than if we used variable sized lists. But we should allow users to change it if needed. Alternatively we could make it quite large (5000) and simply trim (resize) to remove all of the empty columns at the end. It's a huge waste of memory, though. Again, a good candidate for the hackerzdict.

**Comment by isaacovercast** [comment]
I'm calling this 'max_fragment_length', so then
 
SE: maxlen = max_fragment_length
PE: maxlen = 2*max_fragment_length
