### ISSUE TITLE
Step#7 vcf file ValueError: invalid literal for int() with base 10: '43;*9'

### ISSUE THREAD

**Issue by jqrichmond** [dereneaton/ipyrad#397]
Hi Isaac,
I'm using ipyrad 0.9.41 and python 3.7 - getting an error in step 7 for building the vcf file.

Step 7: Filtering and formatting output files 
  [####################] 100% 0:00:06 | applying filters       
  [####################] 100% 0:00:03 | building arrays        
  [####################] 100% 0:00:03 | writing conversions    
  [####################] 100% 0:00:02 | indexing vcf depths    
  Encountered an Error.
  Message: ValueError: invalid literal for int() with base 10: '43;*9'

I've done multiple runs with different assemblies and get this error on all of them. The vcf file is literally the only file format I'm needing right now, otherwise I wouldn't bug you. Any ideas? Thank you. -Jonathan

**Comment by isaacovercast** [comment]
Hello Jonathan,
I fixed this yesterday, as a matter of fact. Pull down the newest version v0.9.42 and it'll work. Let me know how it goes.
-isaac

**Comment by jqrichmond** [comment]
Thanks dude. Much appreciated. I'll give it a whirl in a bit. -Jonathan

________________________________
