### ISSUE TITLE
can't run ABBA-BABA test in ipyrad

### ISSUE THREAD

**Issue by Bean061** [dereneaton/ipyrad#399]
Hi,
When I run this command, bb.run(ipyclient), following the tutorial in https://ipyrad.readthedocs.io/en/latest/API-analysis/cookbook-abba-baba.html, the error goes as follows. 
Looking forward to your reply. Thanks!

[                    ]   0% 0:00:04 |  calculating D-stats 

---------------------------------------------------------------------------
IPyradError                               Traceback (most recent call last)
<ipython-input-11-32c2210814a4> in <module>
----> 1 bb.run(ipyclient)

~/opt/anaconda3/lib/python3.7/site-packages/ipyrad/analysis/baba.py in run(self, ipyclient)
    168             An ipyparallel client object to distribute jobs to a cluster.
    169         """
--> 170         self.results_table, self.results_boots = batch(self, ipyclient)
    171 
    172         ## skip this for 5-part test results

~/opt/anaconda3/lib/python3.7/site-packages/ipyrad/analysis/baba.py in batch(baba, ipyclient)
    402                 if not asyncs[job].successful():
    403                     raise IPyradError(\
--> 404                         " error: {}: {}".format(job, asyncs[job].exception()))
    405                 ## enter results for successful jobs
    406                 else:

IPyradError:  error: 1: IndexError(list index out of range)

**Comment by isaacovercast** [comment]
What version of ipyrad are you running? If not using the most recent version please update and try again.

**Comment by isaacovercast** [comment]
I'm assuming updating to the newest version fixed this.
