### ISSUE TITLE
samtools or pysam?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#4]
We could package up samtools similar to vsearch, or we could pull in pysam as a requirement. I'm 50/50 here. Pysam is just a wrapper around the binary, but it pulls in all this crust and you have to build it at install time, AND a random build on one of my machines failed because the cython version was out of date. Seems easier and safer to use the binary... but i'm still deciding.

**Comment by dereneaton** [comment]
I'm all for choosing the most foolproof installation procedure when possible. Troubleshooting other peoples' installations is the worst. But if we want to use pysam we could require an up-to-date cython installation in setup.py or the conda recipe, right?

**Comment by isaacovercast** [comment]
Agreed. I'll bundle samtools binary as well, lower overhead.

**Comment by isaacovercast** [comment]
Samtools. I pulled fresh code from the git repo, built new binaries for linux and mac, copied them into the ipyrad/bin directory, and got a copy of the license too. I updated the assembly.py code to include this on the refseq branch. It seems to work fine.
