### ISSUE TITLE
step3: cannot copy sequence with size 142 to array axis with dimension 0 when build clusters with clustmap.py 

### ISSUE THREAD

**Issue by Liut035** [dereneaton/ipyrad#404]
Hi,

I've been troubling with a problem for several days. I would appreciate it if you could give me any advice.

I ran ipyrad v.0.9.52 with 164 individuals in total (~60GB) on campus research computing resources with 40 cores and 16gb memory-per-cpu. Pairgbs sequencing with demultiplexed fastq files and reference genome were used in my study. 

The error message is:
 Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:00:03 | indexing reference     
  [####################] 100% 0:35:02 | join unmerged pairs    
  [####################] 100% 0:10:10 | dereplicating          
  [####################] 100% 0:03:56 | splitting dereps       
  [####################] 100% 1 day, 13:36:51 | mapping reads          
  [####################] 100% 0:09:10 | building clusters      

  Encountered an Error.
  Message: ValueError: cannot copy sequence with size 142 to array axis with dimension 0
  Parallel connection closed.
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<string> in <module>
/apps/ipyrad/0.9.52/lib/python3.7/site-packages/ipyrad/assemble/clustmap.py in build_clusters_from_cigars(data, sample)
   2180                     seq = cigared(r1.seq, r1.cigar)
   2181                     start = r1.reference_start - reg[1]
-> 2182                     arr1[start:start + len(seq)] = list(seq)
   2183 
   2184                     seq = cigared(r2.seq, r2.cigar)
ValueError: cannot copy sequence with size 142 to array axis with dimension 0

The second step completed successfully, I don't think it is the reason for the error in third step. Anyhow, I attached part of "s2_rawedit_stats.txt" here.
reads_raw  trim_adapter_bp_read1  trim_adapter_bp_read2  trim_quality_bp_read1  trim_quality_bp_read2  reads_filtered_by_Ns  reads_filtered_by_minlen  reads_passed_filter
  2197908                 441184                  46955                 944289                 971583                     0                         0              2195933
  2717852                 555768                  56457                1181264                1185683                     0                         0              2715321
  2122250                 441998                  41471                 934200                 969245                     0                         0              2120437
  1269833                 241032                  26781                 515238                 543954                     0                         0              1268697
   961878                 167608                  19888                 374683                 393510                     0                         0               960959
  2967810                 534852                  61622                1170237                1259612                     0                         0              2964752

And in the params file, I only changed a few parameters, including:
[sorted_fastq_path]: absolute directory/*.fq.gz
[assembly_method]: reference
[reference_sequence]: absolute directory to the genome reference
[datatype]: pairgbs
[restriction_overhang]: CWGC,
[filter_adapters]: 2
[min_samples_locus]: 10
[trim_reads]: 13, 0, 8, 0
[output_formats]: *

I've been troubling with this problem whenever I try small datasets or large datasets, but I can't find the reason. Could you please give me some suggestions?

Thank you very much!

Tong

**Comment by isaacovercast** [comment]
There was an off-by-one error for PE reference assemblies. This is fixed in **v0.9.53** (ef5a74c), should be up on bioconda within a couple hours.

**Comment by Liut035** [comment]
Hi,


Thanks for the reply. I reran the ipyrad with same dataset and same parameter, and encountered another problem, here is the error message:

&nbsp;

&nbsp;ipyrad [v.0.9.52]
 
&nbsp; Interactive assembly and analysis of RAD-seq data
 
&nbsp;-------------------------------------------------------------&nbsp;
 
&nbsp; Parallel connection | c8a-s21.ufhpc: 28 cores
 
&nbsp;&nbsp;
 
&nbsp; Step 3: Clustering/Mapping reads within samples
 
&nbsp; [####################] 100% 0:00:03 | indexing reference&nbsp; &nbsp; &nbsp;
 
&nbsp; [####################] 100% 0:45:50 | join unmerged pairs &nbsp; &nbsp;
 
&nbsp; [####################] 100% 0:13:42 | dereplicating &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
 
&nbsp; [####################] 100% 0:05:05 | splitting dereps&nbsp; &nbsp; &nbsp; &nbsp;
 
&nbsp; [####################] 100% 2 days, 3:29:00 | mapping reads &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
 


 
&nbsp; Encountered an Error.
 
&nbsp; Message: IPyradError: b'[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes\nsamtools sort: truncated file. Aborting\n'
 
&nbsp; Parallel connection closed.
 
---------------------------------------------------------------------------IPyradError &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Traceback (most recent call last)<string&gt; in <module&gt;
 
/apps/ipyrad/0.9.52/lib/python3.7/site-packages/ipyrad/assemble/clustmap.py in mapping_reads(data, sample, nthreads, altref)
 
&nbsp;&nbsp; 1970 &nbsp; &nbsp; error3 = proc3.communicate()[0]
 
&nbsp;&nbsp; 1971 &nbsp; &nbsp; if proc3.returncode:
 
-&gt; 1972 &nbsp; &nbsp; &nbsp; &nbsp; raise IPyradError(error3)
 
&nbsp;&nbsp; 1973 &nbsp; &nbsp; proc2.stdout.close()
 
&nbsp;&nbsp; 1974&nbsp;
 
IPyradError: b'[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes\nsamtools sort: truncated file. Aborting\n'



Is it also an off-by-one error? Will it be fixed in v.0.9.53?


Thanks!
Tong
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Isaac Overcast"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上6:04
收件人:&nbsp;"dereneaton/ipyrad"<ipyrad@noreply.github.com&gt;;
抄送:&nbsp;"刘彤"<631115420@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [dereneaton/ipyrad] step3: cannot copy sequence with size 142 to array axis with dimension 0 when build clusters with clustmap.py  (#404)





 
There was an off-by-one error for PE reference assemblies. This is fixed in v0.9.53 (ef5a74c), should be up on bioconda within a couple hours.

**Comment by isaacovercast** [comment]
Well it says `truncated file`, so I'm going to guess that you ran out of disk space. Make sure you have lots and lots of free disk space. Step 3 generates a ton of intermediate files that you need room for.

**Comment by Liut035** [comment]
Do you think how much space I may need? My raw data is 60Gb, and after the second step I got a 50 Gb edits file, in the third step, the files seem can increase to more than 600 Gb.

Thanks

**Comment by isaacovercast** [comment]
It's hard to say exactly. 100x the size of the raw data should be a
comfortable upper bound. 10x the size of the raw data is probably not
enough.

**Comment by Liut035** [comment]
Got it. Thank you very much!
