### ISSUE TITLE
Step7 - progress tix

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#41]
notes on progress for step7 just to keep my head straight. Here "fixed" means assemble.write_outfiles.make_outfiles() has a function to call this, and the concordant file_conversion/loci2*.py file has been mod'd to suit.

- loci2phynex: fixed, needs testing
- loci2gphocs: ~~not~~ fixed, needs testing
- loci2SNP: ~~not~~ fixed, needs testing (also needs to resolve the 'seed' issue)
- loci2mig: ~~not~~ fixed, needs testing
- loci2treemix: ~~not~~ fixed, needs testing
- loci2vcf: ~~not~~ fixed, needs testing

~~Treemix relies on .usnps already being output. Maybe .snps/.usnps can be included in the "always output" category with .loci/.alleles/.vcf. Part of me just wants to write all possible output formats to the outfiles/ directory and just not ask, might save a lot of coding heartache for the cost of a few handfuls of cycles.~~ I updated the loci2treemix.make() function to test for .usnps file, if it doesn't find it it calls loci2SNP to make it, if _that_ fails, then it bails out.

**Comment by dereneaton** [comment]
Yeah, it makes sense to recycle the loci2* functions. For API users I think it would be good to make a vcf2loci function available as well, so users can come to ipyrad with data from other sources and use our conversion functions. This would open the door to more people to coming to ipyrad for downstream analyses. 

I don't think that making all formats by default is the right way to go. For super large analyses each output file might be 5-10 GB, and the amount of unnecessary files becomes too large. I'm down for increasing the number of defaults though.

**Comment by isaacovercast** [comment]
vcf2loci is probably a good idea. I'll put it on the stack (#43).

**Comment by isaacovercast** [comment]
Done enough.
