### ISSUE TITLE
Make later versions available in PyPI

### ISSUE THREAD

**Issue by davidlougheed** [dereneaton/ipyrad#412]
The latest version in PyPI is 4 years old and doesn't support Python 3. I'm running ipyrad on a machine where I do not wish to install conda; it works fine if I install it with

```
pip install git+https://github.com/dereneaton/ipyrad.git@0.9.56
```

but it would be nice to have it available in the repository.

**Comment by isaacovercast** [comment]
Thanks for the suggestion. Conda is our main supported install mechanism, and while it might seem easy to maintain install ability from multiple sources it can actually be a little bit of work, so we prefer to stick with conda. Your pip install like for github seems useful, so I added this to the ipyrad install documentation.
