### ISSUE TITLE
Merge exists with 1

### ISSUE THREAD

**Issue by miguelpmachado** [dereneaton/ipyrad#415]
Hi everyone,
I'm trying run ipyrad with different conditions, but when I try merging them, the merge command always exists with 1 although it seems to worked (I think is related with this [line](https://github.com/dereneaton/ipyrad/blob/6934462c4a1631a97cf788bdaa945b13ed13cdf1/ipyrad/__main__.py#L330)).
Is there any reason for this behaviour? I'm asking because this is breaking my script.
Thanks for your attention.
Best regards,
Miguel

**Comment by isaacovercast** [comment]
Huh, that's weird. Thanks for tracking down the exact behavior in the code. I changed this to return 0 on successful merging. You can clone the repository or wait until the next ipyrad version goes up to bioconda.
