### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by gubrins** [dereneaton/ipyrad#418]
Good afternoon,
I was happily working with Ipyrad until, accidentally, I removed my miniconda folder from my account. Since yesterday, I've been trying by all the means to reinstall ipyrad but I don't know why nothing is working for me. I was follwing the guidelines (https://ipyrad.readthedocs.io/en/latest/3-installation.html) and, after installing Miniconda3, when I try to install Ipyrad, it tells me that conda is using Python 3.8 but Ipyrad only accepts version 2.7. 
To solve that, I downloaded Miniconda2, which has python 2.7. After running again the command to install ipyrad (conda install ipyrad -c conda-forge -c bioconda), it stays for ages trying to install the program (it says solving the environment), and nothing happens. Do you have any idea of what is going on? 

Thanks in advance!

**Comment by isaacovercast** [comment]
There is currently a problem with the 3.8 installation. You can install ipyrad in a python 3.7 environment

conda create -n ipyrad_37 python=3.7

Then activate and do the install as normal.
