### ISSUE TITLE
baba Error - "error: {}: {}".format(job, asyncs[job].exception()))

### ISSUE THREAD

**Issue by btmartin721** [dereneaton/ipyrad#420]
Hello. I am having an issue with the ABBA-BABA tests. I get the below error when I run the attached jupyter notebook. I'm not sure if this is an issue with my input data, with ipyparallel, or something else. The ipyclient is running and says I have 4 engines. One thing I thought of was that I generated the .loci file in ipyrad 0.7.28, but am running baba in ipyrad 0.9.57 (I have also tried ipyrad v0.9.51). 

I've tried manually specifying the tests as well as using the generate_tests function, but get the same error.

Has the .loci file format changed since 0.7.28? Or do you know what else might be wrong? 

If you want me to, I can send you the .loci file privately.

Thanks for your time.

[abba-baba_test (2).zip](https://github.com/dereneaton/ipyrad/files/5144702/abba-baba_test.2.zip)

```
# Error below
aa.run(ipyclient)

[                    ]   0% 0:00:32 |  calculating D-stats 

---------------------------------------------------------------------------
IPyradError                               Traceback (most recent call last)
<ipython-input-13-48b12d0cf6cf> in <module>
      1 ## run all tests
----> 2 aa.run(ipyclient)

~/anaconda3/envs/baba_ipyrad/lib/python3.7/site-packages/ipyrad/analysis/baba.py in run(self, ipyclient)
    168             An ipyparallel client object to distribute jobs to a cluster.
    169         """
--> 170         self.results_table, self.results_boots = batch(self, ipyclient)
    171 
    172         ## skip this for 5-part test results

~/anaconda3/envs/baba_ipyrad/lib/python3.7/site-packages/ipyrad/analysis/baba.py in batch(baba, ipyclient)
    402                 if not asyncs[job].successful():
    403                     raise IPyradError(\
--> 404                         " error: {}: {}".format(job, asyncs[job].exception()))
    405                 ## enter results for successful jobs
    406                 else:

IPyradError:  error: 3: IndexError(list index out of range)  

```

**Comment by isaacovercast** [comment]
I can't reproduce the error. Can you share your loci and newick files with me?

**Comment by btmartin721** [comment]
Hi Isaac,

I emailed you my loci, newick, and popmap files. 

Thank you for looking into this.

-Bradley

**Comment by isaacovercast** [comment]
Result of a malformed loci file. There was a blank line inserted somewhere deep within at the head of a random locus. This loci file was from an older version of ipyrad. I think it's safe to assume that the loci file is well formed in the vast majority of cases, so I just added some exception handling here to do a better job reporting the problem.

Thanks for reporting the issue.

**Comment by btmartin721** [comment]
Oh man. It ended up being such a simple issue haha. I was able to get it to run after removing the blank line. Perhaps the blank line was introduced by my OS; not sure how it got there. Thank you so much for your help! 

-Bradley

**Comment by isaacovercast** [comment]
No problem. Good luck!
