### ISSUE TITLE
Problem with demultiplexing of 3RAD dataset

### ISSUE THREAD

**Issue by ludmilasromek** [dereneaton/ipyrad#424]
Hello all,

I think there is a problem with demultiplexing step in ipyrad where there are two inline barcodes. I don't know what's going on, but I got very diffrent numbers of reads for some of the barcodes when I compared results from ipyrad and process_radtags from Stack, e.g
ipyrad: 
sample_name                            total_reads
EY_164                                        6558
sample_name                               true_bar       obs_bar     N_records
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TCGGTACC            46
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TAGGTACC           804
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TCGATACC           697
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TCGTTACC           490
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+GCGGTACC             1
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TTGGTACC           497
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TCTGTACC           424
EY_164                               AGCGTTGAT+TCGGTACC AGCGTTGAT+TCAGTACC          2535
process_radtags:
Barcode	Filename	Total	NoRadTag	LowQuality	Retained
AGCGTTGAT-TCGGTACC	EY_164	3131244	17825	922	3112497

It was ipyrad-0.9.55: datatype: pair3rad, 1 mismatch in barcode. Stack command: 
process_radtags -P -p ./raw_reads_Plate01 -b ./barcodes_plate01_stack.txt -o ./demultiplexed_stack_plate01/ -c -q -r --inline_inline --renz_1 mspI --renz_2 bamHI

**Comment by isaacovercast** [comment]
Is it true that all of these are the same sample? Why are the sample names the same? Were there other samples that returned a more reasonable number of reads?

**Comment by ludmilasromek** [comment]
Yes, that's all reads for this sample. I sent you by e-mail full results files.

**Comment by isaacovercast** [comment]
I never received an email. Can you try again?

**Comment by isaacovercast** [comment]
Ok, well here's a weird clue. For the ipyrad demux process _ALL_ the samples with barcode 2 sequence TCGGTACC failed in this same way (109, 110, 133, 134, 142, 164, 211, & 258) with very very few reads recovered. This is highly suspicous, but I haven't figured out the problem yet. Never seen this before....

**Comment by ludmilasromek** [comment]
I think that something is going wrong with entire demultiplexing step, not only with one barcode - when I looked on final results I recovered my three species, but there is too many hybrid individual to be likely (both when I allow and do not allow 1 mismatch in barcode).

**Comment by isaacovercast** [comment]
Did you ever make progress on this? Can you try updating to the most recent version of ipyrad and running this again?

**Comment by isaacovercast** [comment]
Fixed in 3b6dbea
