### ISSUE TITLE
baba analysis plotting in v0.9 is broken

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#425]
That's it. It doesn't work. Sending people back to use the 0.7 version is becoming increasingly unfeasible.

**Comment by eaton-lab** [comment]
ugh, I have huge updates for tons of the tools, including a working baba --  just need to find time to finish the tutorials. Raising on my TODO list.

**Comment by zelongnie** [comment]
The toytree is installed in the same environment, but ipyrad always produces the same error as below.

>>> import ipyrad.analysis as ipa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/NZL/miniconda3/envs/python2/lib/python2.7/site-packages/ipyrad/analysis/__init__.py", line 18, in <module>
    from .structure import Structure as structure
  File "/Users/NZL/miniconda3/envs/python2/lib/python2.7/site-packages/ipyrad/analysis/structure.py", line 12, in <module>
    from ipyrad.analysis.tetrad import get_spans
  File "/Users/NZL/miniconda3/envs/python2/lib/python2.7/site-packages/ipyrad/analysis/tetrad.py", line 67, in <module> """)
  File "/Users/NZL/miniconda3/envs/python2/lib/python2.7/site-packages/ipyrad/assemble/util.py", line 52, in __init__
    raise IPyradError(*args, **kwargs)
ipyrad.assemble.util.IPyradError:
    Error: tetrad requires the dependency 'toytree', which we haven't yet
    included in the ipyrad installation. For now, you can install toytree
    using conda with the following command:
    conda install toytree -c eaton-lab

**Comment by ksil91** [comment]
Just came here to open this issue! Finishing up a cool hybridization project using the API that I'd like to round out with the ABBA-BABA plot. Is there a way to get the plot now from an analysis done with v0.9.6 (Python3)?

**Comment by eaton-lab** [comment]
Hi @ksil91 and others,

There is an updated documentation notebook here [https://github.com/dereneaton/ipyrad/blob/master/testdocs/analysis/cookbook-baba-ipcoal.ipynb](https://github.com/dereneaton/ipyrad/blob/master/testdocs/analysis/cookbook-baba-ipcoal.ipynb) which also includes simulations to confirm it is working accurately.

This uses ipyrad v0.9.57+ and toytree v2+. The notebook has conda installation instructions at the top.

This is part of the new documentation that is under development. Please let me know if you encounter any problems.

Deren

**Comment by isaacovercast** [comment]
Works as of these versions:
![image](https://user-images.githubusercontent.com/5974975/102273955-6e305a80-3f23-11eb-89b1-3456df7c7870.png)
