### ISSUE TITLE
Expected time for step 3?

### ISSUE THREAD

**Issue by rspfau** [dereneaton/ipyrad#426]
I'm running step 3 on 44 cores (128G memory):
ipyrad -p params-Gtex.txt -s 3 -c 44

And it's been running for over three hours but still says 0% progress. There are only 12 samples, ranging between 1 and 2 million reads per sample.

Should I be concerned? 

![ipyrad clustering mapping](https://user-images.githubusercontent.com/20186858/102028046-b9a10800-3d6d-11eb-822b-fc8918a9409c.JPG)
![ipyrad processors](https://user-images.githubusercontent.com/20186858/102028048-bc036200-3d6d-11eb-85f6-f0acbee1e536.JPG)

**Comment by isaacovercast** [comment]
You don't say how long the reads are, but i'm guessing they are long and i'm guessing this is also paired end data. No reason to be concerned, if it's running then it's still working, that's all.

You might find in the future that the gitter channel is a better place for questions like this: https://gitter.im/dereneaton/ipyrad
