### ISSUE TITLE
cookbook empirical API 1 Pedicularis Structure is out of date

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#428]
https://ipyrad.readthedocs.io/en/latest/API-assembly/cookbook-empirical-API-1-pedicularis.html

The structure analysis in this cookbook is using the old style strfile/mapfile format. We should update it.

**Comment by dereneaton** [comment]
Ok, I can do it, I'm working on these now.

**Comment by isaacovercast** [comment]
Fixed.
