### ISSUE TITLE
Barcode file not being read, unsure if this is a params issue or a continued formatting error?

### ISSUE THREAD

**Issue by molecularronin** [dereneaton/ipyrad#436]
Hi, I wanted to try to submit another issue to see if there is something I am doing wrong here with my early on assembly and I believe it is due to my barcode text file but I am not sure.

Here is the error message I am receiving with the following command:

ipyrad -p params-masters-thesis.txt -s 1 -r

ipyrad.assemble.utils.IPyradError:     One or more barcodes contain invalid IUPAC nucleotide code characters.
    Barcodes must contain only characters from this list "RKSYWMCATG".
    Doublecheck your barcodes file is properly formatted.

My text document, GBS-PstI-barcodes.txt contains the following:

1A CTCTCCAG
1B TAATTG
1C ATCTCGT
1D GACAACT
1E CTCGCAA
1F TGGACACT
1G TGTCAAT
1H TCCTGCT
2A GAACTT
2B ATGCT
2C ATTCCAA
2D GACACACT
2E CGCGT
2F CATACGCG
2G CTATCACT
2H CTGAACCA
3A TCTCCGT
3B TGTACA
3C AAGCAACT
3D ACCGA
3E GTAAG
3F TGATCGCT
3G TGCGG
3H ACTAA
4A GAGGTCCT
4B TAGCTAT
4C CAGCGCAAGA
4D GCTCGCCAT
4E TGTACCAG
4F TGTACGCA
4G TTGGCGCT
4H GTTCACA
5A CATGG
5B ACTACAAT
5C GACTAACT
5D ATGGTGA
5E TATTGCAG
5F ATCTGACT
5G GTCACGA
5H AACGACCACA
6A CGCCTCAT
6B CTTATG
6C TAGAG
6D GGCAT
6E CCGACG
6F TGGTCAAG
6G ACCAAG
6H CCATCCAA
7A GTTCGGT
7B GCCGCAAT
7C CATAAG
7D TTGAGACAG
7E ACCGTCCAT
7F GCGTGCCAGA
7G CCGAT
7H TCCTCCA
8A ACACG
8B CGCAAGA
8C ACACAACA
8D ATATT
8E GTCTCAACG
8F CCGCA
8G TCGTGACAGT
8H AATTG
9A TCCGT
9B TATAAGCAG
9C ATTCA
9D ACATGCCAG
9E TGCCTA
9F AAGGCCAACT
9G ACTCCACG
9H GGTTG
A10 TTCTCA
B10 CTGCCGT
C10 TTCCA
D10 GAGCGCT
E10 TAATTAA
F10 TGTGAGG
G10 TGTTGACG
H10 TACCT
A11 CCAGGA
B11 GGATGA
C11 ACAGAAT
D11 ATACTGAG
E11 CTCCAA
F11 TTAGGA
G11 CCAAGACAGT
H11 CATTGA
A12 TCATT
B12 GAATAGA
C12 TTCTG
D12 ACCTAA
E12 GCGTAG
F12 CGTAGCAACA
G12 AAGCAGA
H12 CAATTGCT

I’m not really sure what the problem could be with the above file, so maybe it’s something in my parameter file? Here are the first few lines of the params file:

masters-thesis                 ## [0] [assembly_name]: Assembly name. Used to name output directories for assembly steps

analysis-ktaube                ## [1] [project_dir]: Project dir (made in curdir if not present)

/home/FM/ktaube/201105_AHLVWJDSXY/McMahan-GBS_S29_L001_R1_001.fastq                        ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files

/home/FM/ktaube/201105_AHLVWJDSXY/McMahan-GBS_S29_L001_R2_001.fastq                        ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files

/home/FM/ktaube/201105_AHLVWJDSXY/GBS-PstI-barcodes-idless.txt                           		  ## [3] [barcodes_path]: Location of barcodes file                       

So I have my R1 and R2 both in the raw fastq path for [2], the barcode text file is there in [3], and nothing is in [4]. Any advice or troubleshooting suggestions would be greatly appreciated!

**Comment by isaacovercast** [comment]
The name of the barcodes file you post here which looks good `GBS-PstI-barcodes.txt` is not the same as the name of the barcodes file in your params file `/home/FM/ktaube/201105_AHLVWJDSXY/GBS-PstI-barcodes-idless.txt`, probably still pointing to the old bad barcodes file, no?

**Comment by isaacovercast** [comment]
These don't seem to be "issues" with ipyrad per se and rather questions about running it, which are much better addressed on our gitter channel: https://gitter.im/dereneaton/ipyrad

If you have questions about installation and running, this is a better place for things like these. Feel free to join the convo over there!
