### ISSUE TITLE
Reference-Based assembly with reference as an output

### ISSUE THREAD

**Issue by aremkh** [dereneaton/ipyrad#439]
Good day Deren and Isac,
Thank you for maintaining and updating the repository.
 In reference-based assembly, is there any way to print the matching loci within reference sequence itself as one of the samples in the output  sequence files?
I usually use third party packages to convert .vcf/.bam to a consensus sequence after phasing  etc.
I am wondering there might be a more straightforward solution for this task during loci assemblies by Ipyrad itself?
Thank you in advance

**Comment by isaacovercast** [comment]
Hello! In fact there is a quite straightforward way to include the reference sequence in the output files. There is a `hackersonly` parameter which you can set by running the analysis inside a jupyter notebook, like this:

```
import ipyrad
data = ipyrad.load_json("/tmp/ipyrad-test/peddradnames.json")
data.hackersonly.exclude_reference = True
data.run(steps="7", auto=True)
```

If you want to run CLI you can edit the json file by hand and set this parameter to `True`, but hand editing the json file is not recommended generally. Give that a shot and let me know how it goes.

Good luck!
