### ISSUE TITLE
Fatal error: Files compressed with gzip are not supported

### ISSUE THREAD

**Issue by laaryjc** [dereneaton/ipyrad#446]
Hi, 
As per below, I keep getting this error.  the wierd thing is it was workign last week, but now it won't progress.
I have a fresh install of Conda, and even started again from scratch.  Any thoughts?

[18:14:15] (base) laaryjc@HAL-at-AU:~/.ipyrad -p params_062921_micpet.txt -s 3
  loading Assembly: micpet_LJC
  from saved path: ~/Bioinformatics/Micpet_2021/iPyrad/micpet_LJC.json

 -------------------------------------------------------------
  ipyrad [v.0.9.81]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 
  Parallel connection | HAL-at-AU: 32 cores
  
  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:00:04 | join merged pairs      

  Encountered an Error.
  Message: IPyradError: Error merge pairs:
 ['/home/laaryjc/anaconda3/bin/vsearch', '--fastq_mergepairs', '/home/laaryjc/Bioinformatics/Micpet_2021/iPyrad/micpet_LJC_edits/MP078.trimmed_R1_.fastq.gz', '--reverse', '/home/laaryjc/Bioinformatics/Micpet_2021/iPyrad/micpet_LJC_edits/MP078.trimmed_R2_.fastq.gz', '--fastqout', '/home/laaryjc/Bioinformatics/Micpet_2021/iPyrad/micpet_LJC-tmpalign/MP078_merged.fastq', '--fastqout_notmerged_fwd', '/home/laaryjc/Bioinformatics/Micpet_2021/iPyrad/micpet_LJC-tmpalign/MP078_nonmerged_R1_.fastq', '--fastqout_notmerged_rev', '/home/laaryjc/Bioinformatics/Micpet_2021/iPyrad/micpet_LJC-tmpalign/MP078_nonmerged_R2_.fastq', '--fasta_width', '0', '--fastq_minmergelen', '35', '--fastq_maxns', '5', '--fastq_minovlen', '20', '--fastq_maxdiffs', '4', '--label_suffix', '_m1', '--fastq_qmax', '93', '--threads', '2', '--fastq_allowmergestagger']
vsearch v2.13.3_linux_x86_64, 78.6GB RAM, 32 cores
https://github.com/torognes/vsearch

Fatal error: Files compressed with gzip are not supported

  Parallel connection closed.

**Comment by isaacovercast** [comment]
Hm, that's weird. It looks like you're using an older version of vsearch that doesn't have zlib support. When I do `vsearch -v` on a working system I see this:
```
$ vsearch -v
vsearch v2.15.2_linux_x86_64, 251.8GB RAM, 40 cores
https://github.com/torognes/vsearch

Rognes T, Flouri T, Nichols B, Quince C, Mahe F (2016)
VSEARCH: a versatile open source tool for metagenomics
PeerJ 4:e2584 doi: 10.7717/peerj.2584 https://doi.org/10.7717/peerj.2584

Compiled with support for gzip-compressed files, and the library is loaded.
zlib version 1.2.11, compile flags a9
Compiled with support for bzip2-compressed files, and the library is loaded.
```
I am pulling vsearch from bioconda, which you can see with `conda list | grep vsearch`
```
vsearch                   2.15.2               h2d02072_0    bioconda
```

You might try conda installing vsearch and using `-c bioconda` and `--force-reinstall`.

**Comment by laaryjc** [comment]
Ok, so prior to your comment i updated conda 3 times and the last time it caught the old vsearch and updated it to v2.17.1, but not the prior 2 times
Weird indeed.  thanks for the help!
