### ISSUE TITLE
Crash at the end of step 3

### ISSUE THREAD

**Issue by carlahurt** [dereneaton/ipyrad#448]
Hello,
I am running a denovo alignment on a very large salamander GBS dataset. Step 3 took a very long time (12 days), and then something appeared to have happened during the aligning step. This caused it to crash in step 6.  Any ideas on what went wrong?  Also, is it possible to pick this back up after "chunking clusters" in step 3 and skip the long wait? I posted the errors in 2 snips - the messages were too long to fit in a single screen shot. I'm also attaching my params file for reference. 

![image](https://user-images.githubusercontent.com/31260532/124353092-f4637400-dbc9-11eb-982f-8256a2943731.png)
![image](https://user-images.githubusercontent.com/31260532/124353108-15c46000-dbca-11eb-9e08-ac17e8b65ed3.png)

[params-barb1.txt](https://github.com/dereneaton/ipyrad/files/6758322/params-barb1.txt)

Thank you,
Carlaa

**Comment by isaacovercast** [comment]
Hello. This is _almost certainly_ a disk space issue. I'm positive that you ran out of disk space right at the beginning of the aligning step. Please be sure that you have _plenty_ of free disk space, like 100's of GB or more, as much as you can get. ipyrad creates numerous temporary files (most of which are cleaned up after each step) but we assume that disk space is essentially unlimited. If your assembly is especially large then this is even more true. Unfortunately there isn't a way to restart _within_ a given step, so you'll have to run step 3 again. The clustering step can be impacted by very long reads, paired end data, and also very noisy data. I would verify with fastqc that your data does not contain a significant amount of low quality bases, and if it does I would trim the reads (during step 2) to remove as much of this as possible. This will speed up the clustering step.

**Comment by mikerenfro** [comment]
Hey, Isaac, Dr. Hurt’s HPC admin here. Where are the temporary files stored by default: /tmp or elsewhere? If /tmp, is there a way to override that, via environment variable or parameter?

**Comment by isaacovercast** [comment]
Hello Mike, all the temporary files are created within the `project_dir` which is specified within the params file for a given assembly. We don't touch the filesystem outside of this directory.

**Comment by mikerenfro** [comment]
In that case, we should have some dozen or so TB free there. Can look more closely on Tuesday or later.

**Comment by isaacovercast** [comment]
If it's not disk it could also be some other resource if there are quotas, for example I have seen issues with quotas on max number of files which could cause a similar kind of behavior.

**Comment by mikerenfro** [comment]
Far as I know, we have quota reporting, but no limits on space, file count, inodes, etc. Can verify later and let you know, thanks.

**Comment by carlahurt** [comment]
Hi Mike,

Thank you for trying to figure this out. Let me know if I need to delete some files.

Carla

Carla Hurt
Associate Professor of Biology
Tennessee Tech University
(931) 372-3143
https://sites.tntech.edu/hurtlab
________________________________

**Comment by mikerenfro** [comment]
From the file server's quota reports:
```
User quota on /mnt/xfs1 (/dev/mapper/VGMD1-LVMD1)
                        Blocks                            Inodes
User ID      Used   Soft   Hard Warn/Grace     Used   Soft   Hard Warn/Grace
---------- --------------------------------- ---------------------------------
...
churt        2.8T      0      0  00 [------] 307.4k      0      0  00 [------]
...
```

So there shouldn't be any file size or file count limits in place.

**Comment by isaacovercast** [comment]
Some strategic googling leads me to believe that the error messages we are seeing are SLURM red-herrings:
https://github.com/E3SM-Project/E3SM/issues/3138
https://www.mail-archive.com/slurm-users@lists.schedmd.com/msg04725.html
https://www.lstsrv.ncep.noaa.gov/pipermail/ncep.list.fv3-announce/2020-September/000410.html

Looking back at the output you originally sent it seems possible that these messages are internal SLURM noise and that they ipyrad assembly actually completed successfully.

Is it possible that step 6 actually ran to completion? Did you try running step 7?

**Comment by carlahurt** [comment]
You're right - it worked!!!
Thank you for your help - I apologize for the unnecessary drama.  I assumed that with the two pages of error messages it couldn't have worked.

**Comment by isaacovercast** [comment]
Very good. This is my favorite kind of problem.... the one that solves itself ;)
