### ISSUE TITLE
Message: IPyradError: bwa error: None

### ISSUE THREAD

**Issue by zilaijuand** [dereneaton/ipyrad#450]
Hello,
  when I running the step3:
 ''nohup ipyrad -p params-iptest.txt -s 3 ''
  Encountered an Error :
 ipyrad [v.0.9.71]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Parallel connection | gs31: 56 cores

  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:00:01 | indexing reference
  [####################] 100% 0:00:56 | dereplicating
  [####################] 100% 0:01:20 | mapping reads

  Encountered an Error.
  Message: IPyradError: bwa error: None
  Parallel connection closed.
  
 how can I fix it
 thanks！

**Comment by isaacovercast** [comment]
Hello,
This is almost certainly a memory allocation issue. From a previous issue on the gitter channel:
```
@brpark29 How much RAM are you allocating? Looks like bwa is crashing, could be lack of resources. If you have 24 cores you will need at LEAST 96GB of RAM. Easiest way to reduce this burden if you don't have enough RAM is to reduce the number of cores you're running on.
```
https://gitter.im/dereneaton/ipyrad?at=5d714d9232e48c5df242aefe

Either reduce the # of cores or increase memory allocation. Good luck.

**Comment by zilaijuand** [comment]
Thanks a lot！
