### ISSUE TITLE
Step 7: Error 72

### ISSUE THREAD

**Issue by minutoides** [dereneaton/ipyrad#453]
Hi!
I'm running Ipyrad [v.0.9.81] and I'm having problems with step 7.
When I run the software without reference (de novo) it works fine. 
But now i'm trying to do it using a genome of reference and it works until step 7, that gives me this error.

This is the full stats files:
`ipyrad -p params-staceiFR.txt -r`

Full stats files
------------------------------------------------
step 1: ./IpyradStaceiFR/StaceiFR_s1_demultiplex_stats.txt
step 2: ./IpyradStaceiFR/StaceiFR_edits/s2_rawedit_stats.txt
step 3: ./IpyradStaceiFR/StaceiFR_clust_0.85/s3_cluster_stats.txt
step 4: ./IpyradStaceiFR/StaceiFR_clust_0.85/s4_joint_estimate.txt
step 5: ./IpyradStaceiFR/StaceiFR_consens/s5_consens_stats.txt
step 6: ./IpyradStaceiFR/StaceiFR_across/StaceiFR_clust_database.fa
step 7: None

And when I run step 7:
`ipyrad -p params-staceiFR.txt -s 7 -d`

  loading Assembly: StaceiFR
  from saved path: /RadSeq/IpyradStaceiFR/StaceiFR.json

 -------------------------------------------------------------
  ipyrad [v.0.9.81]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Parallel connection | UBUNTUSRV: 12 cores

  Step 7: Filtering and formatting output files
  [####################] 100% 0:02:36 | applying filters
  [####################] 100% 0:04:57 | building arrays

  Encountered an Error.
  Message: KeyError: 72
  Parallel connection closed.
---------------------------------------------------------------------------KeyError                                  Traceback (most recent call last)<string> in <module>
~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/write_outputs.py in fill_snp_array(data, ntaxa, nsnps)
   2156         # fill for each taxon
   2157         for sidx in range(ntaxa):
-> 2158             resos = [DCONS[i] for i in snparr[sidx, :]]
   2159
   2160             # pseudoref version
~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/write_outputs.py in <listcomp>(.0)
   2156         # fill for each taxon
   2157         for sidx in range(ntaxa):
-> 2158             resos = [DCONS[i] for i in snparr[sidx, :]]
   2159
   2160             # pseudoref version
KeyError: 72

Could you help me to solve this problem?

Thanks,
Miguel

**Comment by minutoides** [comment]
Solved.
The reference sequences had ambiguities.

**Comment by isaacovercast** [comment]
Glad you solved it! Thanks for updating the issue. Ambiguities in the reference would definitely do it. Glad you figured it out.
