### ISSUE TITLE
Error when run ipyrad

### ISSUE THREAD

**Issue by yexiaying199056** [dereneaton/ipyrad#456]
![image](https://user-images.githubusercontent.com/89673935/131204137-8fb84008-c8c1-4afa-baa1-6e93ec19e966.png)
I installed ipyrad in a conda environment, and can read the help information with "ipyrad -h", but with error when I tried to run it. Do you have any idea how to fix it? Thank you very much!
Ye Xiaying

**Comment by yexiaying199056** [comment]
with -d parameter, it shows like this:
ipyrad [v.0.9.81]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 

  Encountered an Error.
  Message: KeyboardInterrupt: 
  Parallel connection closed.
---------------------------------------------------------------------------KeyboardInterrupt                         Traceback (most recent call last)~/.conda/envs/rad/lib/python3.9/site-packages/ipyparallel/serialize/serialize.py in serialize_object(obj, buffer_threshold, item_threshold)
    120             cobj[k] = c
    121     else:
--> 122         cobj = can(obj)
    123         buffers.extend(_extract_buffers(cobj, buffer_threshold))
    124 
~/.conda/envs/rad/lib/python3.9/site-packages/ipyparallel/serialize/canning.py in can(obj)
    396         # perform can_map imports, then try again
    397         # this will usually only happen once
--> 398         _import_mapping(can_map, _original_can_map)
    399         return can(obj)
    400 
~/.conda/envs/rad/lib/python3.9/site-packages/ipyparallel/serialize/canning.py in _import_mapping(mapping, original)
    359         if isinstance(key, string_types):
    360             try:
--> 361                 cls = import_item(key)
    362             except Exception:
    363                 if original and key not in original:
~/.conda/envs/rad/lib/python3.9/site-packages/ipython_genutils/importstring.py in import_item(name)
     29         # called with 'foo.bar....'
     30         package, obj = parts
---> 31         module = __import__(package, fromlist=[obj])
     32         try:
     33             pak = getattr(module, obj)
~/.conda/envs/rad/lib/python3.9/site-packages/numpy/__init__.py in <module>
    148     from . import _distributor_init
    149 
--> 150     from . import core
    151     from .core import *
    152     from . import compat
~/.conda/envs/rad/lib/python3.9/site-packages/numpy/core/__init__.py in <module>
     20 
     21 try:
---> 22     from . import multiarray
     23 except ImportError as exc:
     24     import sys
~/.conda/envs/rad/lib/python3.9/site-packages/numpy/core/multiarray.py in <module>
     10 import warnings
     11 
---> 12 from . import overrides
     13 from . import _multiarray_umath
     14 from ._multiarray_umath import *  # noqa: F403
~/.conda/envs/rad/lib/python3.9/site-packages/numpy/core/overrides.py in <module>
      5 import textwrap
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)
      9 from numpy.compat._inspect import getargspec
KeyboardInterrupt:

**Comment by isaacovercast** [comment]
This looks like a very unusual issue with numpy which there are some suggestions for solving here:

https://github.com/numpy/numpy/issues/14868

This looks like an issue with your host machine and numpy. You might try adding `-c 1` to the ipyrad command. You might also try some of the things suggested in the github issue I post above.

**Comment by yexiaying199056** [comment]
Thank you very much!
It ran successfully with parameter -c.
