### ISSUE TITLE
how to find out this parameters?

### ISSUE THREAD

**Issue by zilaijuand** [dereneaton/ipyrad#458]
Dear isaacovercast:
    I want to inference the demography history using stairway plot2, but I am confused where should I find this parameters after obtaining SNP.vcf from ipyrad? 
 
![image](https://user-images.githubusercontent.com/50914513/132120875-2ae72a34-d017-443f-9764-375c03be5e01.png)
    Thank you for taking the time!

**Comment by isaacovercast** [comment]
This information is at the very end of the *_stats.txt file:
```
## Alignment matrix statistics:
sequence matrix size: (12, 91000), 0.00% missing sites.
snps matrix size: (12, 4505), 0.00% missing sites.
```
The total sequence length here is 91000bp, including polymorphic and monomorphic sites.

**Comment by zilaijuand** [comment]
Thanks for your help！
