### ISSUE TITLE
Which vcf file is more suitable for calculating SFS?

### ISSUE THREAD

**Issue by zilaijuand** [dereneaton/ipyrad#460]
Dear isaacovercast：
    I want to inference the demographic history of population by allele frequency spectrum，but I'm not sure wether I should use the original vcf (79299SNPs) generated directly  from ipyrad to culculate the SFS or use the vcf (19131SNPs)filter by  some criterions( --max-missing 0.8, --maf 0.01)?
   Thanks~

**Comment by isaacovercast** [comment]
Hello,

I would start by looking at a couple of papers that use the demographic inference method you are interested in using and see how they do it. If you use my tool easySFS (search it on github) then it doesn't matter which vcf file you start with.

As this isn't an ipyrad issue at all, so I'm going to close it. In the future, for questions/discussion and other things that aren't specifically ipyrad issues, it's better to use the gitter channel: https://gitter.im/dereneaton/ipyrad.

**Comment by zilaijuand** [comment]
Thanks Reply！ I will pay attention next time.
