### ISSUE TITLE
step3: vsearch 2.20 deprecated --derep_fulllength

### ISSUE THREAD

**Issue by Uniltiranyu** [dereneaton/ipyrad#469]
ipyrad -p params-test2.txt -s 123

 -------------------------------------------------------------
  ipyrad [v.0.9.81]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 
  Parallel connection | master: 64 cores
  
  Step 1: Loading sorted fastq data to Samples
  [####################] 100% 0:00:54 | loading reads          
  50 fastq files loaded to 50 Samples.
  
  Step 2: Filtering and trimming reads
  [####################] 100% 0:08:23 | processing reads     
  
  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:00:01 | dereplicating          

  Encountered an Error.
  Message: IPyradError: 

Fatal error: FASTQ input is only allowed with the fastx_uniques command

  Parallel connection closed.
Is there something wrong with my fastq file? 
I'm using the default parameters, nothing has changed except the pathname, the same fastq files can be recognized by stacks.
ipyrad is downloaded by conda.
so sorry for my English.

**Comment by isaacovercast** [comment]
Well this looks like an issue with vsearch. They just implemented some change which causes this to break:

https://github.com/torognes/vsearch/issues/348

Ok, so it looks like derep_fulllength was deprecated in [vsearch 2.20](https://github.com/torognes/vsearch/commit/cd659b8a0a3255e891666dfe030a95cd375d4867). You can fix this by rolling back vsearch to 2.19:
`conda install -c bioconda vsearch=2.19`

I will think about a longer term solution.

**Comment by isaacovercast** [comment]
Pinned vsearch to 2.19 in ipyrad version 0.9.82

**Comment by isaacovercast** [comment]
Added a check to handle this in clustmap.py.
