### ISSUE TITLE
Fatal error: FASTQ input is only allowed with the fastx_uniques command

### ISSUE THREAD

**Issue by amesclir** [dereneaton/ipyrad#473]
Dear Isaac Overcast,

I got a error in the step3. I have analyzed 4 different projects. three of them complete the step 3 without problem. But for one of them I get always this message with step 3 starts:
Fatal error: FASTQ input is only allowed with the fastx_uniques command
Do you know which could be the problem?
Thanks!
Cheers,
Marcial

**Comment by amesclir** [comment]
OK! I have read other user with the same problem. It's a issue with a version ipyrad and vsearch. Fixed!

**Comment by isaacovercast** [comment]
Awesome, glad you got it fixed. I've been meaning to patch that so it doesn't happen any more. I'll try to get to it today.

**Comment by isaacovercast** [comment]
Fixed in `0.9.84`
