### ISSUE TITLE
Support for muscle v5

### ISSUE THREAD

**Issue by benoitnabholz** [dereneaton/ipyrad#477]
Hello,

I'm testing ipyrad on ddRAD data using already published Orthoptera data (https://www.ncbi.nlm.nih.gov/bioproject/PRJNA543714) wit 11 samples (single reads already demultiplexed).

I have installed ipyrad from conda: conda install ipyrad -c conda-forge -c bioconda
Version : ipyrad 0.9.84

Command line:
ipyrad -p params-Omocestus1.txt -s 1234 -c 10 -d

Everything went fine until step 3 where I got the following error message.

  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:00:23 | dereplicating          
  [####################] 100% 0:12:10 | clustering/mapping     
  [####################] 100% 0:00:03 | building clusters      
  [####################] 100% 0:00:00 | chunking clusters      
  [####################] 100% 0:00:02 | aligning clusters      

  Encountered an Error.
  Message: IndexError: string index out of range
  Parallel connection closed.

**My hard disk is not full.**

Running ipyrad using the "-d" option gave this:

File ~/miniconda3/envs/ipyrad/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1488, in <listcomp>(.0)
   1485 lclust1 = list(chain(*zip(
   1486     lclust[::2], [i.split("nnnn")[0] for i in lclust[1::2]])))
   1487 lclust2 = list(chain(*zip(
-> 1488     lclust[::2], [i.split("nnnn")[1] for i in lclust[1::2]])))
   1490 # put back into strings

IndexError: list index out of range
During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
File <string>:1, in <module>

File ~/miniconda3/envs/ipyrad/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1397, in align_and_parse(handle, max_internal_indels, is_gbs, declone)
   1394 nwodups = 0
   1396 # iterate over clusters sending each to muscle, splits and aligns pairs
-> 1397 aligned = persistent_popen_align3(clusts, 200, is_gbs)
   1399 # store good alignments to be written to file
   1400 refined = []

File ~/miniconda3/envs/ipyrad/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in persistent_popen_align3(clusts, maxseqs, is_gbs)
   1569 lines = "".join(align1)[1:].split("\n>")
   1571 ## find seed of the cluster and put it on top.
   1572 #seed = [i for i in lines if i.split(";")[-1][0] == "*"][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == "*"][0]
   1574 lines.pop(lines.index(seed))
   1575 lines = [seed] + sorted(
   1576     lines, key=get_derep_num, reverse=True)

File ~/miniconda3/envs/ipyrad/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in <listcomp>(.0)
   1569 lines = "".join(align1)[1:].split("\n>")
   1571 ## find seed of the cluster and put it on top.
   1572 #seed = [i for i in lines if i.split(";")[-1][0] == "*"][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == "*"][0]
   1574 lines.pop(lines.index(seed))
   1575 lines = [seed] + sorted(
   1576     lines, key=get_derep_num, reverse=True)

IndexError: string index out of range

""

Thank-you for your help,
Benoit

**Comment by isaacovercast** [comment]
Can you wetransfer me the raw data you're using?

**Comment by benoitnabholz** [comment]
Yes, off course:
https://filesender.renater.fr/?s=download&token=2105f98d-29c9-4b06-898f-daa389e8c7e7

I also put the param.txt file.

**Comment by isaacovercast** [comment]
The real problem is here (the IndexError is properly handled, it's a test for PE vs SE):
```
File ~/miniconda3/envs/ipyrad/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in persistent_popen_align3(clusts, maxseqs, is_gbs)
1569 lines = "".join(align1)[1:].split("\n>")
1571 ## find seed of the cluster and put it on top.
1572 #seed = [i for i in lines if i.split(";")[-1][0] == ""][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == ""][0]  <<<<-------
1574 lines.pop(lines.index(seed))
1575 lines = [seed] + sorted(
1576 lines, key=get_derep_num, reverse=True)
```
I think this would only happen if the iterator `i` either didn't contain a newline or if the zeroth element was empty.

This _works_ for me with a recent-ish version of ipyrad (0.9.81) and muscle version 3.8.1551 and vsearch 2.18.0. It _feels_ like a muscle or a vsearch update incompatibility, and I know that vsearch recently changed something that broke something else, so this seems plausible.

**Comment by isaacovercast** [comment]
Indeed, with the most recent version of ipyrad (0.9.84), muscle (5.1), and vsearch (2.21.1) I see this exact error.

**Comment by isaacovercast** [comment]
Something changed with muscle in the newest version. You can fix this by rolling back to an older (working) version:
```
conda install -c bioconda muscle=3.8.1551
```

**Comment by isaacovercast** [comment]
Okay, two things:

1) muscle 5 changed the flags from `-in`/`-out` to `-align`/`-output`
2) It _looks_ like muscle 5 can't natively read fasta data from a pipe. Looking at muscle source file multisequence.cpp, `MultiSequence::LoadMFA` is expecting a filename as a string.

Our current method relies on piping:
```
cmd = ("echo -e '{}' | {} -quiet -in - ; echo {}"
             .format(lclust, ip.bins.muscle, "//\n"))
```
I'm not quite sure what to do about this at the moment.

**Comment by isaacovercast** [comment]
Force aligning w/ Old version
```
head -n 8 /tmp/ipyrad-test/se-tmpalign/1B_0_chunk_0.ali | /Users/isaac/miniconda3/envs/tmp/bin/muscle -quiet -in /dev/stdin -out /dev/stdout
```

and new version:
```
head -n 8 /tmp/ipyrad-test/se-tmpalign/1B_0_chunk_0.ali | muscle -quiet -align /dev/stdin -output /dev/stdout
```
