### ISSUE TITLE
problems in Step 3: Error merge pairs

### ISSUE THREAD

**Issue by Yyeserin** [dereneaton/ipyrad#484]
Hi,

I am working on paired ddRADseq data.  I came across this issue, and don't understand why:

 _------------------------------------------------------------
  ipyrad [v.0.9.84]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Parallel connection | r445.uppmax.uu.se: 20 cores

Step 1: Loading sorted fastq data to Samples
  [####################] 100% 0:05:42 | loading reads
  196 fastq files loaded to 98 Samples.

  Step 2: Filtering and trimming reads
  [####################] 100% 0:50:43 | processing reads

  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:12:17 | join merged pairs

  Encountered an Error.
  Message: IPyradError: Error merge pairs:
 ['/proj/snic2022-23-181/conda/ipyrad/bin/vsearch', '--fastq_mergepairs', '/crex/proj/snic2022-23-181/damselfly/whole/ipyrad/all_samples_run/damselfly_all/damselfly_all_edits/Pop-1_RS.16.trimmed_R1_.fastq.gz', '--reverse', '/crex/proj/snic2022-23-181/damselfly/whole/ipyrad/all_samples_run/damselfly_all/damselfly_all_edits/Pop-1_RS.16.trimmed_R2_.fastq.gz', '--fastqout', '/crex/proj/snic2022-23-181/damselfly/whole/ipyrad/all_samples_run/damselfly_all/damselfly_all-tmpalign/Pop-1_RS.16_merged.fastq', '--fastqout_notmerged_fwd', '/crex/proj/snic2022-23-181/damselfly/whole/ipyrad/all_samples_run/damselfly_all/damselfly_all-tmpalign/Pop-1_RS.16_nonmerged_R1_.fastq', '--fastqout_notmerged_rev', '/crex/proj/snic2022-23-181/damselfly/whole/ipyrad/all_samples_run/damselfly_all/damselfly_all-tmpalign/Pop-1_RS.16_nonmerged_R2_.fastq', '--fasta_width', '0', '--fastq_minmergelen', '40', '--fastq_maxns', '4', '--fastq_minovlen', '20', '--fastq_maxdiffs', '4', '--label_suffix', '_m1', '--fastq_qmax', '93', '--threads', '2', '--fastq_allowmergestagger']
vsearch v2.21.1_linux_x86_64, 125.4GB RAM, 20 cores
https://github.com/torognes/vsearch_

How can I solve the problem?  I will appreciate your suggestions.

Many thanks.
Yeserin.

**Comment by isaacovercast** [comment]
Hello,
Can you please try running step 3 again and this time including the `-d` flag? This should generate more debug output to show better what the error is. Please post any additional error information here and I'll take a look.

**Comment by isaacovercast** [comment]
Any update on this?

**Comment by Yyeserin** [comment]
Step 3 did not finish even after running it for several days. Maybe it is memory issues. I have given up with the software. You could close the issue. 

Thank you for your suggestion and help.

**Comment by isaacovercast** [comment]
Step 3 can take a long time depending on how many samples you have, the sequencing effort, and so on. Paired end data also makes step 3 take longer. 196 samples of paired-end data could easily take a couple days. Small memory allocation would also make step 3 run slowly. I will close this issue as you suggest. Good luck!
