### ISSUE TITLE
Step 1 has been running and does not end, and there is no error message

### ISSUE THREAD

**Issue by Zeroo11** [dereneaton/ipyrad#487]
[](url)Only 4 demultiplexed/sorted RAD-seq data are used. After running the first step, it has been running and never ends, no any file is generated, but there is no error message. 

**The parameter file is as follows**:
 <img width="966" alt="image" src="https://user-images.githubusercontent.com/72841838/178544421-1a4a4565-4aba-4798-9134-fe4c6431ba68.png">

**They are 4 demultiplexed/sorted RAD-seq:**
<img width="473" alt="image" src="https://user-images.githubusercontent.com/72841838/178542332-47feb61c-6c49-4691-8c2c-152b93bb1632.png">

**It's a state that never stops** （no error message）：
<img width="537" alt="image" src="https://user-images.githubusercontent.com/72841838/178544587-9b2385d6-a278-45e0-a541-a5ce7e0c9151.png">

**This is the cpu status：**
<img width="612" alt="image" src="https://user-images.githubusercontent.com/72841838/178544739-15205c7c-681f-4164-a72d-0dc7e6d035a3.png">

I have tried reinstalling ipyrad, installing ipyrad with a lower version, and even reinstalling the centos system, but still can't solve it. I urge friends and developers to help, thank you very much!

**Comment by Zeroo11** [comment]
> Hm, are you running this on an HPC system or a local workstation?
> 
> You might try launching ipcluster by hand, it seems there is some coordination issue with the python parallelization backend.
> 
> ```
> ## Replace 64 here with however many cores your workstation has
> ipcluster start --n 64 --daemonize
> ## Wait for this to return and make look for the message saying the cluster is running
> 
> ## Now run ipyrad with the --ipcluster flag
> ipyrad -p params-iplex.txt -s 1 --ipcluster
> ```
> 
> Try that and let me know how it goes.

Thank you very much !
According to your method, there are some error messages, as follows
`(ipyrad) [pse_01@localhost params_file]$ ipyrad -p params-ipilex.txt -s 1 --ipcluster

 -------------------------------------------------------------
  ipyrad [v.0.9.84]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 
Traceback (most recent call last):
  File "/home/pse_01/miniconda3/envs/ipyrad/bin/ipyrad", line 10, in <module>
    sys.exit(main())
  File "/home/pse_01/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/__main__.py", line 605, in main
    CLI()
  File "/home/pse_01/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/__main__.py", line 75, in __init__
    self.run()
  File "/home/pse_01/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/__main__.py", line 496, in run
    ipyclient = ipp.Client(profile=self.args.ipcluster)
  File "/home/pse_01/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyparallel/client/client.py", line 607, in __init__
    self._connect(sshserver, ssh_kwargs, timeout)
  File "/home/pse_01/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyparallel/client/client.py", line 758, in _connect
    raise TimeoutError("Hub connection request timed out")
TimeoutError: Hub connection request timed out
`

Do you still know how to solve this error？
My research team and I are very grateful for your help!

**Comment by isaacovercast** [comment]
Yes, it looks like you need to wait longer for the ipcluster instance to start up before launching ipyrad. You can see some documentation about running ipcluster by hand [here](https://ipyrad.readthedocs.io/en/latest/HPC_script.html#optional-controlling-ipcluster-by-hand).

The call to `sleep` gives the ipcluster engines time to spin up. You might need to experiment with longer sleep times depending on your particular clusters behavior.

```
ipcluster start --n 20 --daemonize
sleep 60
 ipyrad -p params-test.txt -s 2 --ipcluster
```

**Comment by isaacovercast** [comment]
Fixed?
