### ISSUE TITLE
Step3 error IndexError: string index out of range

### ISSUE THREAD

**Issue by Uniltiranyu** [dereneaton/ipyrad#489]
I used -d flag.

IndexError                                Traceback (most recent call last)
File <string>:1, in <module>

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1397, in align_and_parse(handle, max_internal_indels, is_gbs, declone)
   1394 nwodups = 0
   1396 # iterate over clusters sending each to muscle, splits and aligns pairs
-> 1397 aligned = persistent_popen_align3(clusts, 200, is_gbs)
   1399 # store good alignments to be written to file
   1400 refined = []

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in persistent_popen_align3(clusts, maxseqs, is_gbs)
   1569 lines = "".join(align1)[1:].split("\n>")
   1571 ## find seed of the cluster and put it on top.
   1572 #seed = [i for i in lines if i.split(";")[-1][0] == "*"][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == "*"][0]
   1574 lines.pop(lines.index(seed))
   1575 lines = [seed] + sorted(
   1576     lines, key=get_derep_num, reverse=True)

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in <listcomp>(.0)
   1569 lines = "".join(align1)[1:].split("\n>")
   1571 ## find seed of the cluster and put it on top.
   1572 #seed = [i for i in lines if i.split(";")[-1][0] == "*"][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == "*"][0]
   1574 lines.pop(lines.index(seed))
   1575 lines = [seed] + sorted(
   1576     lines, key=get_derep_num, reverse=True)

IndexError: string index out of range

**Comment by Uniltiranyu** [comment]
ipyrad -p params-test3.txt -s 34567 -d -c 40
  loading Assembly: test3
  from saved path: ~/viola/ipy/test3.json

 -------------------------------------------------------------
  ipyrad [v.0.9.84]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 
  Parallel connection | master: 40 cores
  
  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:00:03 | indexing reference     
  [####################] 100% 0:03:31 | dereplicating          
  [####################] 100% 6:42:33 | clustering/mapping     
  [####################] 100% 0:00:24 | building clusters      
  [####################] 100% 0:00:05 | chunking clusters      
  [####################] 100% 0:01:10 | aligning clusters      

  Encountered an Error.
  Message: IndexError: string index out of range
  Parallel connection closed.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1488, in persistent_popen_align3(clusts, maxseqs, is_gbs)
   1485 lclust1 = list(chain(*zip(
   1486     lclust[::2], [i.split("nnnn")[0] for i in lclust[1::2]])))
   1487 lclust2 = list(chain(*zip(
-> 1488     lclust[::2], [i.split("nnnn")[1] for i in lclust[1::2]])))
   1490 # put back into strings

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1488, in <listcomp>(.0)
   1485 lclust1 = list(chain(*zip(
   1486     lclust[::2], [i.split("nnnn")[0] for i in lclust[1::2]])))
   1487 lclust2 = list(chain(*zip(
-> 1488     lclust[::2], [i.split("nnnn")[1] for i in lclust[1::2]])))
   1490 # put back into strings

IndexError: list index out of range

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
File <string>:1, in <module>

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1397, in align_and_parse(handle, max_internal_indels, is_gbs, declone)
   1394 nwodups = 0
   1396 # iterate over clusters sending each to muscle, splits and aligns pairs
-> 1397 aligned = persistent_popen_align3(clusts, 200, is_gbs)
   1399 # store good alignments to be written to file
   1400 refined = []

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in persistent_popen_align3(clusts, maxseqs, is_gbs)
   1569 lines = "".join(align1)[1:].split("\n>")
   1571 ## find seed of the cluster and put it on top.
   1572 #seed = [i for i in lines if i.split(";")[-1][0] == "*"][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == "*"][0]
   1574 lines.pop(lines.index(seed))
   1575 lines = [seed] + sorted(
   1576     lines, key=get_derep_num, reverse=True)

File ~/miniconda3/lib/python3.8/site-packages/ipyrad/assemble/clustmap.py:1573, in <listcomp>(.0)
   1569 lines = "".join(align1)[1:].split("\n>")
   1571 ## find seed of the cluster and put it on top.
   1572 #seed = [i for i in lines if i.split(";")[-1][0] == "*"][0]
-> 1573 seed = [i for i in lines if i.split('\n')[0][-1] == "*"][0]
   1574 lines.pop(lines.index(seed))
   1575 lines = [seed] + sorted(
   1576     lines, key=get_derep_num, reverse=True)

IndexError: string index out of range

**Comment by isaacovercast** [comment]
Can you please post your params file?

Without knowing more I will guess that you are doing a 'reference' assembly and I will guess that there are one or more 'special' characters in the reference sequence CHROM names. Can you check the reference sequence to make sure there aren't any unusual characters (like slashes or stars or colons).

**Comment by Uniltiranyu** [comment]
------- ipyrad params file (v.0.9.63)-------------------------------------------
test3                          ## [0] [assembly_name]: Assembly name. Used to name output directories for assembly steps
/data/plantlab/HYS/viola/ipy   ## [1] [project_dir]: Project dir (made in curdir if not present)
                               ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files
                               ## [3] [barcodes_path]: Location of barcodes file
/data/plantlab/HYS/viola/out/*.fq.gz ## [4] [sorted_fastq_path]: Location of demultiplexed/sorted fastq files
denovo                         ## [5] [assembly_method]: Assembly method (denovo, reference)
/data/plantlab/HYS/viola/pubescens/viola.fa ## [6] [reference_sequence]: Location of reference sequence file
rad                            ## [7] [datatype]: Datatype (see docs): rad, gbs, ddrad, etc.
AATTC,                         ## [8] [restriction_overhang]: Restriction overhang (cut1,) or (cut1, cut2)
4                              ## [9] [max_low_qual_bases]: Max low quality base calls (Q<20) in a read
33                             ## [10] [phred_Qscore_offset]: phred Q score offset (33 is default and very standard)
6                              ## [11] [mindepth_statistical]: Min depth for statistical base calling
6                              ## [12] [mindepth_majrule]: Min depth for majority-rule base calling
10000                          ## [13] [maxdepth]: Max cluster depth within samples
0.93                           ## [14] [clust_threshold]: Clustering threshold for de novo assembly
0                              ## [15] [max_barcode_mismatch]: Max number of allowable mismatches in barcodes
2                              ## [16] [filter_adapters]: Filter for adapters/primers (1 or 2=stricter)
35                             ## [17] [filter_min_trim_len]: Min length of reads after adapter trim
2                              ## [18] [max_alleles_consens]: Max alleles per site in consensus sequences
0.05                           ## [19] [max_Ns_consens]: Max N's (uncalled bases) in consensus
0.05                           ## [20] [max_Hs_consens]: Max Hs (heterozygotes) in consensus
1                              ## [21] [min_samples_locus]: Min # samples per locus for output
20                             ## [22] [max_SNPs_locus]: Max # SNPs per locus
8                              ## [23] [max_Indels_locus]: Max # of indels per locus
0.1                            ## [24] [max_shared_Hs_locus]: Max # heterozygous sites per locus
0, 0, 0, 0                     ## [25] [trim_reads]: Trim raw read edges (R1>, <R1, R2>, <R2) (see docs)
0, 0, 0, 0                     ## [26] [trim_loci]: Trim locus edges (see docs) (R1>, <R1, R2>, <R2)
s, v                           ## [27] [output_formats]: Output formats (see docs)
                               ## [28] [pop_assign_file]: Path to population assignment file
                               ## [29] [reference_as_filter]: Reads mapped to this reference are removed in step 3

**Comment by Uniltiranyu** [comment]
Hi
I got this error after updating to the latest version using conda 
So roll back to 0.9.63
The same has this error

**Comment by Uniltiranyu** [comment]
The same dataset didn't have this error before, I just deleted some individuals and ran new branches

**Comment by isaacovercast** [comment]
How did you delete some individuals exactly? Can you show me the commands you ran to remove individuals and run the new branch?

If you removed files or moved anything around it might just be easiest to start over from step 1 and use the -f flag to force rerunning. Steps 1 and 2 are fast and this will get your assembly back into working order.

**Comment by Uniltiranyu** [comment]
I used step1 and 2 directly，but this error still occurred.Ipyrad -p  para*.txt -s 1234567 -c 40 -d -f

**Comment by isaacovercast** [comment]
The params file you posted shows 'denovo' as the assembly_method, but the output you posted includes the 'indexing reference' step, which is only processed for 'reference' assembly methods:

```
[####################] 100% 0:00:03 | indexing reference
```

Are you sure the params file you posted in this issue is the one you are using for the assembly? It doesn't look like it to me.

**Comment by Uniltiranyu** [comment]
I thought that if I choose denovo, the reference path selection will be disabled, so I didn't change the file.I will try to manually write a parameter file once.-------- 原始邮件 --------发件人： Isaac Overcast ***@***.***>日期： 2022年8月9日周二 凌晨2:36收件人： dereneaton/ipyrad ***@***.***>抄送： Uniltiranyu ***@***.***>, Author ***@***.***>主    题： Re: [dereneaton/ipyrad] Step3 error IndexError: string index out of range (Issue #489)
The params file you posted shows 'denovo' as the assembly_method, but the output you posted includes the 'indexing reference' step, which is only processed for 'reference' assembly methods:
[####################] 100% 0:00:03 | indexing reference

Are you sure the params file you posted in this issue is the one you are using for the assembly? It doesn't look like it to me.

**Comment by isaacovercast** [comment]
If you choose 'denovo' it does ignore the reference sequence. try re-running making sure the 'denovo' method is selected, and post the complete output of ipyrad here, if it doesn't work.

**Comment by Uniltiranyu** [comment]
I ran it again and still got the same error.So I uninstalled the entire anaconda environment and reinstalled it, and it workedIt is speculated that the fault is caused by the direct upgrade of the software by conda
