### ISSUE TITLE
KeyError: <ufunc 'invert'>  at Assembly Step7

### ISSUE THREAD

**Issue by mydjc** [dereneaton/ipyrad#490]
Assembly Step7, error after applying filters reached 100%, the assembly interrupted.

Some said it could caused by the wrong version combination of numba or numpy, I have tried some combinations according to the _Version support information_ from [https://numba.readthedocs.io/en/stable/user/installing.html](url). 

But none of them works without interruption. I am really confused since I am not good at python.

**_---------------------------------------------- the python console-----------------------------------------------------_**
Parallel connection | mydjc-manjora: 11 cores
[####################] 100% 0:00:02 | applying filters     | s7 |
Encountered an Error.
Message: KeyError: <ufunc 'invert'>
**_---------------------------------------------- the python console-----------------------------------------------------_**

OS：5.15.55-1-MANJARO (64-bit)
python：3.9.12
ipyrad：0.9.84
some possable involved packages vision: numba==0.56.0、numpy==1.22.4、llvmlite==0.39.0.

**Comment by isaacovercast** [comment]
It sounds like a version issue of some package, so I think the first thing to try would be to blow away your conda environment, create a new clean environment, and reinstall ipyrad from scratch. Can you try that and let me know how it goes?

```
conda create -n new_ipyrad
conda activate new_ipyrad
conda install -c conda-forge -c bioconda ipyrad
``` 

Good luck.

**Comment by mydjc** [comment]
Thank you very much. It works well in a new clean environment.
Maybe the the previous Error was caused by the incomplete conda installation with some trivial pip remedy, 
 After all, it is not rare to see conda install **timeout** in my country.

In a word,  it is best to only use conda to install ipyrad complete.
