### ISSUE TITLE
IPyradError

### ISSUE THREAD

**Issue by mydjc** [dereneaton/ipyrad#491]
There is another error that I want to pointed out.
**_---------------------------------------------- the python console-----------------------------------------------------_**
IPyradError: b'/opt/miniconda3/bin/samtools: /opt/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by /opt/miniconda3/bin/samtools)\n/opt/miniconda3/bin/samtools: /opt/miniconda3/bin/../lib/libncursesw.so.6: no version information available (required by /opt/miniconda3/bin/samtools)\n/opt/miniconda3/bin/samtools: /opt/miniconda3/bin/../lib/libncursesw.so.6: no version information available (required by /opt/miniconda3/bin/samtools)\n[E::hts_hopen] Failed to open file -\n[E::hts_open_format] Failed to open file "-" : Exec format error\nsamtools sort: can\'t open "-": Exec format error\n'
**_---------------------------------------------- the python console-----------------------------------------------------_**

There is another **ipyradERROR** above in the Step3. 
It occured in all of our lab's linux devices. And neglect that there is already a ncurses in the conda list ,`conda install ncurses -c conda-forge`,it will install the right ncurses,although I don't know the reason.

**Comment by mydjc** [comment]
Let me summarize the process of installing ipyrad
   ```
conda create EnvName 
conda activate EnvName
conda install ipyrad -c conda-forge -c bioconda
pip uninstall h5py
pip3 install h5py
conda install ncurses -c conda-forge
```

If just `conda install ipyrad -c conda-forge -c bioconda` in a new clean env，
1. you may meet the h5py init error when you start ipyrad in the terminal.





2. you may meet error about samtools in the Step3

```
IPyradError: b'/opt/miniconda3/bin/samtools: /opt/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by /opt/miniconda3/bin/samtools)\n/opt/miniconda3/bin/samtools: /opt/miniconda3/bin/../lib/libncursesw.so.6: no version information available (required by /opt/miniconda3/bin/samtools)\n/opt/miniconda3/bin/samtools: /opt/miniconda3/bin/../lib/libncursesw.so.6: no version information available (required by /opt/miniconda3/bin/samtools)\n[E::hts_hopen] Failed to open file -\n[E::hts_open_format] Failed to open file "-" : Exec format error\nsamtools sort: can't open "-": Exec format error\n'
```

   Or when you start samtools in the terminal.

**Comment by isaacovercast** [comment]
Hello, thanks for the detailed information about this install issue. I _suspect_ that the problem is related to dependencies when using python 3.9 (as it looks like you have here). I installed ipyrad in a clean python3.10 environment and everything worked fine. I created a new python3.9 environment and I see the step of solving install dependencies is having a lot of problems. Can you try python3.10?

```
conda create -n ipyrad_py310 python=3.10
conda activate ipyrad_py310
conda install ipyrad -c conda-forge -c bioconda
```

I updated the README and the install documentation to indicate that python 3.10 is preferable and known to work.

**Comment by mydjc** [comment]
The python 3.10 env still need `conda install ncurses -c conda-forge` to fix the samtools lib error.

**Comment by mydjc** [comment]
Sorry, lol, here I am again! I finally found out that the most suitable ipyrad is still python3.7, because
 
In the environment of 3.9, samtools and HDF5 will report an error;
In the 3.10 environment, samtools will still report an error, and tetrad only supports up to 3.7.

In the 3.7 environment, I just need to install it according to your instructions, and it seems that there will be no errors.

**Comment by isaacovercast** [comment]
Very good. Thank you for the detailed information about solving the installation problem. I _suspect_ that some local configuration on your machine is causing some of these dependency problems, as the py3.10 ipyrad install works cleanly on several computers I have tested (primarily Ubuntu linux). regardless, I hope your solution and your error reporting will be useful if someone in the future has a similar problem. Thanks for reporting it!
