### ISSUE TITLE
Where to pay the ref sequence indexing penalty?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#5]
Reference has to get indexed before mapping will work. This is a one time cost, the indices hang around forever unless you delete them. Depending on the size of the reference sequence this can take between 5 and 20 minutes. Here are options for where we could make this happen:

* Make the user do it. We might still have to guard against the case where it isn't done right, in which case we'd have to do it ourselves anyway.
* Do it during creation of assembly object - this seems annoying, feels like a bad user experience decision.
* Do it inside assembly.step3() - this seems more appropriate. People already *expect* step3 to take a while, so another few minutes won't be noticed.
* Do it inside cluster_within.run() somewhere - This is where i was initially gonna put it, but burying it so deep seems problematic.

I'm leaning toward adding it at the beginning of step3

**Comment by dereneaton** [comment]
I agree, beginning of step 3 seems most appropriate.

**Comment by isaacovercast** [comment]
This will live in assemble.step3() right at the head of the function. Tested and it seems to work fine, passes silently if no reference or if it's already indexed.
