### ISSUE TITLE
Refseq mapping - New mode "neutral only"

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#50]
Got a weird idea for a new mode for refseq mapping, could be cool and it's _super_ easy to implement. In this mode you map reads, then throw away all the ones that __DO__ map, so it's like 'denovo_only'. My reasoning is that lots of downstream stuff assumes neutral markers, and stuff that maps to reference is demonstrably more highly conserved, so it is probably non-neutral or linked to non-neutral. It needs a catchy name, some ideas: 'denovo_only' maybe 'neutral_only' but that's a little presumptuous.

**Comment by isaacovercast** [comment]
Fixed. 8256059

**Comment by dereneaton** [comment]
This is a great idea. I imagine one could easily setup a couple of different assemblies for comparison. e.g., 
```
## gets all data that matches to reference
data1 = ip.Assembly("reference")
data1.set_params("assembly_method", "reference")

## gets all data that does not match to reference
data2 = ip.Assembly("neutral")
data2.set_params("assembly_method", "neutral")

## gets ref & denovo data, uses reference for additional paralog filtering
data3 = ip.Assembly("hybrid")
data3.set_params("assembly_method", "hybrid")

## assemble all objects
for assembly in [data1, data2, data3]:
    assembly.run()

```

To be even more efficient, `data2` and `data3` could branch as copies of data1 before step3 if one wanted to save time and disk space by reusing the same step1 and step2 files. 

``` 
## run steps 1&2 on data1
data1 = ip.Assembly("reference")
data1.set_params("assembly_method", "reference")
data1.run(12)

## branch data2 and data3 from existing files
data2 = data1.copy("neutral")
data3 = data1.copy("hybrid")
data2.set_params("assembly_method", "neutral")
data3.set_params("assembly_method", "hybrid")

## finish all 3 assemblies 
for assembly in [data1, data2, data3]:
    assembly.run(3456)
```

This seems like good stuff for the documentation. We'll just have to make it clear which files are affected by which assembly method so users know when they can and cannot branch Assembly objects.

**Comment by dereneaton** [comment]
To be clear, there are now four methods, right?

1) Denovo -- uses only denovo data
2) Reference -- uses only data that matches to reference
3) Hybrid -- uses denovo data and reference match data
4) Neutral -- uses denovo data, but excludes any matches to reference

**Comment by isaacovercast** [comment]
Yes, exactly. Your ideas about branching are exactly what i had in mind. There are now 4 methods, the new one is called 'denovo_only', cuz i even though "neutral" is cooler i thought it was also very presumptuous :). I can see that 'denovo_only' might be ambiguous, should i switch this to 'neutral'? I think it makes it more clear what it's actually doing.

**Comment by dereneaton** [comment]
What about something like `ref_filtered`? since we're using the reference sequence to only remove loci. I could see this being useful whether the reference is a full reference, transcriptome, or plastome.

**Comment by isaacovercast** [comment]
How about `remove_reference`? Seems most unambiguous, plus it's concordant with the `reference` option.

**Comment by dereneaton** [comment]
OK. Then we explain it like the following: 
```
Denovo
Reference
Hybrid             (Denovo + Reference) i.e., (Denovo assisted by Reference)
Remove_Reference   (Denovo - Reference) i.e., (Denovo filtered by Reference)
```
