### ISSUE TITLE
ipyrad assembly step (1) stalls indefinitely

### ISSUE THREAD

**Issue by billiemaguire** [dereneaton/ipyrad#506]
I am having an issue where certain ipyrad steps, particularly the assembly step, will never stop running. I can create the params file just fine, but the following steps will stall indefinitely. Uninstalling ipyrad or creating a new conda environment will sometimes solve the problem temporarily.

I've installed miniconda and ipyrad on my unviersity's HPC like this:

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
bash
conda info
 
conda create —name ipyrad28
conda activate ipyrad28

conda config --set solver classic
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
conda install -v ipyrad -c conda-forge -c bioconda

I've written this at the top of my sbatch script:

#!/bin/bash
#SBATCH -p cpu-long # partition
#SBATCH -c 12  # cpu
#SBATCH --mem=100G  # Requested Memory
#SBATCH -o ipy5-123b  # %j = job ID

#module load miniconda

eval "$(/work/pi_mayra_cadorinvidal_umb_edu/epi/scripts/bash/bin/conda shell.bash hook)"

source  /work/pi_mayra_cadorinvidal_umb_edu/epi/scripts/bash/

conda activate ipyrad28

Any insight into what might be causing this issue would be greatly appreciated. 

Thank you much,
Billie

**Comment by isaacovercast** [comment]
Hello Billie,

Thanks for providing all the great detail in your issue, it helps a lot.

This sounds like an HPC timing issue, which is somewhat common on HPC systems. You can get around this by launching the ipyparallel cluster by hand, prior to running ipyrad. Docs for this are here: https://ipyrad.readthedocs.io/en/latest/HPC_script.html#optional-controlling-ipcluster-by-hand

**Comment by isaacovercast** [comment]
Well, that all looks fine, except the error message indicates you are out of disk space in your home directory. This could be what the real problem has been all along. Check on your disk usage and what your quota is. You'll probably have to remove some stuff from your home directory to make room for the ipyparallel log files (they aren't big, but moving them to a different location would be annoying). Good luck and let me know how it goes.

**Comment by billiemaguire** [comment]
That works! Thank you so much for your help. I really appreciate it.
