### ISSUE TITLE
trim_loci does not work  properly in ver 0.9.84 to trim 3' ends of loci

### ISSUE THREAD

**Issue by gscabanne** [dereneaton/ipyrad#509]
I am using ver 0.9.84 and trim_loci does not work for trimming 3' ends of loci. In parameter trim_loci I used specified 0,6,0,0,   since I wanted to cut six bases from 3' end of all loci. I only re run step 7, however, outfiles were exactly the same as with 0,0,0,0.
What grabbed my attention is that release notes of ver 0.9.57 stated to have solved an issued on trim_loci (i.e., Fix oops in step 7 where trim_loci 3’ R1 wasn’t being used.)

**Comment by isaacovercast** [comment]
Thanks for reporting this. It looks like the problem in #410 never actually got fixed and this is the same issue you're seeing, so i'm going to close this issue and just log all my progress in #410, because there's already some useful info there. Watch #410 for progress.
