### ISSUE TITLE
How to add the ddRAD data to params.text

### ISSUE THREAD

**Issue by AliBasuony2022** [dereneaton/ipyrad#513]
Dear colleageus,
Does any one know how to add the ddRAD data in the parameters file. I know it is a simple question, but I have tried a lot and it didn't work.
for example, I tried the below.
./Ali/plate1_AliBasuony_R1.fastq.gz     ./Ali/plate1_AliBasuony_R2.fastq.gz ## [2] [raw_fastq_path]: Location of raw non-demultiplexed fastq files

Kind regards,
Ali

**Comment by isaacovercast** [comment]
Hello Ali,
Yes, you must use the wildcard character to specify paired data '*', like this:

./Ali/plate1_AliBasuony_R*.fastq.gz

The files must also be renamed to include exactly "_R1_" and "_R2_".

Good luck
