### ISSUE TITLE
Starting from step 2, demultiplexed/sorted fastq files

### ISSUE THREAD

**Issue by AliBasuony2022** [dereneaton/ipyrad#514]
Dear Isaac,

I have tow plates of ddrad data and the same barcodes were used for both plates ( I mean the same barcodes set has been used for different samples. I think I can't combine the two plates to one and start from step 1, because of the confusion to assign the reads with the same barcode to two differnt samples.  I have done demultiplexing step (step 1 in ipyrad pipeline) using a nother piepline and started from step 2, but I got  the below error that mean I must have .json file which can be generated only in step 1.

Any suggestions to resolve this, please.
 
 error " ipyrad.assemble.utils.IPyradError:
            Could not find saved Assembly file (.json) in expected location.
            Checks in: [project_dir]/[assembly_name].json
            Checked: /mnt/ursus/GROUP-sbifh3/c1845371/ipyrad/Ali_ddRAD_denovo_plate1_R1.json

Kind regards,
Ali

**Comment by isaacovercast** [comment]
If you demultiplexed both plates independently you can just put all the fastq files in one folder and point to this with the ipyrad `sorted_fastqs_folder` parameter. Then you need to run step 1 on this to load in the fastqs (it will not demux only load the data), then you can proceed as normal.

You could also do everything using the ipyrad commands and the `-m` parameter to merge different assemblies after step 1: https://ipyrad.readthedocs.io/en/latest/8-branching.html#one-library-multiple-lanes-of-sequencing

Good luck!
