### ISSUE TITLE
ModuleNotFoundError: No module named 'ipyrad'

### ISSUE THREAD

**Issue by emagallong** [dereneaton/ipyrad#515]
Hi!
I installed ipyrad step-by-step as suggested, but when I moved to Jupyter Notebook I got this error:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_422489/30096575.py in <module>
----> 1 import ipyrad as ip

ModuleNotFoundError: No module named 'ipyrad'

What can I do to resolve it?

Thanks in advance ;)

**Comment by isaacovercast** [comment]
Did you install ipyrad inside a conda environment? Did you run the jupyter
notebook server from the same conda environment that you installed ipyrad
in?

**Comment by isaacovercast** [comment]
This is not really an issue with ipyrad, but more of a help request, which is probably easier to handle on our gitter channel:

https://app.gitter.im/#/room/#dereneaton_ipyrad:gitter.im

If you need more assistance like this please use the gitter channel. Thanks!

**Comment by emagallong** [comment]
Yes, I installed ipyrad inside a conda environment. I'm not working on a server, I'm on a Linux workstation... I run in Jupyter the command !conda activate ipyrad ... It didn't work.

**Comment by isaacovercast** [comment]
Yes, you can't change the conda environment of a running jupyter server.
You need to kill your notebook server and `conda activate ipyrad` and then
start the notebook server from the proper environment. Good luck!

**Comment by isaacovercast** [comment]
+1 nice!
