### ISSUE TITLE
Clustering Threshold value and reference mapping

### ISSUE THREAD

**Issue by Gutierrez-Larruscain** [dereneaton/ipyrad#517]
Dear Isaac,

How exactly works the parameter Clustering Threshold in a reference mapped assembly? I am running Ipyrad under reference assembly method parameter, branching it for different threshold values (0.85 to 0.95, by 0,01 steps). 

The point is that I am obtaining identical results (_stats.txt) and I am so confused about it, because It seems that modified CT parameter is not affecting in any way final results.

Best
David

**Comment by isaacovercast** [comment]
Hi David,

The clustering threshold actually is not used in the reference mapped assembly, so that explains why the results are the same. Let me know if you have other questions!

-isaac
