### ISSUE TITLE
No module named \'cutadapt.cli\'\n’

### ISSUE THREAD

**Issue by zerdoner** [dereneaton/ipyrad#520]
Hi, 

after ipyrad (v0.9.92) worked fine about 4-6 weeks ago, I wanted to run some further analyses for the past couple of days and I consistently encounter an error at step 2:

<ipyrad.Sample object A071co1933_4> [14:apply] IPyradError:  error in cutadapt -a AGATCGGAAGAGC --quality-base 33 -q 20 --minimum-length 35 --max-n 5 --trim-n --output /home/zerdoner/data_remote/Summer_school_TaxonOMICS/ISC/ISC_80_edits/A071co1933_4.trimmed_R1_.fastq.gz /home/zerdoner/data_remote/Summer_school_TaxonOMICS/Raw_data/A071co1933_4.fastq.gz
 b'Traceback (most recent call last):\n  File "/home/zerdoner/miniconda3/bin/cutadapt", line 7, in <module>\n    from cutadapt.cli import main_cli\nModuleNotFoundError: No module named \'cutadapt.cli\'\n'

I am using the cutadapt that is integrated in ipyrad  (conda install ipyrad -c conda-forge -c bioconda). Downloading the whole thing did not help. I am using Python 3.8.16.

When checking for dependencies in (mini)conda I get a similar error when trying to open cutadapt:

Traceback (most recent call last):
  File "/home/zerdoner/miniconda3/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
ModuleNotFoundError: No module named 'cutadapt.cli'

Has anyone else encountered a similar issue?

**Comment by isaacovercast** [comment]
Hello,

That's weird, it works for me and cutadapt doesn't seem to have changed recently. I am using cutadapt v4.4 (from bioconda) and that appears to be the most recent version when i search with `anaconda search cutadapt`. Can you try this and show me the results?

```
$ python 
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cutadapt
>>> cutadapt.__version__
'4.4'
>>> import cutadapt.cli
>>> 
```

**Comment by zerdoner** [comment]
Hi,

in case someone else is going to have a similar issue. I still do not know what the problem is, because cutadapt is there, but I created a new environment and installed ipyrad locally. This solved the issue.

**Comment by isaacovercast** [comment]
glad it is working now. +1
