### ISSUE TITLE
How to express 'or' in the statement when establishing subsamples in step 7?

### ISSUE THREAD

**Issue by jljy47** [dereneaton/ipyrad#527]
How to express A or B in the statement when establishing subsamples in step 7?

For example, my dataset contains four species: A -, B -, C -, and D -, and I want to generate a dataset with A - and B -.

Currently, I could only listed all AB species for generation. 
>Keep_ List=[i for i in data. samples. keys() if i in ["A-xxxx1", "B-xxxx1", ...]

Is there any other expression that can simply include A+B?
I have tried using 
>subsamples=[i for i in pops. samples if "A" or "B" in i] 
but reported an error.

So how to express 'or' in ipyrad?

Known expressions:
>Nouts=data. branch ("nouts_min32", samples=[i for i in pops. samples if "A" in i])

>subsamples=[i for i in pops. samples if "A" in i]
>subsamples=[i for i in pops. samples if "A" not in i]

Thank you so much~

**Comment by isaacovercast** [comment]
This isn't really an ipyrad question so much as a python question, but anyway one strategy is simple:

Did you try this?

```
[i for i in pops.samples if 'A' in i or 'B' in i]
```

Good luck.

**Comment by jljy47** [comment]
Wow, thank you so much for helping me with this simple question!~ 
I will try this after the newest process finishing.


Sincere thanks,
with best wishes. ;)
