### ISSUE TITLE
The timing bar is not updated after closing the Jupyter notebook web page by mistake

### ISSUE THREAD

**Issue by jljy47** [dereneaton/ipyrad#528]
Hi,

I accidentally closed the progress bar page in Jupyter notebook (but the terminal is still there). After re-opening, there is no timing, and the terminal displays as shown as follow. I would like to ask if the program is still continuing in the background at this time?

Terminal

> 
> [W 14:57:30.569 NotebookApp] Notebook HT_all_20231004.ipynb is not trusted
> [W 14:57:30.686 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20231004091321 (127.0.0.1) 3.420000ms referer=http://localhost:8888/notebooks/HT_all_20231004.ipynb
> [I 14:57:30.703 NotebookApp] Discarding 3 buffered messages for 2241b074-00c6-4023-982b-9f7ec468eacc:ec2bed7b0e934be5a939bd14f1472795
> [I 16:22:50.489 NotebookApp] Starting buffering for 2241b074-00c6-4023-982b-9f7ec468eacc:3ea932dcf9c4413c8fd48c5ab011b37e
> [W 16:22:50.810 NotebookApp] Notebook HT_all_20231004.ipynb is not trusted
> [W 16:22:50.982 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20231004091321 (127.0.0.1) 2.470000ms referer=http://localhost:8888/notebooks/HT_all_20231004.ipynb
> [I 16:22:51.010 NotebookApp] Discarding 5 buffered messages for 2241b074-00c6-4023-982b-9f7ec468eacc:3ea932dcf9c4413c8fd48c5ab011b37e
> [I 17:08:10.184 NotebookApp] Starting buffering for 2241b074-00c6-4023-982b-9f7ec468eacc:75da0a1cec2840a5a5e258b3588367b4
> ERROR:asyncio:Task exception was never retrieved
> future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/nku/miniconda3/lib/python3.7/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
> Traceback (most recent call last):
>   File "/home/nku/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 1102, in wrapper
>     await fut
> tornado.iostream.StreamClosedError: Stream is closed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/nku/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
>     raise WebSocketClosedError()
> tornado.websocket.WebSocketClosedError
> [W 17:08:10.623 NotebookApp] Notebook HT_all_20231004.ipynb is not trusted
> [W 17:08:10.859 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20231004091321 (127.0.0.1) 3.550000ms referer=http://localhost:8888/notebooks/HT_all_20231004.ipynb
> [I 17:08:10.899 NotebookApp] Discarding 7 buffered messages for 2241b074-00c6-4023-982b-9f7ec468eacc:75da0a1cec2840a5a5e258b3588367b4
> [W 17:10:10.248 NotebookApp] Notebook HT_all_20231004.ipynb is not trusted
> [W 17:10:10.583 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20231004091321 (127.0.0.1) 3.670000ms referer=http://localhost:8888/notebooks/HT_all_20231004.ipynb
> 
>

**Comment by isaacovercast** [comment]
Hello there,

This is not an ipyrad issue, it is a question about how jupyter notebooks work. Issues in the ipyrad github repo should be limited to problems with the software itself. If you have general computing questions or issues with coding or jupyter please feel free to ask on the ipyrad gitter channel or join stackflow.

I know the answer to your question but I will leave it as an exercise for you to figure out how to answer for yourself. If you are truly stuck ask it again on the gitter channel in a couple days.

All the best,
-isaac

**Comment by jljy47** [comment]
Hi, isaac.

Sorry to ask another question not related to ipyrad.

Thank you for pointing me to the area where this problem belongs. 
I'm going to try and find out the answer.

Thank you very much again.~


Best wishes,
-L
