### ISSUE TITLE
multithread alignment

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#53]
The **mucle_align** functions only run at about 30% CPU. I think this is because it's using a pretty inefficient IO method to pass the data to **muscle** and back. I've tried a ton of different ways to improve this but to no success. 

One thing I've though about doing is to simply run 2-3 threads on each processor that run muscle_align separately, which would effectively use more of the available processing power. When the number of clusters is huge (~1M) the alignment step usually takes much longer than clustering. So improvements to this would be great.

**Comment by isaacovercast** [comment]
The chunking we do now seems pretty optimal.
