### ISSUE TITLE
ipyrad-bucky error in python 3.12

### ISSUE THREAD

**Issue by tsm-tsm** [dereneaton/ipyrad#536]
Hello！
 I have encountered some issues with the operation of Bucky and encountered an error while executing the final command line.

c.run_mbsum(force=True, ipyclient=ipyclient)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/bucky.py", line 406, in run_mbsum
    progressbar(sum(ready), len(ready), start, printstr)
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/utils.py", line 201, in progressbar
    progress = 100 * (finished / float(total))
ZeroDivisionError: float division by zero

Thanks!

**Comment by isaacovercast** [comment]
Can you show the notebook code you ran before run_mbsum?  Did you first `run_mrbayes`? It looks like there are no mbtrees which is why you're getting the divide by zero error.

**Comment by tsm-tsm** [comment]
Thank you!

(base) chenxing@chenxing-VirtualBox:~/Documents/tangshimei/tangshimei/20231106RAD/test_outfiles4$ python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipyrad.analysis as ipa
>>> import ipyparallel as ipp
>>> ipyclient = ipp.Client(cluster_id="bucky")
>>> len(ipyclient)
1
>>> samples = [
...     "C.Wenchangensis_LFT",
...     "C.amabilis_SS",
...     "C.argyrophylla_LC",
...     "C.calathiformis_PDLZ",
...     "C.carlesii_FJS",
...     "Q.variabilis_SCBG",
...     "T.doichangensis_PDLZ",
... ]
>>> c = ipa.bucky(
...     name="buckytest",
...     data="./test.alleles",
...     workdir="analysis-bucky",
...     samples=samples,
...     minsnps=0,
...     maxloci=100,
... )
>>> c.params
bucky_alpha           [0.1, 1.0, 10.0]    
bucky_nchains         4                   
bucky_niter           1000000             
bucky_nreps           4                   
maxloci               100                 
mb_mcmc_burnin        100000              
mb_mcmc_ngen          1000000             
mb_mcmc_sample_freq   1000                
minsnps               0                   
seed                  525539085           

>>> c.write_nexus_files(force=True)
wrote 100 nexus files to ~/Documents/tangshimei/tangshimei/20231106RAD/test_outfiles4/analysis-bucky/buckytest
>>> c.run_mrbayes(force=True, ipyclient=ipyclient)
[####################] 100% 0:00:01 | infer gene-tree posteriors 
>>> c.run_mbsum(force=True, ipyclient=ipyclient)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/bucky.py", line 406, in run_mbsum
    progressbar(sum(ready), len(ready), start, printstr)
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/utils.py", line 201, in progressbar
    progress = 100 * (finished / float(total))
ZeroDivisionError: float division by zero
>>> c.run(force=True, ipyclient=ipyclient)
wrote 100 nexus files to ~/Documents/tangshimei/tangshimei/20231106RAD/test_outfiles4/analysis-bucky/buckytest
[####################] 100% 0:00:01 | infer gene-tree posteriors 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/bucky.py", line 328, in run
    self.run_mbsum(force=force, quiet=quiet, ipyclient=ipyclient)
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/bucky.py", line 406, in run_mbsum
    progressbar(sum(ready), len(ready), start, printstr)
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/utils.py", line 201, in progressbar
    progress = 100 * (finished / float(total))
ZeroDivisionError: float division by zero
>>>

**Comment by isaacovercast** [comment]
Do you have mrbayes installed? The `run_mrbayes` function finished in 1 second, which indicates to me that something went wrong with it. the last time i checked there were some issues installing mrbayes with conda, so you'll have to do it by hand, unfortunately.

```
c.run_mrbayes(force=True, ipyclient=ipyclient)
[####################] 100% 0:00:01 | infer gene-tree posteriors
```

**Comment by tsm-tsm** [comment]
Is there a difference between the command to install mrbay in Bucky (conda install - c BioBuilds mrbayes) and the command to install mrbayes in Mrbayes (conda install mrbayes - c bioconda - c conda-forge)? Are the two ways of installing mrbayes the same?
Thanks

**Comment by isaacovercast** [comment]
Pulling from bioconda will install a more recent version of mrbayes so I assume it's updated more frequently. What happens if you try running mrbayes from the command line by hand?

**Comment by tsm-tsm** [comment]
**(1)**
# Name                    Version            Build             Channel
mrbayes                   3.2.7                h1b649f3_6    bioconda

**(2)**
import ipyrad.analysis as ipa
import toytree
nexfile = "./test.nex"
mb = ipa.mrbayes(
    name="test16",
    data=nexfile,
    clock=True,
    ngen=5000000,
    samplefreq=5000,
    nruns=1,
)
mb.params.samplefreq = 10000
mb.params
print(mb.nexus_string)
mb.run(block=True, force=True)

**(3)**
nohup: ignoring input
#NEXUS
log start filename=/home/ug1297/mrbayes-test16/analysis-mb/test16.nex.log replace;
execute /home/ug1297/mrbayes-test16/test.nex;
begin mrbayes;
set autoclose=yes nowarn=yes;

lset nst=6 rates=gamma;
mcmcp ngen=5000000 nrun=1 nchains=4;
mcmcp relburnin=yes burninfrac=0.25;
mcmcp samplefreq=10000 printfreq=10000;
mcmcp filename=/home/ug1297/mrbayes-test16/analysis-mb/test16.nex;
mcmc;
sump filename=/home/ug1297/mrbayes-test16/analysis-mb/test16.nex;
sumt filename=/home/ug1297/mrbayes-test16/analysis-mb/test16.nex;
end;
Traceback (most recent call last):
  File "/home/ug1297/mrbayes-test16/mrbayes.py", line 22, in <module>
    mb.run(block=True, force=True)
  File "/home/ug1297/.conda/envs/tetrad/lib/python3.10/site-packages/ipyrad/analysis/mrbayes.py", line 397, in run
    self.stdout = _call_mb([self.binary, self.nexus])
  File "/home/ug1297/.conda/envs/tetrad/lib/python3.10/site-packages/ipyrad/analysis/mrbayes.py", line 532, in _call_mb
    raise IPyradError(comm[0].decode())
ipyrad.assemble.utils.IPyradError

**Comment by isaacovercast** [comment]
Any progress? This seems to be a problem with mrbayes and the conda package, not ipyrad, so if you can get mrbayes running and still have problems please reopen this issue.

**Comment by tsm-tsm** [comment]
Hi, I'm not getting anywhere, I'm using a different approach instead of this analysis.
