### ISSUE TITLE
step3 error

### ISSUE THREAD

**Issue by Kenjicoral** [dereneaton/ipyrad#537]
Hello,

I am running ipyrad, my data are 12 samples, pair-end obtained from ezRadseq. 
I am having an error during step 3, and I can not figure out what is the source of the error. 
Any help would be very appreciated.

This is the code and the error message:

ipyrad -p ./ipyrad_parameter/params-blackcoral.txt -s 1234567

 -------------------------------------------------------------
  ipyrad [v.0.9.93]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 
  Parallel connection | dl-machine: 14 cores
  
  Step 1: Loading sorted fastq data to Samples
  [####################] 100% 0:00:48 | loading reads          
  24 fastq files loaded to 12 Samples.
  
  Step 2: Filtering and trimming reads
  [####################] 100% 0:16:35 | processing reads     
  
  Step 3: Clustering/Mapping reads within samples
  [####################] 100% 0:02:36 | join merged pairs      
  [####################] 100% 0:00:13 | join unmerged pairs    
  [####################] 100% 0:01:16 | dereplicating          
  [####################] 100% 9 days, 22:59:59 | clustering/mapping     

  Encountered an Error.
  Message: IPyradError: cmd ['/home/takatak/anaconda3/envs/ipyrad/bin/vsearch', '-cluster_smallmem', '/home/takatak/ezRADseq/BlackCoral/blackcoral-tmpalign/Stichopathes_sp.180_derep.fa', '-strand', 'both', '-query_cov', '0.75', '-id', '0.85', '-minsl', '0.75', '-userout', '/home/takatak/ezRADseq/BlackCoral/blackcoral_clust_0.85/Stichopathes_sp.180.utemp', '-userfields', 'query+target+id+gaps+qstrand+qcov', '-maxaccepts', '1', '-maxrejects', '0', '-threads', '2', '-notmatched', '/home/takatak/ezRADseq/BlackCoral/blackcoral_clust_0.85/Stichopathes_sp.180.htemp', '-fasta_width', '0', '--minseqlength', '35', '-fulldp', '-usersort']: b'WARNING: Option --fulldp is ignored\nvsearch v2.25.0_linux_x86_64, 125.5GB RAM, 14 cores\nhttps://github.com/torognes/vsearch\n\nReading file /home/takatak/ezRADseq/BlackCoral/blackcoral-tmpalign/Stichopathes_sp.180_derep.fa 100%\n1387417923 nt in 6041477 seqs, min 35, max 527, avg 230\nMasking 100%\nCounting k-mers 100%\nClustering'
Error: ipcluster shutdown and must be restarted
  Parallel connection closed.

**Comment by Kenjicoral** [comment]
After adjusting the length to be trimmed with fastqc, the error disappeared and the analysis was done in a short time!
Thank you very much!

**Comment by isaacovercast** [comment]
👍 awesome!
