### ISSUE TITLE
ipyrad-baba error 

### ISSUE THREAD

**Issue by tsm-tsm** [dereneaton/ipyrad#538]
Hello！

I have encountered some issues with the operation of baba and encountered an error. Can I use tetrad's newick tree as input file？It runs normally when I use the raxml's newick file as the input file. Thank !

#####################1-1-2
##1Load packages
import ipyrad.analysis as ipa
import ipyparallel as ipp
import toytree
import toyplot

##2Set up and connect to the ipyparallel cluster
#ipcluster start -n 5 --cluster-id="baba" --daemonize
ipyclient = ipp.Client(cluster_id="baba")
len(ipyclient)

##3Load in your .loci data file  parse the newick tree, re-root it, and plot it
locifile = "./test16.loci"
newick = "./virentes-min4.tree"
rtre = toytree.tree(newick).root(wildcard="T.doichangensis_PDLZ")
newick = rtre.write()

##4create an initial object linked to your data in 'locifile'
aa = ipa.baba(data=locifile)
bb = aa.copy()
cc = aa.copy()

##5Linking tests to the baba object
aa.tests = {
    "p4": ["C.mollissima_MJ"],
    "p3": ["C.fissa_JFL"],
    "p2": ["C.tcheponensis_TMS"],
    "p1": ["C.clarkei_DHB", "C.indica_JFL", "C.hainanensis_JFL", "C.Wenchangensis_LFT", "C.delavayi_GL", "C.jucunda_LA", "C.chinensis_DH", "C.sclerophylla_NC", "C.mekongensis_PDLZ", "C.fordii_HSD",  "C.hystrix_SS", "C.kawakamii_SCBG", "C.tibetana_FJS", "C.rockii_GL", "C.xichouensis_MLP_3", "C.malipoensis_MLP_15", "C.orthacantha_QZ", "C.chunii_FJS", "C.platyacantha_YJ",  "C.kweichowensis_XDJ", "C.fabri_JFL", "C.ceratacantha_TMS", "C.lamontii_MS", "C.eyrei_FJS", "C.carlesii_FJS", "C.echidnocarpa_DDG", "C.ledongensis_JFL", "C.fargesii_FJS", "C.amabilis_SS", "C.nigrescens_HSD", "C.megaphylla_DW", "C.jianfenglingensis_JFL_3", "C.tonkinensis_JFL", "C.ferox_QSZ", "C.fleuryi_PDLZ", "C.argyrophylla_LC"],
}

bb.tests = {
    "p4": ["C.mollissima_MJ"],
    "p3": ["C.fissa_JFL"],
    "p2": ["C.tcheponensis_TMS"],
    "p1": ["C.clarkei_DHB", "C.indica_JFL", "C.hainanensis_JFL", "C.Wenchangensis_LFT", "C.delavayi_GL", "C.jucunda_LA", "C.chinensis_DH", "C.sclerophylla_NC", "C.mekongensis_PDLZ", "C.fordii_HSD",  "C.hystrix_SS", "C.kawakamii_SCBG", "C.tibetana_FJS", "C.rockii_GL", "C.xichouensis_MLP_3", "C.malipoensis_MLP_15", "C.orthacantha_QZ", "C.chunii_FJS", "C.platyacantha_YJ",  "C.kweichowensis_XDJ", "C.fabri_JFL", "C.ceratacantha_TMS", "C.lamontii_MS", "C.eyrei_FJS", "C.carlesii_FJS", "C.echidnocarpa_DDG", "C.ledongensis_JFL", "C.fargesii_FJS", "C.amabilis_SS", "C.nigrescens_HSD", "C.megaphylla_DW", "C.jianfenglingensis_JFL_3", "C.tonkinensis_JFL", "C.ferox_QSZ", "C.fleuryi_PDLZ", "C.argyrophylla_LC"],
}

cc.tests = [
    {
     "p4": ["C.mollissima_MJ"],
     "p3": ["C.fissa_JFL"],
     "p2": ["C.tcheponensis_TMS"],
     "p1": ["C.clarkei_DHB", "C.indica_JFL", "C.hainanensis_JFL", "C.Wenchangensis_LFT", "C.delavayi_GL", "C.jucunda_LA", "C.chinensis_DH", "C.sclerophylla_NC", "C.mekongensis_PDLZ", "C.fordii_HSD",  "C.hystrix_SS", "C.kawakamii_SCBG", "C.tibetana_FJS", "C.rockii_GL", "C.xichouensis_MLP_3", "C.malipoensis_MLP_15", "C.orthacantha_QZ", "C.chunii_FJS", "C.platyacantha_YJ",  "C.kweichowensis_XDJ", "C.fabri_JFL", "C.ceratacantha_TMS", "C.lamontii_MS", "C.eyrei_FJS", "C.carlesii_FJS", "C.echidnocarpa_DDG", "C.ledongensis_JFL", "C.fargesii_FJS", "C.amabilis_SS", "C.nigrescens_HSD", "C.megaphylla_DW", "C.jianfenglingensis_JFL_3", "C.tonkinensis_JFL", "C.ferox_QSZ", "C.fleuryi_PDLZ", "C.argyrophylla_LC"],
    },
    {
     "p4": ["C.mollissima_MJ"],
     "p3": ["C.fissa_JFL"],
    "p2": ["C.tcheponensis_TMS"],
    "p1": ["C.clarkei_DHB", "C.indica_JFL", "C.hainanensis_JFL", "C.Wenchangensis_LFT", "C.delavayi_GL", "C.jucunda_LA", "C.chinensis_DH", "C.sclerophylla_NC", "C.mekongensis_PDLZ", "C.fordii_HSD",  "C.hystrix_SS", "C.kawakamii_SCBG", "C.tibetana_FJS", "C.rockii_GL", "C.xichouensis_MLP_3", "C.malipoensis_MLP_15", "C.orthacantha_QZ", "C.chunii_FJS", "C.platyacantha_YJ",  "C.kweichowensis_XDJ", "C.fabri_JFL", "C.ceratacantha_TMS", "C.lamontii_MS", "C.eyrei_FJS", "C.carlesii_FJS", "C.echidnocarpa_DDG", "C.ledongensis_JFL", "C.fargesii_FJS", "C.amabilis_SS", "C.nigrescens_HSD", "C.megaphylla_DW", "C.jianfenglingensis_JFL_3", "C.tonkinensis_JFL", "C.ferox_QSZ", "C.fleuryi_PDLZ", "C.argyrophylla_LC"],
}

cc.tests = [
    {
     "p4": ["C.mollissima_MJ"],
     "p3": ["C.fissa_JFL"],
     "p2": ["C.tcheponensis_TMS"],
     "p1": ["C.clarkei_DHB", "C.indica_JFL", "C.hainanensis_JFL", "C.Wenchangensis_LFT", "C.delavayi_GL", "C.jucunda_LA", "C.chinensis_DH", "C.sclerophylla_NC", "C.mekongensis_PDLZ", "C.fordii_HSD",  "C.hystrix_SS", "C.kawakamii_SCBG", "C.tibetana_FJS", "C.rockii_GL", "C.xichouensis_MLP_3", "C.malipoensis_MLP_15", "C.orthacantha_QZ", "C.chunii_FJS", "C.platyacantha_YJ",  "C.kweichowensis_XDJ", "C.fabri_JFL", "C.ceratacantha_TMS", "C.lamontii_MS", "C.eyrei_FJS", "C.carlesii_FJS", "C.echidnocarpa_DDG", "C.ledongensis_JFL", "C.fargesii_FJS", "C.amabilis_SS", "C.nigrescens_HSD", "C.megaphylla_DW", "C.jianfenglingensis_JFL_3", "C.tonkinensis_JFL", "C.ferox_QSZ", "C.fleuryi_PDLZ", "C.argyrophylla_LC"],
    },
    {
     "p4": ["C.mollissima_MJ"],
     "p3": ["C.fissa_JFL"],
     "p2": ["C.tcheponensis_TMS"],
     "p1": ["C.clarkei_DHB", "C.indica_JFL", "C.hainanensis_JFL", "C.Wenchangensis_LFT", "C.delavayi_GL", "C.jucunda_LA", "C.chinensis_DH", "C.sclerophylla_NC", "C.mekongensis_PDLZ", "C.fordii_HSD",  "C.hystrix_SS", "C.kawakamii_SCBG", "C.tibetana_FJS", "C.rockii_GL", "C.xichouensis_MLP_3", "C.malipoensis_MLP_15", "C.orthacantha_QZ", "C.chunii_FJS", "C.platyacantha_YJ",  "C.kweichowensis_XDJ", "C.fabri_JFL", "C.ceratacantha_TMS", "C.lamontii_MS", "C.eyrei_FJS", "C.carlesii_FJS", "C.echidnocarpa_DDG", "C.ledongensis_JFL", "C.fargesii_FJS", "C.amabilis_SS", "C.nigrescens_HSD", "C.megaphylla_DW", "C.jianfenglingensis_JFL_3", "C.tonkinensis_JFL", "C.ferox_QSZ", "C.fleuryi_PDLZ", "C.argyrophylla_LC"],
    },
]

##print params for object aa
aa.params
bb.params.mincov = {"p4":1, "p3":1, "p2":1, "p1":1}
bb.params
aa.run(ipyclient)
bb.run(ipyclient)
cc.run(ipyclient)

#Auto-generating tests
dd = bb.copy()
dd.newick = newick
dd.generate_tests_from_tree()
constraint_dict = {
    "p4": ["C.mollissima_MJ"],
    "p3": ["C.fissa_JFL"],
    "p2": ["C.tcheponensis_TMS"],
    }

dd.generate_tests_from_tree(
    constraint_dict=constraint_dict,
    constraint_exact=False,
)
dd.generate_tests_from_tree(
    constraint_dict=constraint_dict,
    constraint_exact=True,
)

dd.run(ipyclient)

dd.results_table.to_csv("dd.abba-baba-1-1-2.csv")
dd.taxon_table.to_csv("dd.abba-baba-taxon-1-1-2.csv")

nohup: ignoring input
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:01 |  calculating D-stats ^M[                    ]   0% 0:00:01 |  calculating D-stats ^M[                  
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                  
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:01 |  calculating D-stats ^M[                  
1374166 tests generated from tree
73 tests generated from tree
73 tests generated from tree
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                  
  File "/home/chenxing/Documents/tangshimei/tangshimei/20231106RAD/abba-test16-No-LD/1tetrad.analysis111.py", line 84, in <module>
    dd.run(ipyclient)
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/baba.py", line 170, in run
    self.results_table, self.results_boots = batch(self, ipyclient)
  File "/home/chenxing/miniconda3/lib/python3.10/site-packages/ipyrad/analysis/baba.py", line 403, in batch
    raise IPyradError(\
ipyrad.assemble.utils.IPyradError:  error: 31: [2:apply] ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by isaacovercast** [comment]
Any newick file should be fine. Is the _topology_ of the tetrad tree the same? if the topology is different and you are constraining the tests in a way that doesn't make sense for the tetrad tree, then you will get this kind of error. Are you sure the constraints make sense for the tetrad tree?

**Comment by tsm-tsm** [comment]
The _topology_ of raxml and tetrad is different, but I have modified aa.tests, bb.tests, cc.tesst and constraints_dict according to the topology of tetrad.
When I delete "p2": ["C.tcheponensis_TMS"], of constraints_dict, 

nohup: ignoring input
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M
^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M[                    ]   0% 0:00:00 |  calculating D-stats ^M
1374166 tests generated from tree
4442 tests generated from tree
4442 tests generated from tree
^M[                    ]   0% 0:00:01 |  calculating D-stats ^M[                    ]   0% 0:00:01 |  calculating D-stats ^M[                    ]   0% 0:00:01 |  calculating D-stats ^M
  File "/home/ug1297/baba-test16-tetrad-NOLD/1tetrad.analysis111.py", line 83, in <module>
    dd.run(ipyclient)
  File "/home/ug1297/.conda/envs/tetrad/lib/python3.10/site-packages/ipyrad/analysis/baba.py", line 170, in run
    self.results_table, self.results_boots = batch(self, ipyclient)
  File "/home/ug1297/.conda/envs/tetrad/lib/python3.10/site-packages/ipyrad/analysis/baba.py", line 403, in batch
    raise IPyradError(\
ipyrad.assemble.utils.IPyradError:  error: 31: [4:apply] ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by isaacovercast** [comment]
Can you wetransfer me the loci file and the newick trees you are using from raxml and tetrad?

**Comment by tsm-tsm** [comment]
Thank you for your attention. I have sent the file to you as an attachment.




Tangshimei
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dereneaton/ipyrad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 凌晨5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dereneaton/ipyrad] ipyrad-baba error  (Issue #538)





 
Can you wetransfer me the loci file and the newick trees you are using from raxml and tetrad?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

test.loci (128.38M, 2024年02月14日 10:11 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0f39373057d7c1c1ced97f5215370a19494d0251025100021c010405501a095406091a05560e5a1b0008040407565a03065b5656333e3842544a431e5f585b5f3104&code=19703786

**Comment by isaacovercast** [comment]
Thank you. Can I also please have the newick trees you are using from raxml and tetrad?

**Comment by tsm-tsm** [comment]
Hello, sometimes the GitHub website is unstable, so yesterday I replied to your email using QQ Mail. I also attached the tree file via QQ Mail, but I'm not sure if you received these files. Therefore, I have re-uploaded the tree file on GitHub.
[tree file.zip](https://github.com/dereneaton/ipyrad/files/13944448/tree.file.zip)

**Comment by isaacovercast** [comment]
![image](https://github.com/dereneaton/ipyrad/assets/5974975/9c77be71-05e5-46de-bdc0-8921753f2424)

The `reference` individual is included in the tetrad newick tree, but not the RAxML tree. The 'reference' sequence is not included in the loci file, so this is why it works for the RAxML tree, but not the tetrad tree. Remove the 'reference' individual from the tetrad tree and it will work.

+1
