### ISSUE TITLE
ipyrad - PE original RAD with reference 

### ISSUE THREAD

**Issue by ivan06513** [dereneaton/ipyrad#539]
Hi Isaac,

About the PE original RAD data, We've knew that those cases of denovo method should assembly with SE and ignore R2. 
https://ipyrad.readthedocs.io/en/latest/faq.html?highlight=original%20RAD#why-doesn-t-ipyrad-handle-pe-original-rad

But what if there is a great WGS reference genome? Could I assemble the PE original RAD data with pairgbs option or other approaches? 

Thank you very much!

**Comment by isaacovercast** [comment]
Hello,

Yes you could do this if you had a nice reference genome, that would probably work okay. My suspicion is that you will will have a lot of missing data in the parts of the loci covered by R2, so while it will probably 'work' it will also probably give you some missing data problems which could make downstream more difficult.

I would still say do R1 only _first_ and then do the reference assembly with both R1 and R2 so you have a baseline to compare it to. I think it's worth trying but the reference sequence isn't going to 'fix' the non-overlappingness of R2, so don't expect it to work a miracle. :)

Let me know how it goes.
-isaac
