### ISSUE TITLE
why prefix_outname parameter?

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#54]
This parameter seems necessary for the CLI so that users can name their output, but in the API we can just use the name of the Assembly object. Thus `data.name == data.paramsdict["prefix_outname"]` in most cases. We could formalize this by not providing prefix_outname as an API argument, and setting the CLI Assembly objects name with the params.txt argument prefix\_outname. 

Do you foresee any problems with this? Otherwise I'll go for it.

**Comment by isaacovercast** [comment]
Agreed. In my experience CLI users don't care about this param, i've seen more than one person who's used `c85d6m4p3` as the prefix_outname simply because that's what it is in the docs :D lol. If we can give a meaningful, consistent default for CLI users i'm sure they'll be happy.

**Comment by dereneaton** [comment]
good good. I'm killing it.
