### ISSUE TITLE
How to export toyplot.csv in Structure analysis ?

### ISSUE THREAD

**Issue by khorikhori** [dereneaton/ipyrad#540]
Dear my colleagues,

May I have a question ?
How to save bar data of Structure analysis as csv ? A right click does not work on jupyter notebook. 
A shift key with right click does not also work.  Google Chrome and Edge seem to have the same problem now.

Sincerely yours,

**Comment by isaacovercast** [comment]
Hello,
Do you want to save the bar plot as a csv (comma separated value)? You want to save the table of ancestry proportions? Or you want to save the _image_ of the bar plot as svg or png? If you want to save the image you can do something like this (see the [toyplot documentation for rendering](https://toyplot.readthedocs.io/en/stable/rendering.html):

```
import toyplot.pdf
toyplot.pdf.render(canvas, "figure1.pdf")

# or this
import toyplot.png
toyplot.png.render(canvas, "figure1.png")
```

**Comment by khorikhori** [comment]
Dear Mr. Issac,
Thank you very much for your suggestion. Yes, I already know the scripts of toyplot. png/svg/html, but I'd like to check 'magnitude' values. In rerun.get_clumpp_table, 4th decimal values of clummpps are not present (like 0.xxx, but clummps values are 0.xxxx) .  Alternatively,  I may copy and paste the magnitude values from 'clumpp.outfile' in the newst version now.
Sincerely,

**Comment by khorikhori** [comment]
Dear Mr. Issac,
I edited the previous comment. Bit sorry..

**Comment by isaacovercast** [comment]
Did you try exporting the data as csv using the pandas [to_csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html) function:
```
etable = struct.get_evanno_table([2, 3, 4, 5])
etable.to_csv("my_data.csv")
```

**Comment by khorikhori** [comment]
Dear Dr. Issac,

Thank you very much for your suggestion. The csv file is successfully exported.

Sincerely,
