### ISSUE TITLE
VCF output fails

### ISSUE THREAD

**Issue by TomaszSuchan** [dereneaton/ipyrad#543]
I'm getting the following error when trying to output vcf file. No issue when I remove vcf from ## [27] [output_formats] in the params file. It's Ubuntu 22.04.3 LTS on windows subsystem for linux if it makes any difference:

```
 -------------------------------------------------------------
  ipyrad [v.0.9.93]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Parallel connection | WS-02-LENOVO: 20 cores

  Step 7: Filtering and formatting output files
  [####################] 100% 0:01:31 | applying filters

  Encountered an Error.
  Message: EngineError: Engine b'ad1789f0-1a6d4501cfacddba85eb868a' died while running task '90af9baa-7514104a38f30120a124c9c9_2044614_41'
warning: error during shutdown:
[Errno 3] No such process
```

**Comment by isaacovercast** [comment]
EngineError is _almost_ caused by running out of RAM. How much ram is on your system? You can try reducing the number of cores (try '-c 10') to allocate more ram per core. That should solve it.

**Comment by TomaszSuchan** [comment]
Thanks, that worked just fine!
