### ISSUE TITLE
UnboundLocalError: local variable 'barcode' referenced before assignment

### ISSUE THREAD

**Issue by SerenaCaplins** [dereneaton/ipyrad#545]
Running ipyrad in a singularity container we keep running into this issue.
 -------------------------------------------------------------
  ipyrad [v.0.9.93]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Parallel connection | c0649: 28 cores

  Step 1: Demultiplexing fastq data to Samples
  [####################] 100% 0:31:03 | chunking large files
  [                    ]   0% 0:00:04 | sorting reads
  Encountered an Error.
  Message: UnboundLocalError: local variable 'barcode' referenced before assignment
Error: ipcluster shutdown and must be restarted

**Comment by isaacovercast** [comment]
Can you post your params file please?

**Comment by SerenaCaplins** [comment]
Hi Isaac, 

We were missing the cut overhang. Everything is working great now. You can close this issue. 

Cheers, 
Serena

**Comment by isaacovercast** [comment]
Ok great, thanks for letting me know. +1
