### ISSUE TITLE
Merging libraries of different read lengths

### ISSUE THREAD

**Issue by spilornis-ng** [dereneaton/ipyrad#547]
Hi this is a doubt and not an issue. We had generated ddRAD data for ~400 samples targeting 100x2 reads last year, however, we got less than expected depth for several samples. We eventually decided to generate additional data for the same libraries, but this was done on a 150x2 flowcell (the company didn't inform us before sequencing, even though we asked for 100x2 flowcell). We are now wondering if we can merge assemblies across 100x2 and 150x2 datasets for the same samples in ipyrad? also, what could be the potential issues in doing this?

PS: I have posted this on gitter as well. Really looking to get some feedback on this!

**Comment by isaacovercast** [comment]
Yes, you can do this, _assuming_ that they used the same enzymes and size selection. You can just merge them and run them both together without modification to see how it looks, or alternatively you could merge them after step 1 and then use `trim_reads` to trim everything down to 100bp. I guess it depends on how things look and how much overlap there is between the new and old datasets. Let me know how it goes if you have any questions.
