### ISSUE TITLE
Ipyrad excluding samples during demultiplexing stage

### ISSUE THREAD

**Issue by ikb001** [dereneaton/ipyrad#548]
My dataset includes two 96 well plates containing 185 samples in total. I had a single barcode file which was supposed to be used in demultiplexing both plates so I modified the barcode file to include sample names for the specific plates. Ipyrad then ran the demultiplexing stage and excluded 98 samples from my dataset saying there was no match for those samples. Kindly find attached the barcode files used in demultiplexing my reads.
[GBS_barcodes.ApeKI-1-96-A.txt](https://github.com/dereneaton/ipyrad/files/14461764/GBS_barcodes.ApeKI-1-96-A.txt)
[GBS_barcodes.ApeKI-1-96-B.txt](https://github.com/dereneaton/ipyrad/files/14461765/GBS_barcodes.ApeKI-1-96-B.txt)

I would be glad if any help or advice could be offered to me in making sure this does not occur again especially when I merge them finally.

**Comment by isaacovercast** [comment]
Did you run each plate in ipyrad step 1 independently? I assume so.

Can you post the s1_*.txt stats files from each of the _fastqs directories?

**Comment by ikb001** [comment]
Yes, I did. I have attached copies of the s1 stats files to my reply.
[s1_demultiplex_stats - B.txt](https://github.com/dereneaton/ipyrad/files/14462047/s1_demultiplex_stats.-.B.txt)
[s1_demultiplex_stats-A.txt](https://github.com/dereneaton/ipyrad/files/14462050/s1_demultiplex_stats-A.txt)

**Comment by ikb001** [comment]
Thank you very much for this insight! I think the error may have happened in the process of me copying the barcodes. I have since corrected that for plate A. For Plate B, I am not quite sure what the issue might be either. But I am repeating the step to see if it turns out the same. I will update the thread on the outcome. Thank you!

**Comment by ikb001** [comment]
properly structuring the barcode files worked. Thank you very much for the help.
