### ISSUE TITLE
Popgen summary statistics fails when using imap

### ISSUE THREAD

**Issue by zwuckl** [dereneaton/ipyrad#550]
Hey guys. I've successfully assembled ddRAD loci of some >170 plant samples with ipyrad. As part of the analysis, I stumbled upon your cookbook on the "ipyrad-analysis toolkit" (https://ipyrad.readthedocs.io/en/stable/API-analysis/cookbook-popgen-sumstats.html).

When running popgen without any imap like this...

    popgen = Popgen(data=data)
    popgen.run(ipyclient=ipyclient)

... it takes a while but finishes successfully and outputs values for "pop1".

However when supplying even the simplest imap with only two populations such as...

    imap = {"uk"       : ["40002","40019","40031","40032","40033","40034"],
            "germany"  : ["40003","40004","40005","40006","40007","40008","40009","40010","40029","40040"]
           }

    popgen = Popgen(data=data, imap=imap
    popgen.run(ipyclient=ipyclient)

the run returns with the following error:

```python
Parallel connection | mosscompute: 24 cores
[locus filter] full data: 207219
[locus filter] post filter: 69502
[####################] 100% 0:00:05 | Calculating sumstats for nloci 69502 

Encountered an Error.
Message: IPyradError: Malformed locus idx: 71
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File /scratch/micromamba/envs/ipyrad/lib/python3.10/site-packages/ipyrad/analysis/popgen.py:457, in Processor.run(self)
    456 try:
--> 457     cts, sidxs, length = self._process_locus(
    458                                 locus.loc[locus.index.intersection(self.imap[pop])])
    459 except Exception as inst:

File /scratch/micromamba/envs/ipyrad/lib/python3.10/site-packages/ipyrad/analysis/popgen.py:519, in Processor._process_locus(self, locus)
    518 # Only consider variable sites
--> 519 snps = np.array([len(x) for x in cts]) > 1
    520 # Indexes of variable sites

File /scratch/micromamba/envs/ipyrad/lib/python3.10/site-packages/ipyrad/analysis/popgen.py:519, in <listcomp>(.0)
    518 # Only consider variable sites
--> 519 snps = np.array([len(x) for x in cts]) > 1
    520 # Indexes of variable sites

TypeError: object of type 'numpy.float64' has no len()

During handling of the above exception, another exception occurred:

IPyradError                               Traceback (most recent call last)
File <string>:1

File /scratch/micromamba/envs/ipyrad/lib/python3.10/site-packages/ipyrad/analysis/popgen.py:412, in _calc_sumstats(params, start_lidx, loci)
    409 def _calc_sumstats(params, start_lidx, loci):
    410     # process chunk writes to files and returns proc with features.
    411     proc = Processor(params, start_lidx, loci)
--> 412     proc.run()
    414     with open(proc.outfile, 'wb') as outpickle:
    415         pickle.dump(proc.results, outpickle)

File /scratch/micromamba/envs/ipyrad/lib/python3.10/site-packages/ipyrad/analysis/popgen.py:460, in Processor.run(self)
    457     cts, sidxs, length = self._process_locus(
    458                                 locus.loc[locus.index.intersection(self.imap[pop])])
    459 except Exception as inst:
--> 460     raise IPyradError("Malformed locus idx: {}".format(lidx))
    462 # Number of segregating sites
    463 S = len(sidxs)

IPyradError: Malformed locus idx: 71
```

Do you have any idea what's happening here? 
Or is there some example data that's supposed to run cleanly that I might test? 

Any help is much appreciated :)

Thanks
Nico

**Comment by isaacovercast** [comment]
Hi Nico,

The popgen-sumstats module is still pre-alpha at the moment. I would love for it to be working eventually, but it's not on my priority list right now. I would suggest using vcftools with the .vcf file output from ipyrad, this will get you most of the standard sumstats like Ho/He, pi, and fst.

Hope you're doing well,
-isaac

**Comment by isaacovercast** [comment]
@zwuckl There's not really a way to do that, that I am aware of, unfortunately. The ipyrad analysis tools are just a wrapper around structure, so if you can figure out a way to get the info you want from the structure output files I might be able to tell you how to get that out of the ipyrad analysis results, but no guarantees.

Since this is now a different topic i'm going to close this particular issue. If you want to chat more about the structure results feel free to open a new issue or better just hop on our gitter channel:

https://app.gitter.im/#/room/#dereneaton_ipyrad:gitter.im

-isaac
