### ISSUE TITLE
"1" ("2") instead of "_R1_" ("_R2_) in .fq data files

### ISSUE THREAD

**Issue by jesus-mavarez** [dereneaton/ipyrad#553]
Hi.
I tried to run the first step in a ipyrad analysis with paired-end data, but I got this message.

  Step 1: Demultiplexing fastq data to Samples
  Encountered an Error.
  Message: First read files names must contain '_R1_'.

I checked the data and there no _R1_ (neither _R2_) in sequence names. Is there a way to solve issue this directly in ipyrad?

Thanks in advance

**Comment by isaacovercast** [comment]
For paired-end data the raw files will normally be named like this: xxxxxxxxxxxxxxxxxxxx_R1_.fastq.gz and xxxxxxxxxxxxxxxxxxxx_R2_.fastq.gz, to distinguish the forward and reverse reads. Sometimes the files will have different naming schemes like xxxx_1_fastq.gz (which is the most common alternate, but still is rare). This message from ipyrad is saying that _your_ raw data files do not contain `_R1_` in the filename, so ipyrad doesn't know how to identify the forward reads. You need to rename your raw data files so the file names include `_R1_` in the forward reads and `_R2_` in the reverse. Let me know how it goes.

**Comment by isaacovercast** [comment]
Closing this as stale. If you're still having problems reopen it.
