### ISSUE TITLE
iPyrad CLI tutorials (ABBA/BABA tests, Structure, treemix, etc)

### ISSUE THREAD

**Issue by jesus-mavarez** [dereneaton/ipyrad#555]
Hi Isaac
I've been struggling a bit with the API tutorials for ABBA/BABA tests, Structure, etc. in iPyrad. Don't worry, that comes from my lack of experience using Jupyter notebooks more than anything else. So, I wonder whether there are as well some command-line tutorials available for those types of analyses in iPyrad.
Best wishes
Jesús

**Comment by isaacovercast** [comment]
Hello Jesus,

The ipyrad analysis tools are only available in API mode, so unfortunately there is no CLI interface to these. The notebook APIs take a little getting used to, but once you get the hang of it you'll see that they are powerful. Good luck!
-isaac
