### ISSUE TITLE
ipyrad v.0.9.94/95  frozen at the beggining 

### ISSUE THREAD

**Issue by ospfsg** [dereneaton/ipyrad#558]
Hi
I installed ipyrad v.0.9.94/95 in  HPCs and in a  new workstation with 64 cores and Ubuntu 22.04. These versions are installed and run in older servers, that already run older versions of ipyrad but it the new workstation it frozen at the beginning of the run.  The cursor keep blinking after the first lines  but nothing happen and the number of cores don't show as usual. 

-----------------------------------------------------
ipyrad [v0.9.95]
Interactive assembly and analysis of RAD-seq data
-------------------------------------------------------------------

The Python 3.10.12 is installed  but something seems to be missing in the system or in conda.

Can  you help with this?
Osp

**Comment by ospfsg** [comment]
Hi
the command is this:   ipyrad -p params-lim_20240404.txt -s 1234567

I check with htop and there were several ipyparallel.engine.nany

with -c 8 it run!!!

Thank you very much 

osp

ps: Unfortunately I never had this problem before  our older servers have only 16 cores !!!

**Comment by isaacovercast** [comment]
Glad it works! I have found that with large numbers of cores available on a computer this same behavior, where it stalls out trying to access all cores, but works better when you subset cores with -c. Glad it's working for you :)

**Comment by ospfsg** [comment]
Hi
the command is this:   ipyrad -p params-lim_20240404.txt -s 1234567

I check with htop and there were several ipyparallel.engine.nany

with -c 8 it run!!!

Thank you very much 

osp

ps: Unfortunately I never had this problem before  our older servers have only 16 cores !!!
