### ISSUE TITLE
Ipyrad running on cluster, but not creating .json file or folders

### ISSUE THREAD

**Issue by avculley** [dereneaton/ipyrad#567]
I was able to get ipyrad to run to step 3 on a dataset and then it suddenly stopped working and said the job was "running" on the cluster, but was no longer creating any new files for days. Now, everything is not working- my job will be running on the cluster, but no .json file is even produced. My error and out files are empty and show nothing. I should have plenty of storage for all steps. I have even tried starting completely over and I keep ending up in the same situation where my job is running on the cluster, but nothing is working- leaving me with blank .out and .err files and no .json file created. Does anyone have any suggestions on what could be causing this? I am using a test dataset that someone else has ben able to run through step 7 on, so I know it is not an issue with the data.

**Comment by isaacovercast** [comment]
What step are you trying to run? Are you trying to run step 3 again or starting from scratch? Can you show me your job submission script? You could try [running in an interactive job](https://ipyrad.readthedocs.io/en/latest/HPC_script.html#running-interactive-jobs) on the cluster to see what's happening.

It also might be a problem with timing in [launching the ipcluster process on HPC systems](https://ipyrad.readthedocs.io/en/latest/HPC_script.html#optional-controlling-ipcluster-by-hand), so you could try running it by hand in the job submission script.

**Comment by isaacovercast** [comment]
Any updates here? Is this working now? It sounds like an HPC issue. If this is still happening and you can provide more information please reopen this issue, otherwise I'll close it as stale.
