### ISSUE TITLE
Refseq mapping - PE don't rev or comp when merging mapped reads

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#57]
`samtools view` automatically revcomps R2, so disable this on merge_pairs(), or at least handle it right....

**Comment by isaacovercast** [comment]
vsearch definitely assumes the rev seq is on the reverse strand, so r2 mapped reads will need to be revcomped before going into merge_pairs()

**Comment by dereneaton** [comment]
man this stuff is confusing. This is what I've figured out:

vsearch merge_reads R2 should **not** be revcomped
after that we concat non-merged reads and R2 should be revcomped

**Comment by isaacovercast** [comment]
Finally nailed this. R2 should _not_ be revcomped before mapping, added a 'revcomp' flag to merge_pairs to allow some flexibility around this.
