### ISSUE TITLE
problem with merging option on command line

### ISSUE THREAD

**Issue by jesus-mavarez** [dereneaton/ipyrad#573]
Hi
I've been trying to merge two ddRAD libraries in iPyrad but, unless I'm wrong, without success. I started by running option s1 on a first library (Espeletia_1), then again option s1 on a second library (Espeletia _2). And then option m to create a new file, Espeletia, from the merging of the two initial ones. Everything seems to work OK. But when I check this new merged file I see that none of the individuals from the second library had reads that passed the filter (see below). 

Do you have an idea about what might be going on?

Thanks in advance
Jesús

  
Summary stats of Assembly Espeletia
------------------------------------------------
                 state  reads_raw  reads_passed_filter
annemariana          2     947128               943362
arbelaezii           2     440018               438224
argentea             2     693795               690925
azucarina            1    1138253                    0
barclayana           2    2613124              2603714
betancurii           2    2019315              2013509
boyacensis           2    3283039              3270871
brachyaxiantha       2     367765               366800
brassicoidea         2    1009922              1006381
cachaluensis         1    1423092                    0
caldasii             1    1134917                    0
cayetana             1    3797915                    0
chocontana           1    2248113                    0
cleefii              1     956079                    0
colombiana           1    1805740                    0
congestiflora        2    2007420              2001116
conglomerata         1     516603                    0
corymbosa            2    2159517              2153151
curialensis_Mo       2    3262190              3248883
curialensis_Pi       2    2368378              2360658
discoidea            1     209145                    0
dugandii             1     674698                    0
episcopalis          2    1280497              1276227
estanislana          1     216251                    0
funckii              1     897898                    0
garciae              2    2659343              2649519
glandulosa           2    1106622              1101259
grandiflora_Cg       2     561809               559791
grandiflora_Ru       2    3081000              3069182
grandiflora_Su       2    2792671              2783999
guacharaca           2    1101778              1097202
hartwegiana          1    1616675                    0
hirbana              1    3399743                    0
incana               2    1898196              1892411
insignis             1    1475116                    0
jaramilloi           2    1353394              1348177
....

**Comment by isaacovercast** [comment]
Hello, It looks like you did everything right and that the merge worked, but it looks like you ran steps 1 AND 2 on this first assembly. You can see from the stats that all the samples from the second library are in state 1 (which means they completed step 1) and the samples from the first library are in state 2 (which means the completed step 2). You can run step 2 on the merged assembly and it will complete step 2 only for the samples in state 1 (it won't redo step 2 for the samples form the first library).
