### ISSUE TITLE
Individual loci sequence & alignment files

### ISSUE THREAD

**Issue by Ruiqi-CUB** [dereneaton/ipyrad#574]
Dear Isaac,

Thanks for the awesome pipeline! 

Is it possible to get individual loci sequence & alignment files? Should I just seperate the file in RunName_outfiles/Run_Name.loci using `// ... ... |Number|` between the loci sequence. 

I am asking because I would like to use the loci presented in 50%, 70% and 90% of samples to reconstruct the phylgeny respectively to test the robustness. 

Or is there any built-in function in ipyrad to do it?

Thanks
Ruiqi

**Comment by Ruiqi-CUB** [comment]
or is it possible to branch at step seven only change parameter [min_samples_locus]? Thank you!

**Comment by isaacovercast** [comment]
It is exactly possible to do that! Thats the use case we designed for, so
youre spot on.

If you want to split the loci file to infer gene trees per locus, how you
suggest is how i'd do it, there isnt an automated way to get files for each
locus alignment.

**Comment by Ruiqi-CUB** [comment]
That's great! Thank you! But the tutorial "Assembly: Branching and Merging" only shows how to add/drop samples. Is there a tutorial for how to branch and change  [min_samples_locus] at step 7? or would you mind help pointing it out to me how to do it?

**Comment by isaacovercast** [comment]
You can simply create new branches for different min_samples thresholds and then change the values in the new params files.

```
ipyrad -p params-old.txt -b minsamp20
ipyrad -p params-old.txt -b minsamp40
ipyrad -p params-old.txt -b minsamp60
```
Then you'll have 3 new params files and you can edit the min_samples accordingly and then run step 7 on each.

**Comment by Ruiqi-CUB** [comment]
Thank you! Let me try!
