### ISSUE TITLE
recommended clust_threshold

### ISSUE THREAD

**Issue by Ruiqi-CUB** [dereneaton/ipyrad#575]
Hi Issac,

Hope you are well! 
I understand that the default value for clust_threshold is 0.85, and you do not recommend using any value higher than 0.95. What is the lowest value that you would recommend? 

I am using it at a family level dataset. The oldest node is definitely less than ~80 MYA. There are some recent divergent lineages. 0.85 did gave us a pretty good results, but I think the "normal" practice is to try some different clust_threshold to test robustness (please correct me if I am wrong). I am thinking about using 0.85, 0.9, and 0.95 now. Do you think I should also try some lower values?

Thanks
Ruiqi

**Comment by isaacovercast** [comment]
For step 3 between 85 and 95 are good. You can change clust_threshold at step 6 to account for deeper divisions among samples, but I wouldn't mess with anything lower than 80. Even 85 is low imho, but experiment with different values. Good luck!

**Comment by Ruiqi-CUB** [comment]
Thank you! I will definitely try them!
For branching, shouldn't I change clust_threshold at step 3 instead? or if I use a lower value then I will be able branch with different clust_threshold at step 6? 

Also, could you please check if my understanding is correct? For early divergent species, I should lean toward lower clust_threshold since there should be more mutations etc between homologous loci. For recently divergent lineages, I should use a higher clust_threshold since there is less SNPs.

**Comment by isaacovercast** [comment]
Step 3 is _within_ sample clustering, so this is more based on within species heterozygosity, so the clust_threshold should be chosen based on this, step 6 is about _across_ samples clustering, so I think it's more justifiable to use lower values at step 6 than at step 3, but ymmv.

In general your understanding that you ask about is correct.

**Comment by Ruiqi-CUB** [comment]
Thank you! That makes sense. 
I was wondering if you could check my understanding on [min_samples_locus]:
1. High [min_samples_locus] (>50%?): recovers more conservative loci, it's best for inferring relationships at "deep nodes" (early divergent events) 
2. Low [min_samples_locus](~20%): also recovers "novel" (lineage specific) loci, it's best for resolving recent divergent lineages (shallow nodes)

**Comment by isaacovercast** [comment]
Your understanding is more or less correct. In general higher min_samples_locus will recover more conserved loci, but whether this is 'better' for resolving deep or shallow nodes is an open question. It seems reasonable to think this, but I don't think anyone has proved it yet.
