### ISSUE TITLE
Make data.statsfiles an ObjDict w/ Pandas DF stats for each step

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#58]
Right now we have data.stats building from Sample stats. But for each step there are also a bunch of statistics which we write to file but do not link to Sample objects. I'm thinking we could instead save these in a more verbose Pandas DataFrame for each Sample, and build a Summary across samples the same way we do for .stats. 

This would require changing the `cleanup()` code so that instead of formatting stats to look nice when printed we simply let Pandas do that for us. So each sample has its stats for each step as a dict and the Assembly object builds a DataFrame as a @property of the Samples. 

This has the advantage that all of the stats data is available to API users, and also that we can save the stats to file easily with e.g., data.statsfiles.s1.to_csv("s2_rawedit_stats.txt)`. It's cleaner.

This won't work for all steps, though. Step1 output is mostly not DataFrame friendly, nor is step7 output. But we could save parts of it to Samples at least. 

```
## see summary of main stats
data.stats

## see summary of stats for each step
data.statsfiles.s1     
data.statsfiles.s2 
...etc.
```

**Comment by isaacovercast** [comment]
That's funny, i was totally just thinking the exact same thing.
