### ISSUE TITLE
Why is the max heterozygotes parameter default so low?

### ISSUE THREAD

**Issue by ottoau** [dereneaton/ipyrad#580]
I am running ipyrad on RADseq data I've compiled on grasshoppers of closely related species. After running ipyrad and SNP filtering I am left with a very low amount of SNPs (~40) so I've been editing different parameters to see if I can recover more usable data. 

One of the parameters I am  considering altering is the max_HS_consens or the maximum percentage of heterozygotes in a consensus. I am wondering why this is set to 0.05 allowing only 5% heterozygotes. Does this mean that only 5% of individuals can be heterozygotic for a given site or it will be filtered out? If I were to increase this would it possibly lead to more usable SNPs? What would a reasonable range for this parameter be?

Thanks in advance!

**Comment by isaacovercast** [comment]
max_Hs_consens limits the number of shared heterozygous sites across all samples within a given locus. The intent is to control paralogs, which can be indicated by an inflated number of shared het sites. You can increase this if you want but I don't think it will have the desired effect. How many snps are you starting with in step 7 and what are the values of the filters applied in the *_stats.txt file in the outfiles directory?

What is the min_samples_locus you're using, this is often a much stronger filter that people tend to set too high.

**Comment by ottoau** [comment]
Hi Isaac,

Thanks so much for your response! In step 7 I started with 465737 SNPs and at the end of step 7 was left with 2310 SNPs. The parameters were mostly defaults but I set the minimum samples per locus to 75% of individuals (120/160) and the clustering threshold was set to 0.9. Filter adapters was set to 2 to remove Illumina adapters. This is for a paired end ddrad denovo analysis. 

Since the first run I have been testing different parameters to see if I can increase the output of SNPs I am able to get. I decreased the clustering threshold from 0.9 to 0.85 and decreased the minimum samples per locus to 50% of samples. The best result I have gotten so far was achieved by updating the above parameters as well as reducing the minimum depth marj rule from 6 to 3 while keeping min depth statistical at 6. Would 3 be a reasonable number for that parameter or would it compromise the quality of my data? By making this change I was able to recover an adequate amount of SNPs after filtering. 

Thanks again!

**Comment by isaacovercast** [comment]
I would say that 3 is very low for min_depth_statistical and could compromise the quality of the data. I think setting min_samples_locs to 50% will have by far the biggest effect on the output snps. I wouldn't manipulate clust_threshold to return more loci, I would leave it at 0.9.

**Comment by ottoau** [comment]
Okay, I will see what happens when I apply those parameters. Thanks again!

**Comment by isaacovercast** [comment]
+1

**Comment by ottoau** [comment]
Hi @isaacovercast. Thanks again for your help. I have another question if you don't mind. I followed your suggestions, but was not able to recover as many SNPs as I did by lowering the min_depth_marj_rule. I know you said 3 is very low but would 4 or 5 be reasonable? You also said the quality of data could be negatively affected by setting this number too low, but do you know how exactly the data would be affected? Thank you in advance!

**Comment by isaacovercast** [comment]
4 or 5 are also still quite low. "Reasonable" is about what kind of uncertainty and error you are willing to tolerate. With min_depth < 6 it increases the probability of miscalled bases, so there will be more errors interpreted as true signal, and more true snps removed as error. It's hard to quantify the exact effect, but that would be the mechanism of it.

**Comment by ottoau** [comment]
That makes sense. Thank you so much for explaining!
