### ISSUE TITLE
Python integer 69530 out of bounds for uint16

### ISSUE THREAD

**Issue by amesclir** [dereneaton/ipyrad#581]
Dear Eaton and Overcast,

I got an error in the step7 and it does not generate the output files.
Do you know what this might be?

Thanks!
Marcial

(base) [aescudero@login3 datura]$ cat ipyrad_datura2.log
  loading Assembly: datura2
  from saved path: /lustre~/radseq/datura/datura2.json

 -------------------------------------------------------------
  ipyrad [v.0.9.96]
  Interactive assembly and analysis of RAD-seq data
 ------------------------------------------------------------- 
  Parallel connection | nodo1014: 24 cores
  
  Step 6: Clustering/Mapping across samples 
  [####################] 100% 0:00:21 | concatenating bams     
  [####################] 100% 0:00:08 | fetching regions       
  [####################] 100% 0:00:16 | building database      
  
  Step 7: Filtering and formatting output files 
  [####################] 100% 0:00:12 | applying filters       

  Encountered an Error.
  Message: OverflowError: Python integer 69530 out of bounds for uint16
  Parallel connection closed.
(base) [aescudero@login3 datura]$

**Comment by isaacovercast** [comment]
Hello Marcial,
This is fixed in the most recent version of ipyrad, please update and try again and I'm sure it will work.
All the best,
-isaac
