### ISSUE TITLE
No Progress in analysis

### ISSUE THREAD

**Issue by Zombiekotze** [dereneaton/ipyrad#582]
Hello,

i'm new to ipyrad and i startet with the tutorial after installation. Everything worked fine, but when running ipyrad

```
(base) workstation@workstation:~/Dokumente/1_Test$ ipyrad -p params-iptest.txt -s 1

-------------------------------------------------------------
ipyrad [v.0.9.102]
Interactive assembly and analysis of RAD-seq data
-------------------------------------------------------------
```

nothing happens anymore, it seems not loading anything. I left it overnight, but also in the next morning no progress took place. There is no error message or anything which tells me, what could be wrong.

Cheers
Rob

**Comment by isaacovercast** [comment]
Sometimes it helps to specify the number of cores with `-c`. If u dont specify -c it will default to all cores and sometimes this causes the process to hang. Try setting -c to a few cores leas than the total on the machine
