### ISSUE TITLE
Issue with Indel Filtering When Merging GBS and ddRAD Datasets in ipyrad

### ISSUE THREAD

**Issue by aleferreiro** [dereneaton/ipyrad#585]
Hello,

I am working on merging two reduced representation genomic datasets using ipyrad version 0.9.95. One dataset comes from GBS, and the other from ddRAD. Both datasets have overlapping cut sites but reads of different lengths.

After merging the datasets, we observed an issue in the resulting alignment:

Shared loci between samples show indels at the beginning or end of the reads. These indels seem to arise as a result of the different read lengths between datasets.

In the final, alignment, we have seen that many locis have very long gaps at the end of loci. We wanted to filter this loci by applying the max_Indels_locus = 0 parameter to filter out loci with indels. However, the filter appears to only remove loci with internal indels and does not account for those located at the ends of the reads, as these loci remain in the results.

Would it be that the filter is only applied to gaps in the middle of sequences and not to gaps at the ends of the alignment?

Thank you for your help!

**Comment by isaacovercast** [comment]
Hello,
Yes the max_Indels_locus filter only counts internal gaps. This is probably coming from sequences from the different datasets 'tiling' (partially overlapping) so that there is sequence representation in some samples but not others. Hope that helps!

**Comment by isaacovercast** [comment]
There is not a good way to filter terminal indels, unfortunately. Your filter_min_trim_len strategy makes sense.

Thanks for the suggestion, I have modified the documentation explaining this paramter:

https://github.com/dereneaton/ipyrad/blob/master/newdocs/6-params.rst

Hope you're doing well,
-isaac
