### ISSUE TITLE
Rename binaries in ipyrad/bin dir

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#6]
I think it might be better to rename the binaries in the ipyrad/bin dir to 'muscle_osx', 'vsearch_osx', 'smalt_osx', 'samtools_osx', etc..., simplify the naming scheme. We already know we're testing against 32bit arch, and we don't really care about the version, it's just another string to keep track of. There was a bug in the path to the binaries inside the assemble.py file that tripped an assert on macs (bad filename for vsearch). Seems like since we are in control of which binaries are in this directory if we want to update a binary we can copy it in with the the standard simple name we want, this prevents weird file name errors in the future.. just a thought.

**Comment by dereneaton** [comment]
That sounds fine to me. I expect we will not update them very frequently once we settle upon a good working version.

**Comment by isaacovercast** [comment]
oof, this got annoying, so i fixed it. I made symlinks inside the bin directory to each of the binaries. Figure it might be useful to retain the binary names that include version number, so i'm making symlinks in the bin directory that have generic names like 'vsearch-linux-x86_64', that point to the originals. Changed code inside core/assembly.py to point to the generic symlinks.
