### ISSUE TITLE
Step 7 - shared het filtering - how to deal w/ PE separator

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#60]
It might be better to use some character that's not a valid fasta/iupac ambiguity code, maybe underscore _ or ??? Filtering out shared heterozygous sites is going to misbehave unless the "SSSS" is cut or changed, or unless it's split out and each read is dealt with separately, which I don't really want to do.

**Comment by dereneaton** [comment]
This was a hack. I used to use xxxx, but upon updating to vsearch it crashed b/c it wouldn't accept X as a character. I'm not sure if the newest vsearch allows non IUPAC codes, but it does preserve lower case lettering now, so we could put 'ssss' in there.

**Comment by isaacovercast** [comment]
What if i search and replace "SSSS" to "xxxx" in unmerged PE at the beginning of step7, after vsearch has touched it it shouldn't matter right?

**Comment by dereneaton** [comment]
I'll work on replacing the consens base call in step5 so it outputs ssss. Otherwise the danger is that there might actually be a string of four S characters in a sequence and it would be mistaken for a split. Step 7 can then replace ssss to xxxx, if necessary.

**Comment by isaacovercast** [comment]
its nnnn now
