### ISSUE TITLE
Step7 - How to filter PE R1 and R2 individually if they've been merged?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#61]
D: I have no idea how this would work.

**Comment by dereneaton** [comment]
I think we'll have to treat it as an R1 read.

**Comment by isaacovercast** [comment]
One hack idea: what if we split merged reads in half and filtered using R1 and R2, it's hackish but it's more consistent. If there's merged and unmerged PE reads and there were R1 and R2 filters then merged reads would be subject to much more restrictive filtering.

Oooh, how about for merged reads you use R1+R2 filters. Again it's a little hackish, but maybe more of a forgivable sin.

**Comment by isaacovercast** [comment]
fixed.
