### ISSUE TITLE
Step3 - PE R2 comp vs revcomp into vsearch

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#62]
Looks like the orientation is right in the revcompR2.fastq, but then it's reversed (with AATT at the beginning) in .merged_.fastq

It looks like vsearch --fastq_mergepairs is internally reversing R2 passed in at the --reverse flag.
Since cluster_within is already doing a vsearch --revcomp right before that it explains why the merged R2 are on the correct strand, but reversed. I think the fix to this is to not revcomp r2 before --fastq_mergepairs, but instead to simply comp() R2, and let vsearch do the rev. I want to get your thoughts on this before i make any change here..

**Comment by dereneaton** [comment]
The orientation of R2s is now done correctly for merged and unmerged reads. Tested on Cythophora paired GBS data set.
