### ISSUE TITLE
Log file permissions

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#67]
We need to be sure every assembly has it's own log file. Shared logging with multiple users on a system wouldn't be ideal. Logs should go in the working directory so users have ready access to them, maybe.

Running as a different user on my box i get:
`Unable to configure handler 'ipyrad': [Errno 13] Permission denied: '/tmp/ipyrad_debug.txt'`

**Comment by dereneaton** [comment]
In that case it doesn't seem like we need a log to be saved in the .assembly Object (`_stamp()` function), but rather just in a logfile that is saved alongside it. Then we could use that file for both user logs as well as to print logging to when we are debugging. Since debugging will be set to `ERROR` for users, it could still print errors that cause crashing for them to see, which is fine.

**Comment by isaacovercast** [comment]
what if in `__init__` we just change `'filename':'/tmp/ipyrad_debug.txt',` to `'filename':'./ipyrad_debug.txt',`, just drops the logfile to wherever you're running it?

**Comment by dereneaton** [comment]
I'm cool with that. But what do you think about the log file? Is the debugger also going to be a log file for users? Do we need to make a log file for users? Or should the debug file never write when users are using? I'm still thinking that having a logfile saved within .assembly files doesn't make much sense. 

If people use the API they don't need a log file, all of their code is right in front of them. But for CLI users it could be useful to spit something out that reminds them what their param settings were when they ran something. Thoughts?

**Comment by isaacovercast** [comment]
Set a hackersonly flag to turn on or off the log file.

**Comment by dereneaton** [comment]
I set for `__init__.py` to use `./ipyrad_debug.txt` as the log location if `/tmp` raises a ValueError due to permissions. Not sure if this is ideal long term, but it avoids any errors from arising.
