### ISSUE TITLE
step1() - handle multiple barcodes files?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#71]
More and more people are getting more than one plate of data. It might take some serious thinking to handle more than one barcodes file, maybe it would be more trouble than it's worth and we should just document a good workflow.

**Comment by dereneaton** [comment]
Yeah, I say we recommend a workflow of creating two different Assembly objects and running some kind of merge command. This is already possible through link_fastqs (below), but could be simplified with an explicit ip.merge func which could be more careful in testing that the names match up, etc. 

```
## set data1 to path1 data
data1 = ip.Assemble('data1')
data1.set_params('barcodes_path', '...')
data1.set_params('raw_fastq_path, '...')

## set data2 to path2 data
data2 = ip.Assemble('data2')
data2.set_params('barcodes_path', '...')
data2.set_params('raw_fastq_path, '...')

## demultiplex both into separate dirs
data1.step1()
data2.step1()

## append data2 fastqs to data1 samples.
data1.link_fastqs(path="data2_fastqs/*.fastq.gz", append=True)
```

**Comment by dereneaton** [comment]
Something that would be nice though is being able to demultiplex combinatorial barcodes. I don't think this would be very hard, I just haven't had access to any raw data yet that uses this type of barcoding... maybe I can put out some feelers and see if someone will send me some.

**Comment by dereneaton** [comment]
We now support combinatorial barcodes in the form of 3RAD. We support barcodes with ambiguous bases. And we support merging of assemblies created with different barcodes files.
