### ISSUE TITLE
Step 3 - Empty utemp file from vsearch chokes build_clusters()

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#72]
Not sure yet why vsearch would return an empty userout file, but if it does build_clusters errors out with an IndexError. Nasty to debug. More info when i figure out why utemp would ever be empty.

**Comment by dereneaton** [comment]
If every sequence is a seed and there are no matches then utemp will be empty. I suppose this could happen if you're using preview and grab too few sequences.

**Comment by isaacovercast** [comment]
That's exactly what happened. Seems unlikely to come up in reality. I added a note to clarify why this might happen in the sys.exit() that tests for zero length. I think that's best we can do.

**Comment by isaacovercast** [comment]
You're probably right, that makes sense, i was actually thinking about handling it that way.

**Comment by isaacovercast** [comment]
What's the most graceful way to handle that? Just returning from build clusters will probably not work, all the downstream stuff inside cluster_within will not be happy. Is there a graceful way to exit from an ipclient task?

**Comment by dereneaton** [comment]
After spending an entire day on it, my conclusion is that you can't (or it's not clear how to) raise an Exception within the Engines and try to catch it outside of them while leaving the Engines alive. If you want them to fail gracefully we need to catch exceptions inside the function running on the remote engine and use this to work around completing the function quickly as a way to fail gracefully. 

I have it working now for 'denovo'-mode in step3. If there is no utemp file it raises an exception within `clustall` which is caught in `split_among_processors`. I use the sample.state to keep track of how far it has succeeded in the process. If it fails to build a clust file it is left in state=2, and thus it does not proceed to alignment and cleanup. 

This seems like the easiest way to let Samples fail.
