### ISSUE TITLE
step 6 - fails on sim and real gbs data

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#75]
```
WARNING:ipyrad.assemble.cluster_across:Can't broadcast (100, 94, 150) -> (76, 94, 150)
Error: Can't broadcast (100, 94, 150) -> (76, 94, 150)
File "/usr/local/opt/anaconda/lib/python2.7/site-packages/ipyrad-0.1.18-py2.7.egg/ipyrad/assemble/cluster_across.py", line 185, in multi_muscle_align
    dset[start:start+tup[2]] = tup[1]
```
Seems similar to the earlier error with maxlen not being long enough, but i can't parse that well what cluster_across() is trying to do here.

**Comment by dereneaton** [comment]
I _think_ it's b/c the chunk size is hardcoded to 100 which works for sim data that is multiples of 100, but not for real data yet. I'll put some work into cluster_across tonight and tomorrow to get it up to snuff.

**Comment by isaacovercast** [comment]
Ooh you nailed it.

**Comment by isaacovercast** [comment]
I see two problems, or maybe one problem with two facets. Theres a disconnect between the temp file names created by build_reads_file() and what multi_muscle_align expects them to be for indexing into the indels hdf5 file. It looks like the first tmp file should be named tmp_0 and the second should be named tmp_100, the file name post-fix is the start index into the indels and the nloci should be the number of loci in the file.

Right now on the sim data my first tmp file is called tmp_100, and the second one is also called tmp_100. It seems like multi_muscle_align has the right idea, but the file names getting written out aren't meshing... Working on it..

**Comment by isaacovercast** [comment]
I fixed the first problem, but there's another. currently singlecat() and build_catg_file() get their nloci values from different spots. build_catg_file() gets nloci passed in from the result of build_reads_file(), and singlecat() reads in directly from sample.stats.clusters_hidepth. these vals are out of synch so it frags:
```
  File "/usr/local/opt/anaconda/lib/python2.7/site-packages/ipyrad-0.1.25-py2.7.egg/ipyrad/assemble/cluster_across.py", line 370, in singlecat
    icatg[iloc] = catarr[iloc][:icatg.shape[1], :]
ValueError: Index (996) out of range (0-995)
```

**Comment by isaacovercast** [comment]
Hmm, there's some disconnect between singelcat and build_catg_file that i haven't ascertained yet....

**Comment by dereneaton** [comment]
This is now passing for me in all tests with v.0.1.30.
