### ISSUE TITLE
Replace 'zcat' with 'gunzip -c' in zcat_make_temps

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#8]
step1() was failing miserably on mac. I had to roll up the sleeves and dive way way in to figure out that zcat on mac runs in strict posix mode which MEANS it ALWAYS (stupidly) tries to append a .Z to all incoming files, and since it was in ipclient i wasn't getting good return info about the failed call.

From the gzip man page: "zcat  is  identical to gunzip -c." This is FALSE! gunzip -c doesn't append .Z, so it is more portable.

Same issue as this: https://github.com/dalibo/pgbadger/issues/70

**Comment by isaacovercast** [comment]
Fixed on master and verified it now works on mac and linux.

**Comment by dereneaton** [comment]
Awesome!
