### ISSUE TITLE
Get ipyrad in conda and pip

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#86]
I looked at the packages that are defualt supported by continuum inside [the Anaconda package list](http://docs.continuum.io/anaconda/pkg-docs) and it doesn't look like ipyrad would be a good fit for what's already in there. What's already in there are more like engines, frameworks, interfaces, and support libraries. I think if we get ipyrad in pip, then conda will still find it and install. Workin on it..

**Comment by isaacovercast** [comment]
* Make your changes and commit.
* Update ipyrad version: `./versioner.py 0.1.watever`
 * NB: pypi rejects packages with duplicate versions, so you have to always version new packages before you upload them.
* Build the source package: `python setup.py sdist`
* Upload the package to pip: `python setup.py sdist upload`

**Comment by isaacovercast** [comment]
numba requirement will virtually ensure we can not use pip to install ipyrad.
https://pypi.python.org/pypi/numba
numba install requires you to either use conda or do a bunch of shit by hand because one of the packages it requires is extremely pissy about how you install it.

**Comment by isaacovercast** [comment]
I had the idea to use pip to install miniconda to pull down ipyrad, but i think that's too hackish. Seems like we just can't support pip install, unless the numba dependency changes.

**Comment by isaacovercast** [comment]
Maybe try to get versioner to build both linux and mac packages? Or at least allow versioner to be run twice on the same version (test if version already exists) so the versions for mac and linux can be the same.

**Comment by dereneaton** [comment]
Still looks like 0.1.37 is the latest install that miniconda can find:
```
[de243@login-0-1 ~]$ conda upgrade -c ipyrad ipyrad
Fetching package metadata: ......
# All requested packages already installed.
# packages in environment at /home2/de243/miniconda2:
#
ipyrad                    0.1.37                        6    ipyrad
[de243@login-0-1 ~]$ 
```

**Comment by isaacovercast** [comment]
fixed
