### ISSUE TITLE
don't build catgs twice (steps 4 & 5)

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#89]
Step 4 builds a catg array from all clusters in a sample's clust.gz file and then uses only the high depth columns to get site counts for parameter estimation. Step 5 also builds a catg array from a sample's clust.gz file, but only for the high depth clusters. 

It would be more efficient save the catg array from step4, and then simply subsample from it to build the catg array in step5. This would speed up step5 a bunch.

**Comment by isaacovercast** [comment]
This is not a time intensive process, so we'll just leave it.
