### ISSUE TITLE
Resolve issue with data.name in CLI

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#93]
assembly.name is set as the final directory in the working_directory path. ~~This could cause problems, for example "What happens if workdir is ./"? ~~ This is fixed.

"I feel like workdir doesn't make it clear that this is a new to level dir that we're going to make. Maybe if we called it project_name it would be more clear?

The problem is still, users will get to step 7 and want to output results for several mindepth settings and they need to be able to give different names to the outputs."

**Comment by dereneaton** [comment]
In the API we name the data sets as `data = ip.Assemble('name')`
In the CLI let's just name them with a new parameter 0 from the params file. 

```
------ ipyrad params file (v.0.1.33)--------------------------------------------
data1                          ## [0] Assembly name (prefix name for output files)
./cli                          ## [1] Project dir (made in curdir if not present)
./data/sim_rad1*.fastq.gz      ## [2] Location of raw non-demultiplexed fastq files
./data/sim_rad1*barcodes.txt   ## [3] Location of barcodes file
...
```

I kind of like calling param1 project_dir instead of working_dir. Do you think it would be too big of pain to change it?

**Comment by isaacovercast** [comment]
Since paramsdict is 1 indexed now there are a bunch of small changes to fix if we're adding a 0 index:
* assembly.get_params()
* assembly.set_params()

Fixed. df4a7cd..a12105c
