### ISSUE TITLE
ipcluster not dying on exit?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#95]
My suspicion is that kbd interrupts aren't killing ipcluster in a way that makes them happy. Tons of orphaned engines and controllers on my test box. Granted, i'm ctrl+c'ing those mofo's like mad, but still they should get cleaned up nicely. I'll look into it.

**Comment by dereneaton** [comment]
I think we fit it with: 
```
if data._interactive:
    ipyclient.shutdown()
```
In the kbd section of the wrapper function. I'm just not sure the interactive attr is being set correct.

**Comment by isaacovercast** [comment]
Figured it out, but haven't figured out how to fix it yet. If you kbd interrupt inside _launch() then ipyclient is unset, so attempts to call close() on it fail.

**Comment by isaacovercast** [comment]
c58ad47 

wrap calls to sleep() inside _launch to trap keyboard interrupts. Prevents users from killing during cluster init. Prevents zombie ipyclients for impatient users (me).

**Comment by alexkrohn** [comment]
Hi @isaacovercast. This is also happening to me when I ctrl+C during tetrad runs. Can you explain how to manually shut down the zombie ipyclients? Thanks!

**Comment by isaacovercast** [comment]
Hm, well there's not really an easy way of doing this, you just have to do it by hand (assuming the `ipcluster` controller died). You can `ps -ef | grep ipyrad` and this should list all the engines/controllers which you can stop using `kill` and then passing in the PID of each process. If the `ipcluster` process still exists then you should be able to see the `cluster-id` argument, which you can then use to `ipcluster stop --cluster-id=XXX` <- replace with whatever cluster id you see running.

An easier (though more annoying) way to do this is just to restart the computer, if you are able to. This will kill all the zombie procs and also free up whatever memory they are grabbing. This is not the best way, but it's the easiest way.

**Comment by alexkrohn** [comment]
Thanks for that. They were all ipcluster runs, so I was able to kill all 139 zombie processes (!!) with a few `ipcluster stop` commands with various cluster ids. I can't restart the server, as there are a bunch of other jobs running. Does this mean there is no "correct" way to keyboard interrupt a function that uses `ipcluster`?

(On a tangential aside, is there a place where all of the analysis python functions are documented? I.e. all of the options/parameters for each of the functions, like [this page](https://ipyrad.readthedocs.io/en/master/6-params.html), or an `ipyrad -h`, or an R package manual, for the analysis functions?) 

Thanks again!

**Comment by isaacovercast** [comment]
I'm not 100% what the best way to kbd interrupt ipcluster running jobs is, sorry to day. I don't have to do it that often, so when I do i just clean stuff up by hand. Maybe there's a better way....

There is not a central location for all the ipyrad analysis functions and their parameters, unfortunately. Besides the analysis cookbooks, which show many of the functions and parameters, there's not a documented API. Deren and I are working on the ipyrad.analysis manu, which will probably spur us to generate better API-like docs for the analysis tools.

**Comment by alexkrohn** [comment]
Got it. Thanks for your help.

So far the few tutorials have been helpful enough -- especially when Python
noobies like myself can just export the dataframes to R to re-plot. But it
would be great to understand what other parameters could be adjusted. I
look forward to the developments.

Thanks again.

-Alex
