### ISSUE TITLE
redundancy/confusion: self.name & self.paramsdict.assembly_name 

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#96]
In the API naming is done when Assembly objects are created as a required argument, and this name is stuck to the object and not recommended to be changed. That way it is easy to trace all files that were created under the Assembly parameters of this object. e.g., 
```
data1 = ip.Assembly('data1')
```

To create new (branching) assemblies from this one we use the Assembly.copy('newname') function. This is consistent with providing a name at the time that Assembly objects are created and then not changing it. 
```
data2 = data1.copy('data2')
```

The CLI is currently allowing the name to be changed, which then changes the name of future output files. This is like a branching event, however, the Sample objects are not deep-copied to the new object, and so changes to the Samples under one name also make changes under the other...
```
## run with param 0 set to 'data1'
ipyrad -p params.txt -s 12

## now change param 0 to 'data2' and run the next step
ipyrad -p params.txt -s 3    ## --> error no files were found
 ```

Maybe a good fix would be to make a --branch 'newname' argument for the CLI. This could just run copy on the new object and then save. Then if the params.txt file is called with a name matching the existing assembly object it will load in the new copied object. If there isn't a copied object it will complain that there are no Samples in an Assembly with that name. 

```
## with param 0 == 'data1' run Samples through step2
ipyrad -p params.txt -s 12

## create a branch of this Assembly 
ipyrad -p params.txt --branch 'data2'

## this would create and save data2.assembly and data2-params.txt

## we can then run on each assembly independently
ipyrad -p params.txt -s 3
ipyrad -p data2-params.txt -s 3
```

In this way param0 is only used to set Assembly.name, and the two are always equal. And therefore I think it should not be included in the paramsdict, but rather only parsed from params.txt in `__main__`.

**Comment by isaacovercast** [comment]
I see, yes this makes sense. I like where youre going. I might suggest a modification. There's a strong correlation between params.txt, paramsdict, assembly.write_params() and paramsinfo. They all rely on the 1-to-1 correspondence between elements in the dictionary and the txt file. Messing with this correspondence might cause disharmony. What if instead we made param0 'immutable', it's set once and then further calls to set_params("assembly_name") return an error message with instructions for how to create a branch.

**Comment by dereneaton** [comment]
Niiiice. I like it.

**Comment by isaacovercast** [comment]
7007f41918bb4bc7d4117db319433ecddfdce94f

**Comment by isaacovercast** [comment]
set_params on assembly_name now errors out with a helpful message. Assembly
name is SET at creation time, and is "unmodifiable". This is through both
the CLI and the API, so the behavior is consistent. Also added some error
checking at Assembly.__init__, basically making sure the passed in name
doesn't have spaces or special characters.
