### ISSUE TITLE
Step 1 - Shave off 1 hour by estimating length of infile

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#98]
Step 1 currently reads through a huge input file during precheck to count length to estimate optimal chunk size. Then it reads through again to actually do the chunking. We could shave ~1hr off this step by estimating input file length. You could read in one line to figure out how long each read is, and we know the compression ratio for ascii text for gzip, so we could approximate the optimal chunk size. This might be a V2 issue. It works for now, but it could be a little faster.

**Comment by dereneaton** [comment]
Is this done?

**Comment by isaacovercast** [comment]
not yet.

**Comment by isaacovercast** [comment]
Fixed in 0.1.85. 2x speedup in step1.
