### ISSUE TITLE
conda - Dependency checking at install time takes for ever

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#99]
Like 15 minutes, which is totally unacceptable. Trying to get some hints from conda about what the problem might be:

`conda update -f --alt-hint -c ipyrad ipyrad`

Other people with similar issues:
* https://github.com/conda/conda/issues/736
* https://github.com/conda/conda/issues/777

**Comment by dereneaton** [comment]
I wonder if dependency checking would be simplified if we list more explicit version numbers, i.e., ipyparallel=4.1.0, pandas=0.17, etc

**Comment by isaacovercast** [comment]
I think that might help, but it could introduce some headaches in the future, if users have a newer version of pandas than is requested by ipyrad i don't know how conda handles that.

**Comment by isaacovercast** [comment]
https://gist.github.com/isaacovercast/060bd4c8e09db5a0ee69

I hopped on the conda gitter channel and worked through it with one of the devs. Turns out there's an issue with the dependency solver. It's a known bug, they are working on a new version of the solver. Watch https://github.com/conda/conda/pull/2000 for info on the rewrite. For now there is no straightforward workaround.

Here is the not-straightforward workaround. If you create a new environment to install ipyrad into then it works good and fast:

`conda create -n ipyrad -c ipyrad ipyrad`

Makes it more complicated to use. I think for now we just need to say in the docs "install from conda, then go get a cup of coffee, it'll be done when you get back."

**Comment by dereneaton** [comment]
I see. Sounds good. Hopefully conda folks resolve it soon. 

I ran into the following problem on my laptop which has py27 and py35 installed. https://github.com/conda/conda-build/issues/704 We could probably support py34/py35 in the long run. Either way, seems we can fix it.

I just did a fresh install on a cluster and it seemed to take around 10-15 minutes with miniconda. I suppose it probably goes much faster if one installs the full anaconda stack, since a lot of the dependencies will be included in that.

**Comment by isaacovercast** [comment]
Tested with full anaconda install and it still takes 15 minutes.

**Comment by mcg1969** [comment]
Well, we just implemented some significant solver improvements. You can try it out here, thanks to @groutr:
```
conda install -c https://conda.anaconda.org/rgrout conda
```
Give it a shot and see if this fixes your issue.

**Comment by isaacovercast** [comment]
New solver implemented in conda 4.0, works great.

**Comment by mcg1969** [comment]
Thanks for the report! It does look like we have a couple of rough edges but I'm pleased that it's handling the tough cases well.
